/*
 * $Id: soc_dnx_implemenation_defines.csv,v 1.1.2.5 Broadcom SDK $
 * 
 * $Copyright: (c) 2016 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 * This file is auto-generated by autoCoder
 * DO NOT EDIT THIS FILE!
 *
 */
#include <shared/bsl.h>
#include <soc/dnx/legacy/dnx_config_imp_defs.h>

#ifdef _ERR_MSG_MODULE_NAME
     #error "_ERR_MSG_MODULE_NAME redefined"
#endif /* _ERR_MSG_MODULE_NAME */

#define _ERR_MSG_MODULE_NAME BSL_SOC_INIT

soc_dnx_implementation_defines_t *soc_dnx_implementation_defines[SOC_MAX_NUM_DEVICES] = {NULL};

int soc_dnx_implementation_defines_init(int unit)
{
    SOCDNX_INIT_FUNC_DEFS;

    switch(SOC_INFO(unit).chip_type){

#ifdef BCM_JERICHO_2_SUPPORT
    case SOC_INFO_CHIP_TYPE_JERICHO_2:
        SOCDNX_IF_ERR_EXIT(soc_dnx_jericho_2_implementation_defines_init(unit));
        break;
#endif /* BCM_JERICHO_2_SUPPORT */

    default:
         SOCDNX_EXIT_WITH_ERR(SOC_E_INIT, (_BSL_SOCDNX_MSG("Defines share autoCoder: Unsupported device, chip type: %d"), SOC_INFO(unit).chip_type));
        break;
    }

exit:
    SOCDNX_FUNC_RETURN;
}

int soc_dnx_implementation_defines_deinit(int unit)
{
    SOCDNX_INIT_FUNC_DEFS;

    switch(SOC_INFO(unit).chip_type){

#ifdef BCM_JERICHO_2_SUPPORT
    case SOC_INFO_CHIP_TYPE_JERICHO_2:
        SOCDNX_IF_ERR_EXIT(soc_dnx_jericho_2_implementation_defines_deinit(unit));
        break;
#endif /* BCM_JERICHO_2_SUPPORT */

    default:
         SOCDNX_EXIT_WITH_ERR(SOC_E_INIT, (_BSL_SOCDNX_MSG("Defines share autoCoder: Unsupported device, chip type: %d"), SOC_INFO(unit).chip_type));
        break;
    }

exit:
    SOCDNX_FUNC_RETURN;
}


