/*
 * $Id: soc_dnx_implemenation_defines.csv,v 1.1.2.5 Broadcom SDK $
 * 
 * $Copyright: (c) 2016 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 * This file is auto-generated by autoCoder
 * DO NOT EDIT THIS FILE!
 *
 */

#include <shared/bsl.h>
#include <soc/defs.h>
#ifdef BCM_JERICHO_2_SUPPORT

#include <soc/dnx/legacy/dnx_config_imp_defs.h>
#include <soc/dnx/legacy/soc_dnx_jericho_2_config_imp_defs.h>

#ifdef _ERR_MSG_MODULE_NAME
    #error "_ERR_MSG_MODULE_NAME redefined"
#endif /* _ERR_MSG_MODULE_NAME */

#define _ERR_MSG_MODULE_NAME BSL_SOC_INIT

CONST soc_dnx_implementation_defines_t soc_dnx_implementation_defines_jericho_2= {
    SOC_DNX_NOF_CHANNELIZED_INTERFACES_JERICHO_2,
    SOC_DNX_NOF_SPECIAL_CHANNELIZED_INTERFACES_JERICHO_2,
    SOC_DNX_NOF_SPECIAL_NON_CHANNELIZED_INTERFACES_JERICHO_2,
    SOC_DNX_NOF_NON_CHANNELIZED_INTERFACES_JERICHO_2,
    SOC_DNX_NOF_CORE_INTERFACES_JERICHO_2,
    SOC_DNX_NOF_FEC_BANKS_JERICHO_2,
    SOC_DNX_IHP_STP_TABLE_NOF_LONGS_JERICHO_2,
    SOC_DNX_IHB_PINFO_PMF_NOF_LONGS_JERICHO_2,
    SOC_DNX_IHB_PMF_PROGRAM_SELECTION_CAM_NOF_LONGS_JERICHO_2,
    SOC_DNX_IHB_FEC_ECMP_NOF_LONGS_JERICHO_2,
    SOC_DNX_EGQ_PPCT_NOF_LONGS_JERICHO_2,
    SOC_DNX_EPNI_PRGE_PROGRAM_SELECTION_CAM_NOF_LONGS_JERICHO_2,
    SOC_DNX_IHP_LIF_ACCESSED_NOF_LINES_JERICHO_2,
    SOC_DNX_IHP_FLP_PROGRAM_SELECTION_CAM_NOF_LONGS_JERICHO_2,
    SOC_DNX_IHP_FLP_LOOKUPS_NOF_LONGS_JERICHO_2,
    SOC_DNX_IHB_PTC_INFO_NOF_LONGS_JERICHO_2,
    SOC_DNX_MACT_LIF_BASE_LENGTH_JERICHO_2,
    SOC_DNX_PPDB_LARGE_EM_FLUSH_DB_NOF_LONGS_JERICHO_2,
    SOC_DNX_MESH_TOPOLOGY_REGISTER_CONFIG_4_VAL_JERICHO_2,
    SOC_DNX_EGR_DELETE_FIFO_ALMOST_FULL_MC_LOW_PRIO_JERICHO_2,
    SOC_DNX_EGR_DELETE_FIFO_ALMOST_FULL_MC_JERICHO_2,
    SOC_DNX_EGR_DELETE_FIFO_ALMOST_FULL_ALL_JERICHO_2,
    SOC_DNX_EGR_DELETE_FIFO_THRESHOLD_MAX_JERICHO_2,
    SOC_DNX_OUTLIF_PROFILE_NOF_BITS_JERICHO_2,
    SOC_DNX_DSP_EVENT_ROUTE_ENTRY_NOF_BITS_JERICHO_2,
    SOC_DNX_MIRROR_SNOOP_DESTINATION_QUEUE_ENCODING_JERICHO_2,
    SOC_DNX_MIRROR_SNOOP_DESTINATION_MULTICAST_ENCODING_JERICHO_2,
    SOC_DNX_MIRROR_SNOOP_DESTINATION_SYS_PHY_PORT_ENCODING_JERICHO_2,
    SOC_DNX_MIRROR_SNOOP_DESTINATION_LAG_ENCODING_JERICHO_2,
    SOC_DNX_MDIO_INT_DIVIDEND_DEFAULT_JERICHO_2,
    SOC_DNX_MDIO_INT_FREQ_DEFAULT_JERICHO_2,
    SOC_DNX_MDIO_INT_OUT_DELAY_DEFAULT_JERICHO_2,
    SOC_DNX_CMD_IPT_SNP_MIR_CMD_MAP_SNOOP_OFFSET_JERICHO_2,
    SOC_DNX_MIRROR_SNOOP_DEST_TM_TABLE_OFFSET_JERICHO_2,
    SOC_DNX_FLP_INSTRUCTIONS_NOF_JERICHO_2,
    SOC_DNX_PP_EG_MIRROR_PROFILE_TABLE_BITS_PER_PROFILE_JERICHO_2,
    SOC_DNX_MIRROR_PROBABILITY_BITS_JERICHO_2,
    SOC_DNX_OAM_ID_NOF_BIT_JERICHO_2,
    SOC_DNX_ILKN_CTXT_MAP_START_JERICHO_2,
    SOC_DNX_NIF_CTXT_MAP_START_JERICHO_2,
    SOC_DNX_RCY_CTXT_MAP_START_CORE_0_JERICHO_2,
    SOC_DNX_RCY_CTXT_MAP_START_CORE_1_JERICHO_2,
    SOC_DNX_CPU_CTXT_MAP_START_JERICHO_2,
    SOC_DNX_SAT_CTXT_MAP_START_JERICHO_2,
    SOC_DNX_RCY_0_INTERFACE_JERICHO_2,
    SOC_DNX_RCY_1_INTERFACE_JERICHO_2,
    SOC_DNX_CPU_INTERFACE_JERICHO_2,
    SOC_DNX_SAT_INTERFACE_JERICHO_2,
    SOC_DNX_EGR_IF_MIN_JERICHO_2,
    SOC_DNX_EGR_IF_CPU_JERICHO_2,
    SOC_DNX_EGR_IF_OLP_JERICHO_2,
    SOC_DNX_EGR_IF_OAMP_JERICHO_2,
    SOC_DNX_EGR_IF_RCY_JERICHO_2,
    SOC_DNX_EGR_IF_SAT_JERICHO_2,
    SOC_DNX_EGR_IF_IPSEC_JERICHO_2,
    SOC_DNX_EGR_IF_MAX_JERICHO_2,
};

/* defines struct init func for jericho_2 */
int soc_dnx_jericho_2_implementation_defines_init(int unit)
{
    SOCDNX_INIT_FUNC_DEFS;

    if ( soc_dnx_implementation_defines[unit] == NULL ) {
        soc_dnx_implementation_defines[unit] = (soc_dnx_implementation_defines_t *) sal_alloc(sizeof(soc_dnx_implementation_defines_t),"Defines struct");
        if ( soc_dnx_implementation_defines[unit] == NULL ) {
            SOCDNX_EXIT_WITH_ERR(SOC_E_MEMORY, (_BSL_SOCDNX_MSG("Failed to allocate memory for configuration defines struct")));
        }
    }
        sal_memcpy(soc_dnx_implementation_defines[unit], &soc_dnx_implementation_defines_jericho_2, sizeof(soc_dnx_implementation_defines_t));

exit:
    SOCDNX_FUNC_RETURN;
}

/* defines struct deinit func for jericho_2 */
int soc_dnx_jericho_2_implementation_defines_deinit(int unit)
{
    if ( soc_dnx_implementation_defines[unit] != NULL ) {
        sal_free(soc_dnx_implementation_defines[unit]);
        soc_dnx_implementation_defines[unit] = NULL;
    }

    return SOC_E_NONE;
}

/**************************************/
/*  Operation mode specific logic    */
/**************************************/

#endif /* BCM_JERICHO_2_SUPPORT */
