# $Id: $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/esw/titan2

include ${SDK}/make/Make.config

lib = libtitan2

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
