
/*
 * $Id: cmu_cint.stg,v 1.4 Broadcom SDK $    
 * $Copyright: (c) 2016 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *
 * g3p1_cmu_cint.c: Guadalupe2k V1.3 CMU table manager & wrappers
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from sdk/caladan_ucode/g3p1/src/g3p1_cmu_cfg.lrp.
 * Edits to this file will be lost when it is regenerated.
 *
 */
 int g3p1_ppe_cint_data_not_empty;
#include <sdk_config.h>
#if defined(INCLUDE_LIB_CINT)
#if defined(BCM_CALADAN3_SUPPORT) && defined(BCM_CALADAN3_G3P1_SUPPORT)

#include <cint_config.h>
#include <cint_types.h>
#include <cint_porting.h>
#include <sal/core/libc.h>

#include <soc/sbx/g3p1/g3p1_int.h>
#define UTG_MALLOC(x) sal_alloc((x), "utg");
 

#include <soc/sbx/g3p1/g3p1_cmu.h>
#include <soc/sbx/g3p1/g3p1_cmu_sim.h>

static void*
__cint_maddr__soc_sbx_g3p1_simple32_count_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_simple32_count_t* s = (soc_sbx_g3p1_simple32_count_t*) p;

  switch (mnum) {
    case 0: rv = &(s->accumulator); break;
    default: rv = NULL; break;
  }

    return rv;
}
 
static void*
__cint_maddr__soc_sbx_g3p1_simple64_count_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_simple64_count_t* s = (soc_sbx_g3p1_simple64_count_t*) p;

  switch (mnum) {
    case 0: rv = &(s->accumulator); break;
    default: rv = NULL; break;
  }

    return rv;
}
 
static void*
__cint_maddr__soc_sbx_g3p1_turbo32_count_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_turbo32_count_t* s = (soc_sbx_g3p1_turbo32_count_t*) p;

  switch (mnum) {
    case 0: rv = &(s->bytes); break;
    case 1: rv = &(s->packets); break;
    default: rv = NULL; break;
  }

    return rv;
}
 
static void*
__cint_maddr__soc_sbx_g3p1_turbo64_count_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_turbo64_count_t* s = (soc_sbx_g3p1_turbo64_count_t*) p;

  switch (mnum) {
    case 0: rv = &(s->bytes); break;
    case 1: rv = &(s->packets); break;
    default: rv = NULL; break;
  }

    return rv;
}
 
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_simple32_count_t[] = 
{
     {
       "unsigned long long",
       "accumulator",
       0,
       0
     },
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_simple64_count_t[] = 
{
     {
       "unsigned long long",
       "accumulator",
       0,
       0
     },
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_turbo32_count_t[] = 
{
     {
       "unsigned long long",
       "bytes",
       0,
       0
     },
     {
       "unsigned long long",
       "packets",
       0,
       0
     },
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_turbo64_count_t[] = 
{
     {
       "unsigned long long",
       "bytes",
       0,
       0
     },
     {
       "unsigned long long",
       "packets",
       0,
       0
     },
    { NULL }
};

/*
 * struct type table
 */ 
static cint_struct_type_t __cint_g3p1_structures [] = 
{
  {
        "soc_sbx_g3p1_simple32_count_t",
        sizeof(soc_sbx_g3p1_simple32_count_t),
        __cint_struct_members__soc_sbx_g3p1_simple32_count_t,
        __cint_maddr__soc_sbx_g3p1_simple32_count_t
  },
  {
        "soc_sbx_g3p1_simple64_count_t",
        sizeof(soc_sbx_g3p1_simple64_count_t),
        __cint_struct_members__soc_sbx_g3p1_simple64_count_t,
        __cint_maddr__soc_sbx_g3p1_simple64_count_t
  },
  {
        "soc_sbx_g3p1_turbo32_count_t",
        sizeof(soc_sbx_g3p1_turbo32_count_t),
        __cint_struct_members__soc_sbx_g3p1_turbo32_count_t,
        __cint_maddr__soc_sbx_g3p1_turbo32_count_t
  },
  {
        "soc_sbx_g3p1_turbo64_count_t",
        sizeof(soc_sbx_g3p1_turbo64_count_t),
        __cint_struct_members__soc_sbx_g3p1_turbo64_count_t,
        __cint_maddr__soc_sbx_g3p1_turbo64_count_t
  },
  { NULL }
};
 


          
  CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_pdctr_read,
                           int, int, unit, 0, 0, 
                           uint32, uint32, ulIndex, 0, 0, 
                           uint32, uint32, ulEntries, 0, 0, 
                           int, int, clear, 0, 0, 
                           soc_sbx_g3p1_turbo64_count_t*, soc_sbx_g3p1_turbo64_count_t, pCount, 1, 0);
  CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_pdctr_clear,
                           int, int, unit, 0, 0);
  CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_rtctr_read,
                           int, int, unit, 0, 0, 
                           uint32, uint32, ulIndex, 0, 0, 
                           uint32, uint32, ulEntries, 0, 0, 
                           int, int, clear, 0, 0, 
                           soc_sbx_g3p1_turbo64_count_t*, soc_sbx_g3p1_turbo64_count_t, pCount, 1, 0);
  CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_rtctr_clear,
                           int, int, unit, 0, 0);
  CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_ertctr_read,
                           int, int, unit, 0, 0, 
                           uint32, uint32, ulIndex, 0, 0, 
                           uint32, uint32, ulEntries, 0, 0, 
                           int, int, clear, 0, 0, 
                           soc_sbx_g3p1_turbo64_count_t*, soc_sbx_g3p1_turbo64_count_t, pCount, 1, 0);
  CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_ertctr_clear,
                           int, int, unit, 0, 0);
  CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_excctr_read,
                           int, int, unit, 0, 0, 
                           uint32, uint32, ulIndex, 0, 0, 
                           uint32, uint32, ulEntries, 0, 0, 
                           int, int, clear, 0, 0, 
                           soc_sbx_g3p1_turbo64_count_t*, soc_sbx_g3p1_turbo64_count_t, pCount, 1, 0);
  CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_excctr_clear,
                           int, int, unit, 0, 0);
  CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_ingctr_read,
                           int, int, unit, 0, 0, 
                           uint32, uint32, ulIndex, 0, 0, 
                           uint32, uint32, ulEntries, 0, 0, 
                           int, int, clear, 0, 0, 
                           soc_sbx_g3p1_turbo64_count_t*, soc_sbx_g3p1_turbo64_count_t, pCount, 1, 0);
  CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_ingctr_clear,
                           int, int, unit, 0, 0);
  CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_egrctr_read,
                           int, int, unit, 0, 0, 
                           uint32, uint32, ulIndex, 0, 0, 
                           uint32, uint32, ulEntries, 0, 0, 
                           int, int, clear, 0, 0, 
                           soc_sbx_g3p1_turbo64_count_t*, soc_sbx_g3p1_turbo64_count_t, pCount, 1, 0);
  CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_egrctr_clear,
                           int, int, unit, 0, 0);
  CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_sample_simple32ctr_read,
                           int, int, unit, 0, 0, 
                           uint32, uint32, ulIndex, 0, 0, 
                           uint32, uint32, ulEntries, 0, 0, 
                           int, int, clear, 0, 0, 
                           soc_sbx_g3p1_simple32_count_t*, soc_sbx_g3p1_simple32_count_t, pCount, 1, 0);
  CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_sample_simple32ctr_clear,
                           int, int, unit, 0, 0);
  CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_sample_simple64ctr_read,
                           int, int, unit, 0, 0, 
                           uint32, uint32, ulIndex, 0, 0, 
                           uint32, uint32, ulEntries, 0, 0, 
                           int, int, clear, 0, 0, 
                           soc_sbx_g3p1_simple64_count_t*, soc_sbx_g3p1_simple64_count_t, pCount, 1, 0);
  CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_sample_simple64ctr_clear,
                           int, int, unit, 0, 0);
  CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_sample_turbo32ctr_read,
                           int, int, unit, 0, 0, 
                           uint32, uint32, ulIndex, 0, 0, 
                           uint32, uint32, ulEntries, 0, 0, 
                           int, int, clear, 0, 0, 
                           soc_sbx_g3p1_turbo32_count_t*, soc_sbx_g3p1_turbo32_count_t, pCount, 1, 0);
  CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_sample_turbo32ctr_clear,
                           int, int, unit, 0, 0);
  CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_sample_cmurangectr_read,
                           int, int, unit, 0, 0, 
                           uint32, uint32, ulIndex, 0, 0, 
                           uint32, uint32, ulEntries, 0, 0, 
                           int, int, clear, 0, 0, 
                           soc_sbx_g3p1_range_count_t*, soc_sbx_g3p1_range_count_t, pCount, 1, 0);
  CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_sample_cmurangectr_clear,
                           int, int, unit, 0, 0);  

static cint_function_t __cint_g3p1_functions [] =
{           
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_pdctr_read),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_pdctr_clear),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_rtctr_read),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_rtctr_clear),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_ertctr_read),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_ertctr_clear),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_excctr_read),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_excctr_clear),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_ingctr_read),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_ingctr_clear),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_egrctr_read),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_egrctr_clear),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_sample_simple32ctr_read),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_sample_simple32ctr_clear),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_sample_simple64ctr_read),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_sample_simple64ctr_clear),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_sample_turbo32ctr_read),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_sample_turbo32ctr_clear),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_sample_cmurangectr_read),
    CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_sample_cmurangectr_clear),
  { NULL }
};    

/* 
 * CINT exported datastructure
 */ 
cint_data_t g3p1_cmu_cint_data =
{
    NULL,
    __cint_g3p1_functions,
    __cint_g3p1_structures,
    NULL,   /* __cint_g3p1_enums */
    NULL,   /* __cint_g3p1_typedefs */
    NULL,   /* __cint_g3p1_constants */
    NULL,   /* __cint_g3p1_function_pointers */
};

#endif
#endif
