
/**
 *
 * $Id: tmu_cint.stg,v 1.7 Broadcom SDK $   
 * $Copyright: (c) 2016 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from $SDK/caladan_ucode/g3p1/src/g3p1_tmu_cfg.lrp
 * Edits to this file will be lost when it is regenerated.
 */
 
int g3p1_tmu_cint_data_not_empty;
#include <sdk_config.h>
#if defined(INCLUDE_LIB_CINT)
#if defined(BCM_CALADAN3_SUPPORT) && defined(BCM_CALADAN3_G3P1_SUPPORT)

#include <cint_config.h>
#include <cint_types.h>
#include <cint_porting.h>
#include <sal/core/libc.h>

#include <soc/sbx/g3p1/g3p1_int.h>
#define UTG_MALLOC(x) sal_alloc((x), "utg");

 
                

/*
 * Hash table entry accessor implementations for mac
 */

CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_mac_t_init, soc_sbx_g3p1_mac_t*,  soc_sbx_g3p1_mac_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_mac_set,
                        int, int, unit, 0, 0, 
                        uint8*, uint8, imac, 1, 0,
                        int, int, ivsi, 0, 0,
                        soc_sbx_g3p1_mac_t*, soc_sbx_g3p1_mac_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_mac_add,
                        int, int, unit, 0, 0, 
                        uint8*, uint8, imac, 1, 0,
                        int, int, ivsi, 0, 0,
                        soc_sbx_g3p1_mac_t*, soc_sbx_g3p1_mac_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_mac_get,
                        int, int, unit, 0, 0, 
                        uint8*, uint8, imac, 1, 0,
                        int, int, ivsi, 0, 0,
                        soc_sbx_g3p1_mac_t*, soc_sbx_g3p1_mac_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_mac_update,
                        int, int, unit, 0, 0, 
                        uint8*, uint8, imac, 1, 0,
                        int, int, ivsi, 0, 0,
                        soc_sbx_g3p1_mac_t*, soc_sbx_g3p1_mac_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_mac_delete,
                        int, int, unit, 0, 0, 
                        uint8*, uint8, imac, 1, 0,
                        int, int, ivsi, 0, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_mac_remove,
                        int, int, unit, 0, 0, 
                        uint8*, uint8, imac, 1, 0,
                        int, int, ivsi, 0, 0);
                                                                                               
/*
 * Struct soc_sbx_g3p1_mac_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_mac_t[] = 
{




    {
      "uint32",
      "ageid",
      0,
      0
    },
    {
      "uint32",
      "smac_hit",
      0,
      0
    },
    {
      "uint32",
      "sdrop",
      0,
      0
    },
    {
      "uint32",
      "dontage",
      0,
      0
    },
    {
      "uint32",
      "sreserved",
      0,
      0
    },
    {
      "uint32",
      "pending",
      0,
      0
    },
    {
      "uint32",
      "poe",
      0,
      0
    },

    {
      "uint32",
      "dmac_hit",
      0,
      0
    },
    {
      "uint32",
      "dcopy",
      0,
      0
    },
    {
      "uint32",
      "ddrop",
      0,
      0
    },
    {
      "uint32",
      "dreserved",
      0,
      0
    },
    {
      "uint32",
      "ftidx",
      0,
      0
    },
  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_mac_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_mac_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_mac_t* s = (soc_sbx_g3p1_mac_t*) p;

        switch (mnum) {
                case 0: rv = &(s->ageid); break;
                case 1: rv = &(s->smac_hit); break;
                case 2: rv = &(s->sdrop); break;
                case 3: rv = &(s->dontage); break;
                case 4: rv = &(s->sreserved); break;
                case 5: rv = &(s->pending); break;
                case 6: rv = &(s->poe); break;
                case 7: rv = &(s->dmac_hit); break;
                case 8: rv = &(s->dcopy); break;
                case 9: rv = &(s->ddrop); break;
                case 10: rv = &(s->dreserved); break;
                case 11: rv = &(s->ftidx); break;
          default: rv = NULL; break;
        }

    return rv;
}
 

/*
 * Hash table entry accessor implementations for pvv2e
 */

CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_pvv2e_t_init, soc_sbx_g3p1_pvv2e_t*,  soc_sbx_g3p1_pvv2e_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_pvv2e_set,
                        int, int, unit, 0, 0, 
                        int, int, iivid, 0, 0,
                        int, int, iovid, 0, 0,
                        int, int, iport, 0, 0,
                        soc_sbx_g3p1_pvv2e_t*, soc_sbx_g3p1_pvv2e_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_pvv2e_add,
                        int, int, unit, 0, 0, 
                        int, int, iivid, 0, 0,
                        int, int, iovid, 0, 0,
                        int, int, iport, 0, 0,
                        soc_sbx_g3p1_pvv2e_t*, soc_sbx_g3p1_pvv2e_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_pvv2e_get,
                        int, int, unit, 0, 0, 
                        int, int, iivid, 0, 0,
                        int, int, iovid, 0, 0,
                        int, int, iport, 0, 0,
                        soc_sbx_g3p1_pvv2e_t*, soc_sbx_g3p1_pvv2e_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_pvv2e_update,
                        int, int, unit, 0, 0, 
                        int, int, iivid, 0, 0,
                        int, int, iovid, 0, 0,
                        int, int, iport, 0, 0,
                        soc_sbx_g3p1_pvv2e_t*, soc_sbx_g3p1_pvv2e_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_pvv2e_delete,
                        int, int, unit, 0, 0, 
                        int, int, iivid, 0, 0,
                        int, int, iovid, 0, 0,
                        int, int, iport, 0, 0);
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_pvv2e_remove,
                        int, int, unit, 0, 0, 
                        int, int, iivid, 0, 0,
                        int, int, iovid, 0, 0,
                        int, int, iport, 0, 0);
                                                                                               
/*
 * Struct soc_sbx_g3p1_pvv2e_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_pvv2e_t[] = 
{





    {
      "uint32",
      "pad",
      0,
      0
    },
    {
      "uint32",
      "vpws",
      0,
      0
    },


    {
      "uint32",
      "stpstate",
      0,
      0
    },
    {
      "uint32",
      "vlan",
      0,
      0
    },
    {
      "uint32",
      "lpi",
      0,
      0
    },
    {
      "uint32",
      "hit",
      0,
      0
    },
    {
      "uint32",
      "keeporstrip",
      0,
      0
    },
    {
      "uint32",
      "replace",
      0,
      0
    },
    {
      "uint32",
      "vid",
      0,
      0
    },

  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_pvv2e_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_pvv2e_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_pvv2e_t* s = (soc_sbx_g3p1_pvv2e_t*) p;

        switch (mnum) {
                case 0: rv = &(s->pad); break;
                case 1: rv = &(s->vpws); break;
                case 2: rv = &(s->stpstate); break;
                case 3: rv = &(s->vlan); break;
                case 4: rv = &(s->lpi); break;
                case 5: rv = &(s->hit); break;
                case 6: rv = &(s->keeporstrip); break;
                case 7: rv = &(s->replace); break;
                case 8: rv = &(s->vid); break;
          default: rv = NULL; break;
        }

    return rv;
}
 

/*
 * Hash table entry accessor implementations for labels
 */

CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_labels_t_init, soc_sbx_g3p1_labels_t*,  soc_sbx_g3p1_labels_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0, soc_sbx_g3p1_labels_set,
                        int, int, unit, 0, 0, 
                        int, int, ilabel2, 0, 0,
                        int, int, iresv, 0, 0,
                        int, int, iport, 0, 0,
                        int, int, ilabel1, 0, 0,
                        soc_sbx_g3p1_labels_t*, soc_sbx_g3p1_labels_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0, soc_sbx_g3p1_labels_add,
                        int, int, unit, 0, 0, 
                        int, int, ilabel2, 0, 0,
                        int, int, iresv, 0, 0,
                        int, int, iport, 0, 0,
                        int, int, ilabel1, 0, 0,
                        soc_sbx_g3p1_labels_t*, soc_sbx_g3p1_labels_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0, soc_sbx_g3p1_labels_get,
                        int, int, unit, 0, 0, 
                        int, int, ilabel2, 0, 0,
                        int, int, iresv, 0, 0,
                        int, int, iport, 0, 0,
                        int, int, ilabel1, 0, 0,
                        soc_sbx_g3p1_labels_t*, soc_sbx_g3p1_labels_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0, soc_sbx_g3p1_labels_update,
                        int, int, unit, 0, 0, 
                        int, int, ilabel2, 0, 0,
                        int, int, iresv, 0, 0,
                        int, int, iport, 0, 0,
                        int, int, ilabel1, 0, 0,
                        soc_sbx_g3p1_labels_t*, soc_sbx_g3p1_labels_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_labels_delete,
                        int, int, unit, 0, 0, 
                        int, int, ilabel2, 0, 0,
                        int, int, iresv, 0, 0,
                        int, int, iport, 0, 0,
                        int, int, ilabel1, 0, 0);
CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_labels_remove,
                        int, int, unit, 0, 0, 
                        int, int, ilabel2, 0, 0,
                        int, int, iresv, 0, 0,
                        int, int, iport, 0, 0,
                        int, int, ilabel1, 0, 0);
                                                                                               
/*
 * Struct soc_sbx_g3p1_labels_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_labels_t[] = 
{





    {
      "uint32",
      "pad",
      0,
      0
    },
    {
      "uint32",
      "opcode",
      0,
      0
    },
    {
      "uint32",
      "ftidx",
      0,
      0
    },
    {
      "uint32",
      "vlan",
      0,
      0
    },
    {
      "uint32",
      "hit",
      0,
      0
    },
    {
      "uint32",
      "lock",
      0,
      0
    },
    {
      "uint32",
      "keep_sdtag",
      0,
      0
    },
    {
      "uint32",
      "pipe",
      0,
      0
    },
    {
      "uint32",
      "elsp",
      0,
      0
    },
    {
      "uint32",
      "stpstate",
      0,
      0
    },


    {
      "uint32",
      "vpws",
      0,
      0
    },
    {
      "uint32",
      "loop",
      0,
      0
    },
    {
      "uint32",
      "cos",
      0,
      0
    },
    {
      "uint32",
      "lpi",
      0,
      0
    },
  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_labels_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_labels_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_labels_t* s = (soc_sbx_g3p1_labels_t*) p;

        switch (mnum) {
                case 0: rv = &(s->pad); break;
                case 1: rv = &(s->opcode); break;
                case 2: rv = &(s->ftidx); break;
                case 3: rv = &(s->vlan); break;
                case 4: rv = &(s->hit); break;
                case 5: rv = &(s->lock); break;
                case 6: rv = &(s->keep_sdtag); break;
                case 7: rv = &(s->pipe); break;
                case 8: rv = &(s->elsp); break;
                case 9: rv = &(s->stpstate); break;
                case 10: rv = &(s->vpws); break;
                case 11: rv = &(s->loop); break;
                case 12: rv = &(s->cos); break;
                case 13: rv = &(s->lpi); break;
          default: rv = NULL; break;
        }

    return rv;
}
 

/*
 * TAPS table entry accesser functions
 */
CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_v4da_t_init, soc_sbx_g3p1_v4da_t*,  soc_sbx_g3p1_v4da_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_v4da_table_size_get,
                        int, int, unit, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_g3p1_v4da_table_size_set,
                        int, int, unit, 0, 0,
                        int, int, size, 0, 0);                            
CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_v4da_set,
                        int, int, unit, 0, 0, 
                        int, int, ivrf, 0, 0,
                        int, int, ida, 0, 0,
                        int, int, inetmask_num_bits, 0, 0,
                        soc_sbx_g3p1_v4da_t*, soc_sbx_g3p1_v4da_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_v4da_get,
                        int, int, unit, 0, 0, 
                        int, int, ivrf, 0, 0,
                        int, int, ida, 0, 0,
                        int, int, inetmask_num_bits, 0, 0,
                        soc_sbx_g3p1_v4da_t*, soc_sbx_g3p1_v4da_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_v4da_delete,
                        int, int, unit, 0, 0, 
                        int, int, ivrf, 0, 0,
                        int, int, ida, 0, 0,
                        int, int, inetmask_num_bits, 0, 0);
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_v4da_remove,
                        int, int, unit, 0, 0, 
                        int, int, ivrf, 0, 0,
                        int, int, ida, 0, 0,
                        int, int, inetmask_num_bits, 0, 0);
                                                                                               
/*
 * Struct soc_sbx_g3p1_v4da_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_v4da_t[] = 
{






    {
      "uint32",
      "vid",
      0,
      0
    },
    {
      "uint32",
      "ecmpmask",
      0,
      0
    },
    {
      "uint32",
      "ftidx",
      0,
      0
    },
  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_v4da_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_v4da_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_v4da_t* s = (soc_sbx_g3p1_v4da_t*) p;

        switch (mnum) {
                case 0: rv = &(s->vid); break;
                case 1: rv = &(s->ecmpmask); break;
                case 2: rv = &(s->ftidx); break;
          default: rv = NULL; break;
        }

    return rv;
}


/*
 * TAPS table entry accesser functions
 */
CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_v4sa_t_init, soc_sbx_g3p1_v4sa_t*,  soc_sbx_g3p1_v4sa_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_v4sa_table_size_get,
                        int, int, unit, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_g3p1_v4sa_table_size_set,
                        int, int, unit, 0, 0,
                        int, int, size, 0, 0);                            
CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_v4sa_set,
                        int, int, unit, 0, 0, 
                        int, int, ivrf, 0, 0,
                        int, int, isa, 0, 0,
                        int, int, inetmask_num_bits, 0, 0,
                        soc_sbx_g3p1_v4sa_t*, soc_sbx_g3p1_v4sa_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_v4sa_get,
                        int, int, unit, 0, 0, 
                        int, int, ivrf, 0, 0,
                        int, int, isa, 0, 0,
                        int, int, inetmask_num_bits, 0, 0,
                        soc_sbx_g3p1_v4sa_t*, soc_sbx_g3p1_v4sa_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_v4sa_delete,
                        int, int, unit, 0, 0, 
                        int, int, ivrf, 0, 0,
                        int, int, isa, 0, 0,
                        int, int, inetmask_num_bits, 0, 0);
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_v4sa_remove,
                        int, int, unit, 0, 0, 
                        int, int, ivrf, 0, 0,
                        int, int, isa, 0, 0,
                        int, int, inetmask_num_bits, 0, 0);
                                                                                               
/*
 * Struct soc_sbx_g3p1_v4sa_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_v4sa_t[] = 
{






    {
      "uint32",
      "pad",
      0,
      0
    },
    {
      "uint32",
      "srccnt",
      0,
      0
    },
    {
      "uint32",
      "srcdrop",
      0,
      0
    },
    {
      "uint32",
      "rpfmode",
      0,
      0
    },
    {
      "uint32",
      "poe",
      0,
      0
    },
  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_v4sa_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_v4sa_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_v4sa_t* s = (soc_sbx_g3p1_v4sa_t*) p;

        switch (mnum) {
                case 0: rv = &(s->pad); break;
                case 1: rv = &(s->srccnt); break;
                case 2: rv = &(s->srcdrop); break;
                case 3: rv = &(s->rpfmode); break;
                case 4: rv = &(s->poe); break;
          default: rv = NULL; break;
        }

    return rv;
}


/*
 * Hash table entry accessor implementations for v4mc_sgv
 */

CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_v4mc_sgv_t_init, soc_sbx_g3p1_v4mc_sgv_t*,  soc_sbx_g3p1_v4mc_sgv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_v4mc_sgv_set,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, isa, 0, 0,
                        int, int, iga, 0, 0,
                        soc_sbx_g3p1_v4mc_sgv_t*, soc_sbx_g3p1_v4mc_sgv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_v4mc_sgv_add,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, isa, 0, 0,
                        int, int, iga, 0, 0,
                        soc_sbx_g3p1_v4mc_sgv_t*, soc_sbx_g3p1_v4mc_sgv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_v4mc_sgv_get,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, isa, 0, 0,
                        int, int, iga, 0, 0,
                        soc_sbx_g3p1_v4mc_sgv_t*, soc_sbx_g3p1_v4mc_sgv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_v4mc_sgv_update,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, isa, 0, 0,
                        int, int, iga, 0, 0,
                        soc_sbx_g3p1_v4mc_sgv_t*, soc_sbx_g3p1_v4mc_sgv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_v4mc_sgv_delete,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, isa, 0, 0,
                        int, int, iga, 0, 0);
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_v4mc_sgv_remove,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, isa, 0, 0,
                        int, int, iga, 0, 0);
                                                                                               
/*
 * Struct soc_sbx_g3p1_v4mc_sgv_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_v4mc_sgv_t[] = 
{





    {
      "uint32",
      "rpfunion",
      0,
      0
    },
    {
      "uint32",
      "ftidx",
      0,
      0
    },
    {
      "uint32",
      "hit",
      0,
      0
    },
    {
      "uint32",
      "rsvd",
      0,
      0
    },
    {
      "uint32",
      "proccopy",
      0,
      0
    },
  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_v4mc_sgv_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_v4mc_sgv_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_v4mc_sgv_t* s = (soc_sbx_g3p1_v4mc_sgv_t*) p;

        switch (mnum) {
                case 0: rv = &(s->rpfunion); break;
                case 1: rv = &(s->ftidx); break;
                case 2: rv = &(s->hit); break;
                case 3: rv = &(s->rsvd); break;
                case 4: rv = &(s->proccopy); break;
          default: rv = NULL; break;
        }

    return rv;
}
 

/*
 * Hash table entry accessor implementations for v4mc_gv
 */

CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_v4mc_gv_t_init, soc_sbx_g3p1_v4mc_gv_t*,  soc_sbx_g3p1_v4mc_gv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_v4mc_gv_set,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, iga, 0, 0,
                        soc_sbx_g3p1_v4mc_gv_t*, soc_sbx_g3p1_v4mc_gv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_v4mc_gv_add,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, iga, 0, 0,
                        soc_sbx_g3p1_v4mc_gv_t*, soc_sbx_g3p1_v4mc_gv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_v4mc_gv_get,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, iga, 0, 0,
                        soc_sbx_g3p1_v4mc_gv_t*, soc_sbx_g3p1_v4mc_gv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_v4mc_gv_update,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, iga, 0, 0,
                        soc_sbx_g3p1_v4mc_gv_t*, soc_sbx_g3p1_v4mc_gv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_v4mc_gv_delete,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, iga, 0, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_v4mc_gv_remove,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, iga, 0, 0);
                                                                                               
/*
 * Struct soc_sbx_g3p1_v4mc_gv_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_v4mc_gv_t[] = 
{





    {
      "uint32",
      "rpfunion",
      0,
      0
    },
    {
      "uint32",
      "ftidx",
      0,
      0
    },
    {
      "uint32",
      "hit",
      0,
      0
    },
    {
      "uint32",
      "rsvd",
      0,
      0
    },
    {
      "uint32",
      "proccopy",
      0,
      0
    },
  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_v4mc_gv_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_v4mc_gv_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_v4mc_gv_t* s = (soc_sbx_g3p1_v4mc_gv_t*) p;

        switch (mnum) {
                case 0: rv = &(s->rpfunion); break;
                case 1: rv = &(s->ftidx); break;
                case 2: rv = &(s->hit); break;
                case 3: rv = &(s->rsvd); break;
                case 4: rv = &(s->proccopy); break;
          default: rv = NULL; break;
        }

    return rv;
}
 

/*
 * TAPS table entry accesser functions
 */
CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_v6da_t_init, soc_sbx_g3p1_v6da_t*,  soc_sbx_g3p1_v6da_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_v6da_table_size_get,
                        int, int, unit, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_g3p1_v6da_table_size_set,
                        int, int, unit, 0, 0,
                        int, int, size, 0, 0);                            
CINT_FWRAPPER_CREATE_RP8(int, int, 0, 0, soc_sbx_g3p1_v6da_set,
                        int, int, unit, 0, 0, 
                        int, int, ivrf, 0, 0,
                        int, int, ida0, 0, 0,
                        int, int, ida1, 0, 0,
                        int, int, ida2, 0, 0,
                        int, int, ida3, 0, 0,
                        int, int, inetmask_num_bits, 0, 0,
                        soc_sbx_g3p1_v6da_t*, soc_sbx_g3p1_v6da_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP8(int, int, 0, 0, soc_sbx_g3p1_v6da_get,
                        int, int, unit, 0, 0, 
                        int, int, ivrf, 0, 0,
                        int, int, ida0, 0, 0,
                        int, int, ida1, 0, 0,
                        int, int, ida2, 0, 0,
                        int, int, ida3, 0, 0,
                        int, int, inetmask_num_bits, 0, 0,
                        soc_sbx_g3p1_v6da_t*, soc_sbx_g3p1_v6da_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0, soc_sbx_g3p1_v6da_delete,
                        int, int, unit, 0, 0, 
                        int, int, ivrf, 0, 0,
                        int, int, ida0, 0, 0,
                        int, int, ida1, 0, 0,
                        int, int, ida2, 0, 0,
                        int, int, ida3, 0, 0,
                        int, int, inetmask_num_bits, 0, 0);
CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0, soc_sbx_g3p1_v6da_remove,
                        int, int, unit, 0, 0, 
                        int, int, ivrf, 0, 0,
                        int, int, ida0, 0, 0,
                        int, int, ida1, 0, 0,
                        int, int, ida2, 0, 0,
                        int, int, ida3, 0, 0,
                        int, int, inetmask_num_bits, 0, 0);
                                                                                               
/*
 * Struct soc_sbx_g3p1_v6da_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_v6da_t[] = 
{






    {
      "uint32",
      "vid",
      0,
      0
    },
    {
      "uint32",
      "ecmpmask",
      0,
      0
    },
    {
      "uint32",
      "ftidx",
      0,
      0
    },
  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_v6da_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_v6da_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_v6da_t* s = (soc_sbx_g3p1_v6da_t*) p;

        switch (mnum) {
                case 0: rv = &(s->vid); break;
                case 1: rv = &(s->ecmpmask); break;
                case 2: rv = &(s->ftidx); break;
          default: rv = NULL; break;
        }

    return rv;
}


/*
 * TAPS table entry accesser functions
 */
CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_v6sa_t_init, soc_sbx_g3p1_v6sa_t*,  soc_sbx_g3p1_v6sa_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_v6sa_table_size_get,
                        int, int, unit, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_g3p1_v6sa_table_size_set,
                        int, int, unit, 0, 0,
                        int, int, size, 0, 0);                            
CINT_FWRAPPER_CREATE_RP8(int, int, 0, 0, soc_sbx_g3p1_v6sa_set,
                        int, int, unit, 0, 0, 
                        int, int, ivrf, 0, 0,
                        int, int, isa0, 0, 0,
                        int, int, isa1, 0, 0,
                        int, int, isa2, 0, 0,
                        int, int, isa3, 0, 0,
                        int, int, inetmask_num_bits, 0, 0,
                        soc_sbx_g3p1_v6sa_t*, soc_sbx_g3p1_v6sa_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP8(int, int, 0, 0, soc_sbx_g3p1_v6sa_get,
                        int, int, unit, 0, 0, 
                        int, int, ivrf, 0, 0,
                        int, int, isa0, 0, 0,
                        int, int, isa1, 0, 0,
                        int, int, isa2, 0, 0,
                        int, int, isa3, 0, 0,
                        int, int, inetmask_num_bits, 0, 0,
                        soc_sbx_g3p1_v6sa_t*, soc_sbx_g3p1_v6sa_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0, soc_sbx_g3p1_v6sa_delete,
                        int, int, unit, 0, 0, 
                        int, int, ivrf, 0, 0,
                        int, int, isa0, 0, 0,
                        int, int, isa1, 0, 0,
                        int, int, isa2, 0, 0,
                        int, int, isa3, 0, 0,
                        int, int, inetmask_num_bits, 0, 0);
CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0, soc_sbx_g3p1_v6sa_remove,
                        int, int, unit, 0, 0, 
                        int, int, ivrf, 0, 0,
                        int, int, isa0, 0, 0,
                        int, int, isa1, 0, 0,
                        int, int, isa2, 0, 0,
                        int, int, isa3, 0, 0,
                        int, int, inetmask_num_bits, 0, 0);
                                                                                               
/*
 * Struct soc_sbx_g3p1_v6sa_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_v6sa_t[] = 
{






    {
      "uint32",
      "pad",
      0,
      0
    },
    {
      "uint32",
      "srccnt",
      0,
      0
    },
    {
      "uint32",
      "srcdrop",
      0,
      0
    },
    {
      "uint32",
      "rpfmode",
      0,
      0
    },
    {
      "uint32",
      "poe",
      0,
      0
    },
  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_v6sa_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_v6sa_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_v6sa_t* s = (soc_sbx_g3p1_v6sa_t*) p;

        switch (mnum) {
                case 0: rv = &(s->pad); break;
                case 1: rv = &(s->srccnt); break;
                case 2: rv = &(s->srcdrop); break;
                case 3: rv = &(s->rpfmode); break;
                case 4: rv = &(s->poe); break;
          default: rv = NULL; break;
        }

    return rv;
}


/*
 * Hash table entry accessor implementations for v6mc_gv
 */

CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_v6mc_gv_t_init, soc_sbx_g3p1_v6mc_gv_t*,  soc_sbx_g3p1_v6mc_gv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0, soc_sbx_g3p1_v6mc_gv_set,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, iga0, 0, 0,
                        int, int, iga1, 0, 0,
                        int, int, iga2, 0, 0,
                        int, int, iga3, 0, 0,
                        soc_sbx_g3p1_v6mc_gv_t*, soc_sbx_g3p1_v6mc_gv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0, soc_sbx_g3p1_v6mc_gv_add,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, iga0, 0, 0,
                        int, int, iga1, 0, 0,
                        int, int, iga2, 0, 0,
                        int, int, iga3, 0, 0,
                        soc_sbx_g3p1_v6mc_gv_t*, soc_sbx_g3p1_v6mc_gv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0, soc_sbx_g3p1_v6mc_gv_get,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, iga0, 0, 0,
                        int, int, iga1, 0, 0,
                        int, int, iga2, 0, 0,
                        int, int, iga3, 0, 0,
                        soc_sbx_g3p1_v6mc_gv_t*, soc_sbx_g3p1_v6mc_gv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0, soc_sbx_g3p1_v6mc_gv_update,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, iga0, 0, 0,
                        int, int, iga1, 0, 0,
                        int, int, iga2, 0, 0,
                        int, int, iga3, 0, 0,
                        soc_sbx_g3p1_v6mc_gv_t*, soc_sbx_g3p1_v6mc_gv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0, soc_sbx_g3p1_v6mc_gv_delete,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, iga0, 0, 0,
                        int, int, iga1, 0, 0,
                        int, int, iga2, 0, 0,
                        int, int, iga3, 0, 0);
CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0, soc_sbx_g3p1_v6mc_gv_remove,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, iga0, 0, 0,
                        int, int, iga1, 0, 0,
                        int, int, iga2, 0, 0,
                        int, int, iga3, 0, 0);
                                                                                               
/*
 * Struct soc_sbx_g3p1_v6mc_gv_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_v6mc_gv_t[] = 
{





    {
      "uint32",
      "rpfunion",
      0,
      0
    },
    {
      "uint32",
      "ftidx",
      0,
      0
    },
    {
      "uint32",
      "hit",
      0,
      0
    },
    {
      "uint32",
      "rsvd",
      0,
      0
    },
    {
      "uint32",
      "proccopy",
      0,
      0
    },
  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_v6mc_gv_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_v6mc_gv_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_v6mc_gv_t* s = (soc_sbx_g3p1_v6mc_gv_t*) p;

        switch (mnum) {
                case 0: rv = &(s->rpfunion); break;
                case 1: rv = &(s->ftidx); break;
                case 2: rv = &(s->hit); break;
                case 3: rv = &(s->rsvd); break;
                case 4: rv = &(s->proccopy); break;
          default: rv = NULL; break;
        }

    return rv;
}
 

/*
 * Hash table entry accessor implementations for v6mc_sgv
 */

CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_v6mc_sgv_t_init, soc_sbx_g3p1_v6mc_sgv_t*,  soc_sbx_g3p1_v6mc_sgv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP11(int, int, 0, 0, soc_sbx_g3p1_v6mc_sgv_set,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, isa0, 0, 0,
                        int, int, isa1, 0, 0,
                        int, int, isa2, 0, 0,
                        int, int, isa3, 0, 0,
                        int, int, iga0, 0, 0,
                        int, int, iga1, 0, 0,
                        int, int, iga2, 0, 0,
                        int, int, iga3, 0, 0,
                        soc_sbx_g3p1_v6mc_sgv_t*, soc_sbx_g3p1_v6mc_sgv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP11(int, int, 0, 0, soc_sbx_g3p1_v6mc_sgv_add,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, isa0, 0, 0,
                        int, int, isa1, 0, 0,
                        int, int, isa2, 0, 0,
                        int, int, isa3, 0, 0,
                        int, int, iga0, 0, 0,
                        int, int, iga1, 0, 0,
                        int, int, iga2, 0, 0,
                        int, int, iga3, 0, 0,
                        soc_sbx_g3p1_v6mc_sgv_t*, soc_sbx_g3p1_v6mc_sgv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP11(int, int, 0, 0, soc_sbx_g3p1_v6mc_sgv_get,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, isa0, 0, 0,
                        int, int, isa1, 0, 0,
                        int, int, isa2, 0, 0,
                        int, int, isa3, 0, 0,
                        int, int, iga0, 0, 0,
                        int, int, iga1, 0, 0,
                        int, int, iga2, 0, 0,
                        int, int, iga3, 0, 0,
                        soc_sbx_g3p1_v6mc_sgv_t*, soc_sbx_g3p1_v6mc_sgv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP11(int, int, 0, 0, soc_sbx_g3p1_v6mc_sgv_update,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, isa0, 0, 0,
                        int, int, isa1, 0, 0,
                        int, int, isa2, 0, 0,
                        int, int, isa3, 0, 0,
                        int, int, iga0, 0, 0,
                        int, int, iga1, 0, 0,
                        int, int, iga2, 0, 0,
                        int, int, iga3, 0, 0,
                        soc_sbx_g3p1_v6mc_sgv_t*, soc_sbx_g3p1_v6mc_sgv_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP10(int, int, 0, 0, soc_sbx_g3p1_v6mc_sgv_delete,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, isa0, 0, 0,
                        int, int, isa1, 0, 0,
                        int, int, isa2, 0, 0,
                        int, int, isa3, 0, 0,
                        int, int, iga0, 0, 0,
                        int, int, iga1, 0, 0,
                        int, int, iga2, 0, 0,
                        int, int, iga3, 0, 0);
CINT_FWRAPPER_CREATE_RP10(int, int, 0, 0, soc_sbx_g3p1_v6mc_sgv_remove,
                        int, int, unit, 0, 0, 
                        int, int, ivsi, 0, 0,
                        int, int, isa0, 0, 0,
                        int, int, isa1, 0, 0,
                        int, int, isa2, 0, 0,
                        int, int, isa3, 0, 0,
                        int, int, iga0, 0, 0,
                        int, int, iga1, 0, 0,
                        int, int, iga2, 0, 0,
                        int, int, iga3, 0, 0);
                                                                                               
/*
 * Struct soc_sbx_g3p1_v6mc_sgv_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_v6mc_sgv_t[] = 
{





    {
      "uint32",
      "rpfunion",
      0,
      0
    },
    {
      "uint32",
      "ftidx",
      0,
      0
    },
    {
      "uint32",
      "hit",
      0,
      0
    },
    {
      "uint32",
      "rsvd",
      0,
      0
    },
    {
      "uint32",
      "proccopy",
      0,
      0
    },
  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_v6mc_sgv_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_v6mc_sgv_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_v6mc_sgv_t* s = (soc_sbx_g3p1_v6mc_sgv_t*) p;

        switch (mnum) {
                case 0: rv = &(s->rpfunion); break;
                case 1: rv = &(s->ftidx); break;
                case 2: rv = &(s->hit); break;
                case 3: rv = &(s->rsvd); break;
                case 4: rv = &(s->proccopy); break;
          default: rv = NULL; break;
        }

    return rv;
}
 

/*
 * Hash table entry accessor implementations for oamrx
 */

CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_oamrx_t_init, soc_sbx_g3p1_oamrx_t*,  soc_sbx_g3p1_oamrx_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0, soc_sbx_g3p1_oamrx_set,
                        int, int, unit, 0, 0, 
                        int, int, iivid, 0, 0,
                        int, int, iovid, 0, 0,
                        int, int, idir, 0, 0,
                        int, int, iport, 0, 0,
                        int, int, ivid_mode, 0, 0,
                        soc_sbx_g3p1_oamrx_t*, soc_sbx_g3p1_oamrx_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0, soc_sbx_g3p1_oamrx_add,
                        int, int, unit, 0, 0, 
                        int, int, iivid, 0, 0,
                        int, int, iovid, 0, 0,
                        int, int, idir, 0, 0,
                        int, int, iport, 0, 0,
                        int, int, ivid_mode, 0, 0,
                        soc_sbx_g3p1_oamrx_t*, soc_sbx_g3p1_oamrx_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0, soc_sbx_g3p1_oamrx_get,
                        int, int, unit, 0, 0, 
                        int, int, iivid, 0, 0,
                        int, int, iovid, 0, 0,
                        int, int, idir, 0, 0,
                        int, int, iport, 0, 0,
                        int, int, ivid_mode, 0, 0,
                        soc_sbx_g3p1_oamrx_t*, soc_sbx_g3p1_oamrx_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0, soc_sbx_g3p1_oamrx_update,
                        int, int, unit, 0, 0, 
                        int, int, iivid, 0, 0,
                        int, int, iovid, 0, 0,
                        int, int, idir, 0, 0,
                        int, int, iport, 0, 0,
                        int, int, ivid_mode, 0, 0,
                        soc_sbx_g3p1_oamrx_t*, soc_sbx_g3p1_oamrx_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0, soc_sbx_g3p1_oamrx_delete,
                        int, int, unit, 0, 0, 
                        int, int, iivid, 0, 0,
                        int, int, iovid, 0, 0,
                        int, int, idir, 0, 0,
                        int, int, iport, 0, 0,
                        int, int, ivid_mode, 0, 0);
CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0, soc_sbx_g3p1_oamrx_remove,
                        int, int, unit, 0, 0, 
                        int, int, iivid, 0, 0,
                        int, int, iovid, 0, 0,
                        int, int, idir, 0, 0,
                        int, int, iport, 0, 0,
                        int, int, ivid_mode, 0, 0);
                                                                                               
/*
 * Struct soc_sbx_g3p1_oamrx_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_oamrx_t[] = 
{



    {
      "uint32",
      "hit",
      0,
      0
    },
    {
      "uint32",
      "svc_hdl",
      0,
      0
    },


    {
      "uint32",
      "mdlvl_7_f",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_7_d",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_7_p",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_7_m",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_6_f",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_6_d",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_6_p",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_6_m",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_5_f",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_5_d",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_5_p",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_5_m",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_4_f",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_4_d",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_4_p",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_4_m",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_3_f",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_3_d",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_3_p",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_3_m",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_2_f",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_2_d",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_2_p",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_2_m",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_1_f",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_1_d",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_1_p",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_1_m",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_0_f",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_0_d",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_0_p",
      0,
      0
    },
    {
      "uint32",
      "mdlvl_0_m",
      0,
      0
    },
  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_oamrx_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_oamrx_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_oamrx_t* s = (soc_sbx_g3p1_oamrx_t*) p;

        switch (mnum) {
                case 0: rv = &(s->hit); break;
                case 1: rv = &(s->svc_hdl); break;
                case 2: rv = &(s->mdlvl_7_f); break;
                case 3: rv = &(s->mdlvl_7_d); break;
                case 4: rv = &(s->mdlvl_7_p); break;
                case 5: rv = &(s->mdlvl_7_m); break;
                case 6: rv = &(s->mdlvl_6_f); break;
                case 7: rv = &(s->mdlvl_6_d); break;
                case 8: rv = &(s->mdlvl_6_p); break;
                case 9: rv = &(s->mdlvl_6_m); break;
                case 10: rv = &(s->mdlvl_5_f); break;
                case 11: rv = &(s->mdlvl_5_d); break;
                case 12: rv = &(s->mdlvl_5_p); break;
                case 13: rv = &(s->mdlvl_5_m); break;
                case 14: rv = &(s->mdlvl_4_f); break;
                case 15: rv = &(s->mdlvl_4_d); break;
                case 16: rv = &(s->mdlvl_4_p); break;
                case 17: rv = &(s->mdlvl_4_m); break;
                case 18: rv = &(s->mdlvl_3_f); break;
                case 19: rv = &(s->mdlvl_3_d); break;
                case 20: rv = &(s->mdlvl_3_p); break;
                case 21: rv = &(s->mdlvl_3_m); break;
                case 22: rv = &(s->mdlvl_2_f); break;
                case 23: rv = &(s->mdlvl_2_d); break;
                case 24: rv = &(s->mdlvl_2_p); break;
                case 25: rv = &(s->mdlvl_2_m); break;
                case 26: rv = &(s->mdlvl_1_f); break;
                case 27: rv = &(s->mdlvl_1_d); break;
                case 28: rv = &(s->mdlvl_1_p); break;
                case 29: rv = &(s->mdlvl_1_m); break;
                case 30: rv = &(s->mdlvl_0_f); break;
                case 31: rv = &(s->mdlvl_0_d); break;
                case 32: rv = &(s->mdlvl_0_p); break;
                case 33: rv = &(s->mdlvl_0_m); break;
          default: rv = NULL; break;
        }

    return rv;
}
 

/*
 * Hash table entry accessor implementations for maidmep
 */

CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_maidmep_t_init, soc_sbx_g3p1_maidmep_t*,  soc_sbx_g3p1_maidmep_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0, soc_sbx_g3p1_maidmep_set,
                        int, int, unit, 0, 0, 
                        int, int, isvc_hdl, 0, 0,
                        int, int, imepid, 0, 0,
                        int, int, imsg_type, 0, 0,
                        int, int, imdlvl, 0, 0,
                        soc_sbx_g3p1_maidmep_t*, soc_sbx_g3p1_maidmep_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0, soc_sbx_g3p1_maidmep_add,
                        int, int, unit, 0, 0, 
                        int, int, isvc_hdl, 0, 0,
                        int, int, imepid, 0, 0,
                        int, int, imsg_type, 0, 0,
                        int, int, imdlvl, 0, 0,
                        soc_sbx_g3p1_maidmep_t*, soc_sbx_g3p1_maidmep_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0, soc_sbx_g3p1_maidmep_get,
                        int, int, unit, 0, 0, 
                        int, int, isvc_hdl, 0, 0,
                        int, int, imepid, 0, 0,
                        int, int, imsg_type, 0, 0,
                        int, int, imdlvl, 0, 0,
                        soc_sbx_g3p1_maidmep_t*, soc_sbx_g3p1_maidmep_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0, soc_sbx_g3p1_maidmep_update,
                        int, int, unit, 0, 0, 
                        int, int, isvc_hdl, 0, 0,
                        int, int, imepid, 0, 0,
                        int, int, imsg_type, 0, 0,
                        int, int, imdlvl, 0, 0,
                        soc_sbx_g3p1_maidmep_t*, soc_sbx_g3p1_maidmep_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_maidmep_delete,
                        int, int, unit, 0, 0, 
                        int, int, isvc_hdl, 0, 0,
                        int, int, imepid, 0, 0,
                        int, int, imsg_type, 0, 0,
                        int, int, imdlvl, 0, 0);
CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0, soc_sbx_g3p1_maidmep_remove,
                        int, int, unit, 0, 0, 
                        int, int, isvc_hdl, 0, 0,
                        int, int, imepid, 0, 0,
                        int, int, imsg_type, 0, 0,
                        int, int, imdlvl, 0, 0);
                                                                                               
/*
 * Struct soc_sbx_g3p1_maidmep_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_maidmep_t[] = 
{



    {
      "uint32",
      "hit",
      0,
      0
    },
    {
      "uint32",
      "peer_idx",
      0,
      0
    },



  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_maidmep_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_maidmep_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_maidmep_t* s = (soc_sbx_g3p1_maidmep_t*) p;

        switch (mnum) {
                case 0: rv = &(s->hit); break;
                case 1: rv = &(s->peer_idx); break;
          default: rv = NULL; break;
        }

    return rv;
}
 

/*
 * Hash table entry accessor implementations for emlfilter
 */

CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_emlfilter_t_init, soc_sbx_g3p1_emlfilter_t*,  soc_sbx_g3p1_emlfilter_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_emlfilter_set,
                        int, int, unit, 0, 0, 
                        int, int, iemlindex, 0, 0,
                        soc_sbx_g3p1_emlfilter_t*, soc_sbx_g3p1_emlfilter_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_emlfilter_add,
                        int, int, unit, 0, 0, 
                        int, int, iemlindex, 0, 0,
                        soc_sbx_g3p1_emlfilter_t*, soc_sbx_g3p1_emlfilter_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_emlfilter_get,
                        int, int, unit, 0, 0, 
                        int, int, iemlindex, 0, 0,
                        soc_sbx_g3p1_emlfilter_t*, soc_sbx_g3p1_emlfilter_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_emlfilter_update,
                        int, int, unit, 0, 0, 
                        int, int, iemlindex, 0, 0,
                        soc_sbx_g3p1_emlfilter_t*, soc_sbx_g3p1_emlfilter_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_g3p1_emlfilter_delete,
                        int, int, unit, 0, 0, 
                        int, int, iemlindex, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_g3p1_emlfilter_remove,
                        int, int, unit, 0, 0, 
                        int, int, iemlindex, 0, 0);
                                                                                               
/*
 * Struct soc_sbx_g3p1_emlfilter_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_emlfilter_t[] = 
{



    {
      "uint32",
      "reserved_0",
      0,
      0
    },
    {
      "uint32",
      "reserved_1",
      0,
      0
    },
    {
      "uint32",
      "reserved_2",
      0,
      0
    },
    {
      "uint32",
      "reserved_3",
      0,
      0
    },
  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_emlfilter_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_emlfilter_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_emlfilter_t* s = (soc_sbx_g3p1_emlfilter_t*) p;

        switch (mnum) {
                case 0: rv = &(s->reserved_0); break;
                case 1: rv = &(s->reserved_1); break;
                case 2: rv = &(s->reserved_2); break;
                case 3: rv = &(s->reserved_3); break;
          default: rv = NULL; break;
        }

    return rv;
}
 

/*
 * DM table entry accessor implementations for ete
 */
CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_ete_t_init, soc_sbx_g3p1_ete_t*,  soc_sbx_g3p1_ete_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_ete_table_size_get,
                        int, int, unit, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_g3p1_ete_table_size_set,
                        int, int, unit, 0, 0,
                        int, int, size, 0, 0);     
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_ete_set,
                        int, int, unit, 0, 0, 
                        int, int, ietei, 0, 0,
                        soc_sbx_g3p1_ete_t*, soc_sbx_g3p1_ete_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_ete_get,
                        int, int, unit, 0, 0, 
                        int, int, ietei, 0, 0,
                        soc_sbx_g3p1_ete_t*, soc_sbx_g3p1_ete_t, e, 1, 0);

                                                                                               
/*
 * Struct soc_sbx_g3p1_ete_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_ete_t[] = 
{
    {
      "uint32",
      "dmacset",
      0,
      0
    },
    {
      "uint32",
      "dmacsetlsb",
      0,
      0
    },
    {
      "uint32",
      "dscpremark",
      0,
      0
    },
    {
      "uint32",
      "remark",
      0,
      0
    },
    {
      "uint32",
      "mplsttldec",
      0,
      0
    },
    {
      "uint32",
      "encaplen",
      0,
      0
    },
    {
      "uint32",
      "encapmac",
      0,
      0
    },
    {
      "uint32",
      "nostrip",
      0,
      0
    },
    {
      "uint32",
      "noclass",
      0,
      0
    },
    {
      "uint32",
      "etepid",
      0,
      0
    },
    {
      "uint32",
      "tunnelenter",
      0,
      0
    },
    {
      "uint32",
      "exp0remark",
      0,
      0
    },
    {
      "uint32",
      "exp1remark",
      0,
      0
    },
    {
      "uint32",
      "exp2remark",
      0,
      0
    },
    {
      "uint32",
      "ttl0dec",
      0,
      0
    },
    {
      "uint32",
      "ttl1dec",
      0,
      0
    },
    {
      "uint32",
      "ttl2dec",
      0,
      0
    },
    {
      "uint32",
      "smacset",
      0,
      0
    },
    {
      "uint32",
      "nosplitcheck",
      0,
      0
    },
    {
      "uint32",
      "ttlcheck",
      0,
      0
    },
    {
      "uint32",
      "ipttldec",
      0,
      0
    },
    {
      "uint32",
      "add_pwcw",
      0,
      0
    },
    {
      "uint32",
      "comp_encaplen",
      0,
      0
    },
    {
      "uint32",
      "etype2",
      0,
      0
    },
    {
      "uint32",
      "ttl2",
      0,
      0
    },
    {
      "uint32",
      "s2",
      0,
      0
    },
    {
      "uint32",
      "exp2",
      0,
      0
    },
    {
      "uint32",
      "label2",
      0,
      0
    },
    {
      "uint32",
      "encap_vid",
      0,
      0
    },
    {
      "uint32",
      "pricfi",
      0,
      0
    },
    {
      "uint32",
      "etype",
      0,
      0
    },
    {
      "uint32",
      "tpid",
      0,
      0
    },
    {
      "uint32",
      "pid",
      0,
      0
    },
    {
      "uint32",
      "dmac5",
      0,
      0
    },
    {
      "uint32",
      "dmac4",
      0,
      0
    },
    {
      "uint32",
      "dmac3",
      0,
      0
    },
    {
      "uint32",
      "dmac2",
      0,
      0
    },
    {
      "uint32",
      "dmac1",
      0,
      0
    },
    {
      "uint32",
      "dmac0",
      0,
      0
    },
    {
      "uint32",
      "vlan",
      0,
      0
    },
    {
      "uint32",
      "defpricfi",
      0,
      0
    },
    {
      "uint32",
      "usetag",
      0,
      0
    },
    {
      "uint32",
      "l2_reserved",
      0,
      0
    },
    {
      "uint32",
      "dropuntagged",
      0,
      0
    },
    {
      "uint32",
      "droptagged",
      0,
      0
    },
    {
      "uint32",
      "smacindex",
      0,
      0
    },
    {
      "uint32",
      "stpcheck",
      0,
      0
    },
    {
      "uint32",
      "vid",
      0,
      0
    },




    {
      "uint32",
      "ttl0",
      0,
      0
    },
    {
      "uint32",
      "s0",
      0,
      0
    },
    {
      "uint32",
      "exp0",
      0,
      0
    },
    {
      "uint32",
      "label0",
      0,
      0
    },
    {
      "uint32",
      "ttl1",
      0,
      0
    },
    {
      "uint32",
      "s1",
      0,
      0
    },
    {
      "uint32",
      "exp1",
      0,
      0
    },
    {
      "uint32",
      "label1",
      0,
      0
    },
    {
      "uint32",
      "smac5",
      0,
      0
    },
    {
      "uint32",
      "smac4",
      0,
      0
    },
    {
      "uint32",
      "smac3",
      0,
      0
    },
    {
      "uint32",
      "smac2",
      0,
      0
    },
    {
      "uint32",
      "smac1",
      0,
      0
    },
    {
      "uint32",
      "smac0",
      0,
      0
    },
    {
      "uint32",
      "mtu",
      0,
      0
    },
    {
      "uint32",
      "usevid",
      0,
      0
    },







  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_ete_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_ete_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_ete_t* s = (soc_sbx_g3p1_ete_t*) p;

        switch (mnum) {
                case 0: rv = &(s->dmacset); break;
                case 1: rv = &(s->dmacsetlsb); break;
                case 2: rv = &(s->dscpremark); break;
                case 3: rv = &(s->remark); break;
                case 4: rv = &(s->mplsttldec); break;
                case 5: rv = &(s->encaplen); break;
                case 6: rv = &(s->encapmac); break;
                case 7: rv = &(s->nostrip); break;
                case 8: rv = &(s->noclass); break;
                case 9: rv = &(s->etepid); break;
                case 10: rv = &(s->tunnelenter); break;
                case 11: rv = &(s->exp0remark); break;
                case 12: rv = &(s->exp1remark); break;
                case 13: rv = &(s->exp2remark); break;
                case 14: rv = &(s->ttl0dec); break;
                case 15: rv = &(s->ttl1dec); break;
                case 16: rv = &(s->ttl2dec); break;
                case 17: rv = &(s->smacset); break;
                case 18: rv = &(s->nosplitcheck); break;
                case 19: rv = &(s->ttlcheck); break;
                case 20: rv = &(s->ipttldec); break;
                case 21: rv = &(s->add_pwcw); break;
                case 22: rv = &(s->comp_encaplen); break;
                case 23: rv = &(s->etype2); break;
                case 24: rv = &(s->ttl2); break;
                case 25: rv = &(s->s2); break;
                case 26: rv = &(s->exp2); break;
                case 27: rv = &(s->label2); break;
                case 28: rv = &(s->encap_vid); break;
                case 29: rv = &(s->pricfi); break;
                case 30: rv = &(s->etype); break;
                case 31: rv = &(s->tpid); break;
                case 32: rv = &(s->pid); break;
                case 33: rv = &(s->dmac5); break;
                case 34: rv = &(s->dmac4); break;
                case 35: rv = &(s->dmac3); break;
                case 36: rv = &(s->dmac2); break;
                case 37: rv = &(s->dmac1); break;
                case 38: rv = &(s->dmac0); break;
                case 39: rv = &(s->vlan); break;
                case 40: rv = &(s->defpricfi); break;
                case 41: rv = &(s->usetag); break;
                case 42: rv = &(s->l2_reserved); break;
                case 43: rv = &(s->dropuntagged); break;
                case 44: rv = &(s->droptagged); break;
                case 45: rv = &(s->smacindex); break;
                case 46: rv = &(s->stpcheck); break;
                case 47: rv = &(s->vid); break;
                case 48: rv = &(s->ttl0); break;
                case 49: rv = &(s->s0); break;
                case 50: rv = &(s->exp0); break;
                case 51: rv = &(s->label0); break;
                case 52: rv = &(s->ttl1); break;
                case 53: rv = &(s->s1); break;
                case 54: rv = &(s->exp1); break;
                case 55: rv = &(s->label1); break;
                case 56: rv = &(s->smac5); break;
                case 57: rv = &(s->smac4); break;
                case 58: rv = &(s->smac3); break;
                case 59: rv = &(s->smac2); break;
                case 60: rv = &(s->smac1); break;
                case 61: rv = &(s->smac0); break;
                case 62: rv = &(s->mtu); break;
                case 63: rv = &(s->usevid); break;
          default: rv = NULL; break;
        }

    return rv;
}


/*
 * DM table entry accessor implementations for oam_ep
 */
CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_oam_ep_t_init, soc_sbx_g3p1_oam_ep_t*,  soc_sbx_g3p1_oam_ep_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_oam_ep_table_size_get,
                        int, int, unit, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_g3p1_oam_ep_table_size_set,
                        int, int, unit, 0, 0,
                        int, int, size, 0, 0);     
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_oam_ep_set,
                        int, int, unit, 0, 0, 
                        int, int, ioam_epi, 0, 0,
                        soc_sbx_g3p1_oam_ep_t*, soc_sbx_g3p1_oam_ep_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_oam_ep_get,
                        int, int, unit, 0, 0, 
                        int, int, ioam_epi, 0, 0,
                        soc_sbx_g3p1_oam_ep_t*, soc_sbx_g3p1_oam_ep_t, e, 1, 0);

                                                                                               
/*
 * Struct soc_sbx_g3p1_oam_ep_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_oam_ep_t[] = 
{
    {
      "uint32",
      "smac1",
      0,
      0
    },
    {
      "uint32",
      "smac0",
      0,
      0
    },
    {
      "uint32",
      "dmac5",
      0,
      0
    },
    {
      "uint32",
      "dmac4",
      0,
      0
    },
    {
      "uint32",
      "dmac3",
      0,
      0
    },
    {
      "uint32",
      "dmac2",
      0,
      0
    },
    {
      "uint32",
      "dmac1",
      0,
      0
    },
    {
      "uint32",
      "dmac0",
      0,
      0
    },
    {
      "uint32",
      "smac5",
      0,
      0
    },
    {
      "uint32",
      "smac4",
      0,
      0
    },
    {
      "uint32",
      "smac3",
      0,
      0
    },
    {
      "uint32",
      "smac2",
      0,
      0
    },

    {
      "uint32",
      "vid",
      0,
      0
    },
    {
      "uint32",
      "num_vlan_tags",
      0,
      0
    },
    {
      "uint32",
      "dir",
      0,
      0
    },
    {
      "uint32",
      "reqMinEchoRxInterval",
      0,
      0
    },

    {
      "uint32",
      "localDiscr",
      0,
      0
    },









    {
      "uint32",
      "ftidx",
      0,
      0
    },
    {
      "uint32",
      "dport",
      0,
      0
    },
    {
      "uint32",
      "dqueue",
      0,
      0
    },
    {
      "uint32",
      "tlv_offset",
      0,
      0
    },
    {
      "uint32",
      "period",
      0,
      0
    },
    {
      "uint32",
      "flags_rsvd",
      0,
      0
    },
    {
      "uint32",
      "rdi",
      0,
      0
    },
    {
      "uint32",
      "opcode",
      0,
      0
    },
    {
      "uint32",
      "version",
      0,
      0
    },
    {
      "uint32",
      "mdlvl",
      0,
      0
    },

    {
      "uint32",
      "mepid",
      0,
      0
    },
    {
      "uint32",
      "func",
      0,
      0
    },
    {
      "uint32",
      "type",
      0,
      0
    },
    {
      "uint32",
      "unused",
      0,
      0
    },



  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_oam_ep_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_oam_ep_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_oam_ep_t* s = (soc_sbx_g3p1_oam_ep_t*) p;

        switch (mnum) {
                case 0: rv = &(s->smac1); break;
                case 1: rv = &(s->smac0); break;
                case 2: rv = &(s->dmac5); break;
                case 3: rv = &(s->dmac4); break;
                case 4: rv = &(s->dmac3); break;
                case 5: rv = &(s->dmac2); break;
                case 6: rv = &(s->dmac1); break;
                case 7: rv = &(s->dmac0); break;
                case 8: rv = &(s->smac5); break;
                case 9: rv = &(s->smac4); break;
                case 10: rv = &(s->smac3); break;
                case 11: rv = &(s->smac2); break;
                case 12: rv = &(s->vid); break;
                case 13: rv = &(s->num_vlan_tags); break;
                case 14: rv = &(s->dir); break;
                case 15: rv = &(s->reqMinEchoRxInterval); break;
                case 16: rv = &(s->localDiscr); break;
                case 17: rv = &(s->ftidx); break;
                case 18: rv = &(s->dport); break;
                case 19: rv = &(s->dqueue); break;
                case 20: rv = &(s->tlv_offset); break;
                case 21: rv = &(s->period); break;
                case 22: rv = &(s->flags_rsvd); break;
                case 23: rv = &(s->rdi); break;
                case 24: rv = &(s->opcode); break;
                case 25: rv = &(s->version); break;
                case 26: rv = &(s->mdlvl); break;
                case 27: rv = &(s->mepid); break;
                case 28: rv = &(s->func); break;
                case 29: rv = &(s->type); break;
                case 30: rv = &(s->unused); break;
          default: rv = NULL; break;
        }

    return rv;
}


/*
 * DM table entry accessor implementations for oam_local
 */
CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_oam_local_t_init, soc_sbx_g3p1_oam_local_t*,  soc_sbx_g3p1_oam_local_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_oam_local_table_size_get,
                        int, int, unit, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_g3p1_oam_local_table_size_set,
                        int, int, unit, 0, 0,
                        int, int, size, 0, 0);     
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_oam_local_set,
                        int, int, unit, 0, 0, 
                        int, int, ioam_locali, 0, 0,
                        soc_sbx_g3p1_oam_local_t*, soc_sbx_g3p1_oam_local_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_oam_local_get,
                        int, int, unit, 0, 0, 
                        int, int, ioam_locali, 0, 0,
                        soc_sbx_g3p1_oam_local_t*, soc_sbx_g3p1_oam_local_t, e, 1, 0);

                                                                                               
/*
 * Struct soc_sbx_g3p1_oam_local_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_oam_local_t[] = 
{
    {
      "uint32",
      "maid_w1",
      0,
      0
    },
    {
      "uint32",
      "maid_w0",
      0,
      0
    },
    {
      "uint32",
      "maid_w3",
      0,
      0
    },
    {
      "uint32",
      "maid_w2",
      0,
      0
    },
    {
      "uint32",
      "maid_w5",
      0,
      0
    },
    {
      "uint32",
      "maid_w4",
      0,
      0
    },
    {
      "uint32",
      "unused_w6",
      0,
      0
    },




    {
      "uint32",
      "maid_w7",
      0,
      0
    },
    {
      "uint32",
      "maid_w6",
      0,
      0
    },
    {
      "uint32",
      "maid_w9",
      0,
      0
    },
    {
      "uint32",
      "maid_w8",
      0,
      0
    },
    {
      "uint32",
      "maid_w11",
      0,
      0
    },
    {
      "uint32",
      "maid_w10",
      0,
      0
    },





  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_oam_local_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_oam_local_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_oam_local_t* s = (soc_sbx_g3p1_oam_local_t*) p;

        switch (mnum) {
                case 0: rv = &(s->maid_w1); break;
                case 1: rv = &(s->maid_w0); break;
                case 2: rv = &(s->maid_w3); break;
                case 3: rv = &(s->maid_w2); break;
                case 4: rv = &(s->maid_w5); break;
                case 5: rv = &(s->maid_w4); break;
                case 6: rv = &(s->unused_w6); break;
                case 7: rv = &(s->maid_w7); break;
                case 8: rv = &(s->maid_w6); break;
                case 9: rv = &(s->maid_w9); break;
                case 10: rv = &(s->maid_w8); break;
                case 11: rv = &(s->maid_w11); break;
                case 12: rv = &(s->maid_w10); break;
          default: rv = NULL; break;
        }

    return rv;
}


/*
 * DM table entry accessor implementations for oam_peer
 */
CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_oam_peer_t_init, soc_sbx_g3p1_oam_peer_t*,  soc_sbx_g3p1_oam_peer_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_oam_peer_table_size_get,
                        int, int, unit, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_g3p1_oam_peer_table_size_set,
                        int, int, unit, 0, 0,
                        int, int, size, 0, 0);     
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_oam_peer_set,
                        int, int, unit, 0, 0, 
                        int, int, ioam_peer_idx, 0, 0,
                        soc_sbx_g3p1_oam_peer_t*, soc_sbx_g3p1_oam_peer_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_oam_peer_get,
                        int, int, unit, 0, 0, 
                        int, int, ioam_peer_idx, 0, 0,
                        soc_sbx_g3p1_oam_peer_t*, soc_sbx_g3p1_oam_peer_t, e, 1, 0);

                                                                                               
/*
 * Struct soc_sbx_g3p1_oam_peer_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_oam_peer_t[] = 
{
    {
      "uint32",
      "maid_crc",
      0,
      0
    },
    {
      "uint32",
      "pol_id_wdg",
      0,
      0
    },
    {
      "uint32",
      "fwd_to_host",
      0,
      0
    },
    {
      "uint32",
      "period",
      0,
      0
    },
    {
      "uint32",
      "pad1",
      0,
      0
    },
    {
      "uint32",
      "w2",
      0,
      0
    },
    {
      "uint32",
      "w3",
      0,
      0
    },
    {
      "uint32",
      "w4",
      0,
      0
    },
    {
      "uint32",
      "w5",
      0,
      0
    },
    {
      "uint32",
      "w6",
      0,
      0
    },
    {
      "uint32",
      "w7",
      0,
      0
    },
    {
      "uint32",
      "e_w7",
      0,
      0
    },
    {
      "uint32",
      "code_w7",
      0,
      0
    },
    {
      "uint32",
      "reserved_w7",
      0,
      0
    },
    {
      "uint32",
      "w8",
      0,
      0
    },
    {
      "uint32",
      "w9",
      0,
      0
    },
    {
      "uint32",
      "w10",
      0,
      0
    },
    {
      "uint32",
      "w11",
      0,
      0
    },
    {
      "uint32",
      "w12",
      0,
      0
    },
    {
      "uint32",
      "w13",
      0,
      0
    },
    {
      "uint32",
      "w14",
      0,
      0
    },
    {
      "uint32",
      "w15",
      0,
      0
    },
    {
      "uint32",
      "e_w15",
      0,
      0
    },
    {
      "uint32",
      "code_w15",
      0,
      0
    },
    {
      "uint32",
      "reserved_w15",
      0,
      0
    },
  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_oam_peer_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_oam_peer_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_oam_peer_t* s = (soc_sbx_g3p1_oam_peer_t*) p;

        switch (mnum) {
                case 0: rv = &(s->maid_crc); break;
                case 1: rv = &(s->pol_id_wdg); break;
                case 2: rv = &(s->fwd_to_host); break;
                case 3: rv = &(s->period); break;
                case 4: rv = &(s->pad1); break;
                case 5: rv = &(s->w2); break;
                case 6: rv = &(s->w3); break;
                case 7: rv = &(s->w4); break;
                case 8: rv = &(s->w5); break;
                case 9: rv = &(s->w6); break;
                case 10: rv = &(s->w7); break;
                case 11: rv = &(s->e_w7); break;
                case 12: rv = &(s->code_w7); break;
                case 13: rv = &(s->reserved_w7); break;
                case 14: rv = &(s->w8); break;
                case 15: rv = &(s->w9); break;
                case 16: rv = &(s->w10); break;
                case 17: rv = &(s->w11); break;
                case 18: rv = &(s->w12); break;
                case 19: rv = &(s->w13); break;
                case 20: rv = &(s->w14); break;
                case 21: rv = &(s->w15); break;
                case 22: rv = &(s->e_w15); break;
                case 23: rv = &(s->code_w15); break;
                case 24: rv = &(s->reserved_w15); break;
          default: rv = NULL; break;
        }

    return rv;
}


/*
 * Hash table entry accessor implementations for labels3
 */

CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_labels3_t_init, soc_sbx_g3p1_labels3_t*,  soc_sbx_g3p1_labels3_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0, soc_sbx_g3p1_labels3_set,
                        int, int, unit, 0, 0, 
                        int, int, ilabel3, 0, 0,
                        int, int, ilabel2, 0, 0,
                        int, int, ilabel1, 0, 0,
                        int, int, iresv1, 0, 0,
                        int, int, iport, 0, 0,
                        soc_sbx_g3p1_labels3_t*, soc_sbx_g3p1_labels3_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0, soc_sbx_g3p1_labels3_add,
                        int, int, unit, 0, 0, 
                        int, int, ilabel3, 0, 0,
                        int, int, ilabel2, 0, 0,
                        int, int, ilabel1, 0, 0,
                        int, int, iresv1, 0, 0,
                        int, int, iport, 0, 0,
                        soc_sbx_g3p1_labels3_t*, soc_sbx_g3p1_labels3_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0, soc_sbx_g3p1_labels3_get,
                        int, int, unit, 0, 0, 
                        int, int, ilabel3, 0, 0,
                        int, int, ilabel2, 0, 0,
                        int, int, ilabel1, 0, 0,
                        int, int, iresv1, 0, 0,
                        int, int, iport, 0, 0,
                        soc_sbx_g3p1_labels3_t*, soc_sbx_g3p1_labels3_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0, soc_sbx_g3p1_labels3_update,
                        int, int, unit, 0, 0, 
                        int, int, ilabel3, 0, 0,
                        int, int, ilabel2, 0, 0,
                        int, int, ilabel1, 0, 0,
                        int, int, iresv1, 0, 0,
                        int, int, iport, 0, 0,
                        soc_sbx_g3p1_labels3_t*, soc_sbx_g3p1_labels3_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0, soc_sbx_g3p1_labels3_delete,
                        int, int, unit, 0, 0, 
                        int, int, ilabel3, 0, 0,
                        int, int, ilabel2, 0, 0,
                        int, int, ilabel1, 0, 0,
                        int, int, iresv1, 0, 0,
                        int, int, iport, 0, 0);
CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0, soc_sbx_g3p1_labels3_remove,
                        int, int, unit, 0, 0, 
                        int, int, ilabel3, 0, 0,
                        int, int, ilabel2, 0, 0,
                        int, int, ilabel1, 0, 0,
                        int, int, iresv1, 0, 0,
                        int, int, iport, 0, 0);
                                                                                               
/*
 * Struct soc_sbx_g3p1_labels3_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_labels3_t[] = 
{





    {
      "uint32",
      "pad",
      0,
      0
    },
    {
      "uint32",
      "opcode",
      0,
      0
    },
    {
      "uint32",
      "ftidx",
      0,
      0
    },
    {
      "uint32",
      "vlan",
      0,
      0
    },
    {
      "uint32",
      "hit",
      0,
      0
    },
    {
      "uint32",
      "lock",
      0,
      0
    },
    {
      "uint32",
      "keep_sdtag",
      0,
      0
    },
    {
      "uint32",
      "pipe",
      0,
      0
    },
    {
      "uint32",
      "elsp",
      0,
      0
    },
    {
      "uint32",
      "stpstate",
      0,
      0
    },


    {
      "uint32",
      "vpws",
      0,
      0
    },
    {
      "uint32",
      "loop",
      0,
      0
    },
    {
      "uint32",
      "cos",
      0,
      0
    },
    {
      "uint32",
      "lpi",
      0,
      0
    },
  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_labels3_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_labels3_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_labels3_t* s = (soc_sbx_g3p1_labels3_t*) p;

        switch (mnum) {
                case 0: rv = &(s->pad); break;
                case 1: rv = &(s->opcode); break;
                case 2: rv = &(s->ftidx); break;
                case 3: rv = &(s->vlan); break;
                case 4: rv = &(s->hit); break;
                case 5: rv = &(s->lock); break;
                case 6: rv = &(s->keep_sdtag); break;
                case 7: rv = &(s->pipe); break;
                case 8: rv = &(s->elsp); break;
                case 9: rv = &(s->stpstate); break;
                case 10: rv = &(s->vpws); break;
                case 11: rv = &(s->loop); break;
                case 12: rv = &(s->cos); break;
                case 13: rv = &(s->lpi); break;
          default: rv = NULL; break;
        }

    return rv;
}
 

/*
 * Hash table entry accessor implementations for bfd_ld2e
 */

CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_bfd_ld2e_t_init, soc_sbx_g3p1_bfd_ld2e_t*,  soc_sbx_g3p1_bfd_ld2e_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_bfd_ld2e_set,
                        int, int, unit, 0, 0, 
                        int, int, ilocalDiscri, 0, 0,
                        soc_sbx_g3p1_bfd_ld2e_t*, soc_sbx_g3p1_bfd_ld2e_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_bfd_ld2e_add,
                        int, int, unit, 0, 0, 
                        int, int, ilocalDiscri, 0, 0,
                        soc_sbx_g3p1_bfd_ld2e_t*, soc_sbx_g3p1_bfd_ld2e_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_bfd_ld2e_get,
                        int, int, unit, 0, 0, 
                        int, int, ilocalDiscri, 0, 0,
                        soc_sbx_g3p1_bfd_ld2e_t*, soc_sbx_g3p1_bfd_ld2e_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_g3p1_bfd_ld2e_update,
                        int, int, unit, 0, 0, 
                        int, int, ilocalDiscri, 0, 0,
                        soc_sbx_g3p1_bfd_ld2e_t*, soc_sbx_g3p1_bfd_ld2e_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_g3p1_bfd_ld2e_delete,
                        int, int, unit, 0, 0, 
                        int, int, ilocalDiscri, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_g3p1_bfd_ld2e_remove,
                        int, int, unit, 0, 0, 
                        int, int, ilocalDiscri, 0, 0);
                                                                                               
/*
 * Struct soc_sbx_g3p1_bfd_ld2e_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_bfd_ld2e_t[] = 
{




    {
      "uint32",
      "bubble_id",
      0,
      0
    },
    {
      "uint32",
      "hit",
      0,
      0
    },
    {
      "uint32",
      "c",
      0,
      0
    },
    {
      "uint32",
      "a",
      0,
      0
    },
    {
      "uint32",
      "d",
      0,
      0
    },
    {
      "uint32",
      "m",
      0,
      0
    },
    {
      "uint32",
      "detectMulti",
      0,
      0
    },
    {
      "uint32",
      "length",
      0,
      0
    },
    {
      "uint32",
      "desiredMinTxInterval",
      0,
      0
    },
    {
      "uint32",
      "reqMinRxInterval",
      0,
      0
    },
  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_bfd_ld2e_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_bfd_ld2e_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_bfd_ld2e_t* s = (soc_sbx_g3p1_bfd_ld2e_t*) p;

        switch (mnum) {
                case 0: rv = &(s->bubble_id); break;
                case 1: rv = &(s->hit); break;
                case 2: rv = &(s->c); break;
                case 3: rv = &(s->a); break;
                case 4: rv = &(s->d); break;
                case 5: rv = &(s->m); break;
                case 6: rv = &(s->detectMulti); break;
                case 7: rv = &(s->length); break;
                case 8: rv = &(s->desiredMinTxInterval); break;
                case 9: rv = &(s->reqMinRxInterval); break;
          default: rv = NULL; break;
        }

    return rv;
}
 

/*
 * DM table entry accessor implementations for sample_dm1
 */
CINT_FWRAPPER_CREATE_VP1(soc_sbx_g3p1_sample_dm1_t_init, soc_sbx_g3p1_sample_dm1_t*,  soc_sbx_g3p1_sample_dm1_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0, soc_sbx_g3p1_sample_dm1_table_size_get,
                        int, int, unit, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_g3p1_sample_dm1_table_size_set,
                        int, int, unit, 0, 0,
                        int, int, size, 0, 0);     
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_sample_dm1_set,
                        int, int, unit, 0, 0, 
                        int, int, iindex_1, 0, 0,
                        int, int, iindex_2, 0, 0,
                        soc_sbx_g3p1_sample_dm1_t*, soc_sbx_g3p1_sample_dm1_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0, soc_sbx_g3p1_sample_dm1_get,
                        int, int, unit, 0, 0, 
                        int, int, iindex_1, 0, 0,
                        int, int, iindex_2, 0, 0,
                        soc_sbx_g3p1_sample_dm1_t*, soc_sbx_g3p1_sample_dm1_t, e, 1, 0);

                                                                                               
/*
 * Struct soc_sbx_g3p1_sample_dm1_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_g3p1_sample_dm1_t[] = 
{
    {
      "uint32",
      "w0",
      0,
      0
    },
    {
      "uint32",
      "w1",
      0,
      0
    },
    {
      "uint32",
      "w2",
      0,
      0
    },
    {
      "uint32",
      "w3",
      0,
      0
    },
  { NULL }
};         

/*
 * Struct soc_sbx_g3p1_sample_dm1_t
 */
 static void*
__cint_maddr__soc_sbx_g3p1_sample_dm1_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_g3p1_sample_dm1_t* s = (soc_sbx_g3p1_sample_dm1_t*) p;

        switch (mnum) {
                case 0: rv = &(s->w0); break;
                case 1: rv = &(s->w1); break;
                case 2: rv = &(s->w2); break;
                case 3: rv = &(s->w3); break;
          default: rv = NULL; break;
        }

    return rv;
}

/*
 * Function table
 */
static cint_function_t __cint_g3p1_functions [] =
{  
     
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_mac_t_init),  /* Hash mac */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_mac_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_mac_add),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_mac_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_mac_update),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_mac_delete),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_mac_remove),
     
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_pvv2e_t_init),  /* Hash pvv2e */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_pvv2e_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_pvv2e_add),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_pvv2e_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_pvv2e_update),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_pvv2e_delete),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_pvv2e_remove),
     
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_labels_t_init),  /* Hash labels */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_labels_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_labels_add),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_labels_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_labels_update),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_labels_delete),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_labels_remove),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4da_t_init),  /* TAPS v4da */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4da_table_size_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4da_table_size_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4da_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4da_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4da_delete),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4da_remove),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4sa_t_init),  /* TAPS v4sa */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4sa_table_size_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4sa_table_size_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4sa_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4sa_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4sa_delete),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4sa_remove),
     
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4mc_sgv_t_init),  /* Hash v4mc_sgv */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4mc_sgv_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4mc_sgv_add),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4mc_sgv_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4mc_sgv_update),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4mc_sgv_delete),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4mc_sgv_remove),
     
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4mc_gv_t_init),  /* Hash v4mc_gv */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4mc_gv_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4mc_gv_add),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4mc_gv_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4mc_gv_update),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4mc_gv_delete),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v4mc_gv_remove),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6da_t_init),  /* TAPS v6da */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6da_table_size_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6da_table_size_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6da_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6da_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6da_delete),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6da_remove),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6sa_t_init),  /* TAPS v6sa */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6sa_table_size_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6sa_table_size_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6sa_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6sa_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6sa_delete),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6sa_remove),
     
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6mc_gv_t_init),  /* Hash v6mc_gv */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6mc_gv_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6mc_gv_add),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6mc_gv_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6mc_gv_update),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6mc_gv_delete),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6mc_gv_remove),
     
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6mc_sgv_t_init),  /* Hash v6mc_sgv */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6mc_sgv_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6mc_sgv_add),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6mc_sgv_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6mc_sgv_update),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6mc_sgv_delete),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_v6mc_sgv_remove),
     
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oamrx_t_init),  /* Hash oamrx */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oamrx_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oamrx_add),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oamrx_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oamrx_update),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oamrx_delete),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oamrx_remove),
     
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_maidmep_t_init),  /* Hash maidmep */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_maidmep_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_maidmep_add),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_maidmep_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_maidmep_update),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_maidmep_delete),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_maidmep_remove),
     
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_emlfilter_t_init),  /* Hash emlfilter */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_emlfilter_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_emlfilter_add),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_emlfilter_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_emlfilter_update),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_emlfilter_delete),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_emlfilter_remove),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_ete_t_init), /* DM ete */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_ete_table_size_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_ete_table_size_set),                          
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_ete_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_ete_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oam_ep_t_init), /* DM oam_ep */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oam_ep_table_size_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oam_ep_table_size_set),                          
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oam_ep_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oam_ep_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oam_local_t_init), /* DM oam_local */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oam_local_table_size_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oam_local_table_size_set),                          
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oam_local_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oam_local_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oam_peer_t_init), /* DM oam_peer */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oam_peer_table_size_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oam_peer_table_size_set),                          
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oam_peer_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_oam_peer_get),
     
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_labels3_t_init),  /* Hash labels3 */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_labels3_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_labels3_add),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_labels3_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_labels3_update),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_labels3_delete),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_labels3_remove),
     
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_bfd_ld2e_t_init),  /* Hash bfd_ld2e */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_bfd_ld2e_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_bfd_ld2e_add),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_bfd_ld2e_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_bfd_ld2e_update),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_bfd_ld2e_delete),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_bfd_ld2e_remove),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_sample_dm1_t_init), /* DM sample_dm1 */
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_sample_dm1_table_size_get),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_sample_dm1_table_size_set),                          
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_sample_dm1_set),
      CINT_FWRAPPER_ENTRY(soc_sbx_g3p1_sample_dm1_get),
   { NULL }
};
 
/*
 * struct type table
 */ 
static cint_struct_type_t __cint_g3p1_structures [] = 
{
      {  /* mac */
            "soc_sbx_g3p1_mac_t",
            sizeof(soc_sbx_g3p1_mac_t),
            __cint_struct_members__soc_sbx_g3p1_mac_t,
            __cint_maddr__soc_sbx_g3p1_mac_t
      },
      {  /* pvv2e */
            "soc_sbx_g3p1_pvv2e_t",
            sizeof(soc_sbx_g3p1_pvv2e_t),
            __cint_struct_members__soc_sbx_g3p1_pvv2e_t,
            __cint_maddr__soc_sbx_g3p1_pvv2e_t
      },
      {  /* labels */
            "soc_sbx_g3p1_labels_t",
            sizeof(soc_sbx_g3p1_labels_t),
            __cint_struct_members__soc_sbx_g3p1_labels_t,
            __cint_maddr__soc_sbx_g3p1_labels_t
      },
      {  /* v4da */
            "soc_sbx_g3p1_v4da_t",
            sizeof(soc_sbx_g3p1_v4da_t),
            __cint_struct_members__soc_sbx_g3p1_v4da_t,
            __cint_maddr__soc_sbx_g3p1_v4da_t
      },
      {  /* v4sa */
            "soc_sbx_g3p1_v4sa_t",
            sizeof(soc_sbx_g3p1_v4sa_t),
            __cint_struct_members__soc_sbx_g3p1_v4sa_t,
            __cint_maddr__soc_sbx_g3p1_v4sa_t
      },
      {  /* v4mc_sgv */
            "soc_sbx_g3p1_v4mc_sgv_t",
            sizeof(soc_sbx_g3p1_v4mc_sgv_t),
            __cint_struct_members__soc_sbx_g3p1_v4mc_sgv_t,
            __cint_maddr__soc_sbx_g3p1_v4mc_sgv_t
      },
      {  /* v4mc_gv */
            "soc_sbx_g3p1_v4mc_gv_t",
            sizeof(soc_sbx_g3p1_v4mc_gv_t),
            __cint_struct_members__soc_sbx_g3p1_v4mc_gv_t,
            __cint_maddr__soc_sbx_g3p1_v4mc_gv_t
      },
      {  /* v6da */
            "soc_sbx_g3p1_v6da_t",
            sizeof(soc_sbx_g3p1_v6da_t),
            __cint_struct_members__soc_sbx_g3p1_v6da_t,
            __cint_maddr__soc_sbx_g3p1_v6da_t
      },
      {  /* v6sa */
            "soc_sbx_g3p1_v6sa_t",
            sizeof(soc_sbx_g3p1_v6sa_t),
            __cint_struct_members__soc_sbx_g3p1_v6sa_t,
            __cint_maddr__soc_sbx_g3p1_v6sa_t
      },
      {  /* v6mc_gv */
            "soc_sbx_g3p1_v6mc_gv_t",
            sizeof(soc_sbx_g3p1_v6mc_gv_t),
            __cint_struct_members__soc_sbx_g3p1_v6mc_gv_t,
            __cint_maddr__soc_sbx_g3p1_v6mc_gv_t
      },
      {  /* v6mc_sgv */
            "soc_sbx_g3p1_v6mc_sgv_t",
            sizeof(soc_sbx_g3p1_v6mc_sgv_t),
            __cint_struct_members__soc_sbx_g3p1_v6mc_sgv_t,
            __cint_maddr__soc_sbx_g3p1_v6mc_sgv_t
      },
      {  /* oamrx */
            "soc_sbx_g3p1_oamrx_t",
            sizeof(soc_sbx_g3p1_oamrx_t),
            __cint_struct_members__soc_sbx_g3p1_oamrx_t,
            __cint_maddr__soc_sbx_g3p1_oamrx_t
      },
      {  /* maidmep */
            "soc_sbx_g3p1_maidmep_t",
            sizeof(soc_sbx_g3p1_maidmep_t),
            __cint_struct_members__soc_sbx_g3p1_maidmep_t,
            __cint_maddr__soc_sbx_g3p1_maidmep_t
      },
      {  /* emlfilter */
            "soc_sbx_g3p1_emlfilter_t",
            sizeof(soc_sbx_g3p1_emlfilter_t),
            __cint_struct_members__soc_sbx_g3p1_emlfilter_t,
            __cint_maddr__soc_sbx_g3p1_emlfilter_t
      },
      {  /* ete */
            "soc_sbx_g3p1_ete_t",
            sizeof(soc_sbx_g3p1_ete_t),
            __cint_struct_members__soc_sbx_g3p1_ete_t,
            __cint_maddr__soc_sbx_g3p1_ete_t
      },
      {  /* oam_ep */
            "soc_sbx_g3p1_oam_ep_t",
            sizeof(soc_sbx_g3p1_oam_ep_t),
            __cint_struct_members__soc_sbx_g3p1_oam_ep_t,
            __cint_maddr__soc_sbx_g3p1_oam_ep_t
      },
      {  /* oam_local */
            "soc_sbx_g3p1_oam_local_t",
            sizeof(soc_sbx_g3p1_oam_local_t),
            __cint_struct_members__soc_sbx_g3p1_oam_local_t,
            __cint_maddr__soc_sbx_g3p1_oam_local_t
      },
      {  /* oam_peer */
            "soc_sbx_g3p1_oam_peer_t",
            sizeof(soc_sbx_g3p1_oam_peer_t),
            __cint_struct_members__soc_sbx_g3p1_oam_peer_t,
            __cint_maddr__soc_sbx_g3p1_oam_peer_t
      },
      {  /* labels3 */
            "soc_sbx_g3p1_labels3_t",
            sizeof(soc_sbx_g3p1_labels3_t),
            __cint_struct_members__soc_sbx_g3p1_labels3_t,
            __cint_maddr__soc_sbx_g3p1_labels3_t
      },
      {  /* bfd_ld2e */
            "soc_sbx_g3p1_bfd_ld2e_t",
            sizeof(soc_sbx_g3p1_bfd_ld2e_t),
            __cint_struct_members__soc_sbx_g3p1_bfd_ld2e_t,
            __cint_maddr__soc_sbx_g3p1_bfd_ld2e_t
      },
      {  /* sample_dm1 */
            "soc_sbx_g3p1_sample_dm1_t",
            sizeof(soc_sbx_g3p1_sample_dm1_t),
            __cint_struct_members__soc_sbx_g3p1_sample_dm1_t,
            __cint_maddr__soc_sbx_g3p1_sample_dm1_t
      },
  { NULL }
};

/* 
 * CINT exported datastructure
 */ 
cint_data_t g3p1_tmu_cint_data =
{
    NULL,
    __cint_g3p1_functions,
    __cint_g3p1_structures,
    NULL,   /* __cint_g3p1_enums */
    NULL,   /* __cint_g3p1_typedefs */
    NULL,   /* __cint_g3p1_constants, */
    NULL,   /* __cint_g3p1_function_pointers */
};

#endif
#endif
