# -*- Makefile -*-
# $Id: Makefile,v 1.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
LOCALDIR = src/appl/diag/cint

include ${SDK}/make/Make.config

CFGFLAGS += -I$(SDK)/src/appl/cint

lib = libdiagcint
include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
