/*
 * DO NOT EDIT THIS FILE!
 *
 */

#if defined(INCLUDE_LIB_CINT)

#include <cint_config.h>
#include <cint_types.h>
#include <cint_porting.h>

#if defined(PHYMOD_EPIL_APIS_SUPPORT)

#include <phymod/phymod.h>
#include <phymod/phymod_types.h>
#include "/projects/ntsw-sw7/home/hoang/PLP_ePIL/misc/ePIL-Combined-10.0.1/bcm_pm_if/bcm_pm_if_api.h"

/* Macros section */

/* Functions section */
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         bcm_pm_if_static_config_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         void*, void, bcm_static_config, 1, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         bcm_pm_if_static_config_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         void*, void, bcm_static_config, 1, 0);

CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0,
                         bcm_pm_if_cleanup,
                         uint32_t, uint32_t, phy_id, 0, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_link_status_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t*, uint32_t, link_status, 1, 0);

CINT_FWRAPPER_CREATE_RP9(int, int, 0, 0,
                         bcm_pm_if_mode_config_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         int, int, speed, 0, 0,
                         int, int, if_type, 0, 0,
                         int, int, ref_clk, 0, 0,
                         int, int, interface_mode, 0, 0,
                         void*, void, device_aux_modes, 1, 0);

CINT_FWRAPPER_CREATE_RP9(int, int, 0, 0,
                         bcm_pm_if_mode_config_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         int*, int, speed, 1, 0,
                         int*, int, if_type, 1, 0,
                         int*, int, ref_clk, 1, 0,
                         int*, int, interface_mode, 1, 0,
                         void*, void, device_aux_modes, 1, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         bcm_pm_if_version_get,
                         uint16_t*, uint16_t, chip_ver, 1, 0,
                         uint16_t*, uint16_t, api_ver, 1, 0,
                         uint16_t*, uint16_t, enahan_ver, 1, 0);

CINT_FWRAPPER_CREATE_RP9(int, int, 0, 0,
                         bcm_pm_if_prbs_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t, uint32_t, tx_rx, 0, 0,
                         uint32_t, uint32_t, poly, 0, 0,
                         uint32_t, uint32_t, invert, 0, 0,
                         uint32_t, uint32_t, loopback, 0, 0,
                         uint32_t, uint32_t, ena_dis, 0, 0);

CINT_FWRAPPER_CREATE_RP9(int, int, 0, 0,
                         bcm_pm_if_prbs_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t, uint32_t, tx_rx, 0, 0,
                         uint32_t*, uint32_t, poly, 1, 0,
                         uint32_t*, uint32_t, invert, 1, 0,
                         uint32_t*, uint32_t, loopback, 1, 0,
                         uint32_t*, uint32_t, ena_dis, 1, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_prbs_rx_stat,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t, uint32_t, time, 0, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_prbs_clear,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t, uint32_t, tx_rx, 0, 0);

CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0,
                         bcm_pm_if_prbs_config_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t, uint32_t, tx_rx, 0, 0,
                         uint32_t*, uint32_t, poly, 1, 0,
                         uint32_t*, uint32_t, invert, 1, 0);

CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0,
                         bcm_pm_if_prbs_status_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t*, uint32_t, prbs_lock, 1, 0,
                         uint32_t*, uint32_t, prbs_lock_loss, 1, 0,
                         uint32_t*, uint32_t, error_count, 1, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_reg_value_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, devaddr, 0, 0,
                         uint32_t, uint32_t, regaddr, 0, 0,
                         uint32_t, uint32_t, data, 0, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_reg_value_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, devaddr, 0, 0,
                         uint32_t, uint32_t, regaddr, 0, 0,
                         uint32_t*, uint32_t, data, 1, 0);

CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0,
                         bcm_pm_if_polarity_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t, uint32_t, tx_pol, 0, 0,
                         uint32_t, uint32_t, rx_pol, 0, 0);

CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0,
                         bcm_pm_if_polarity_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t*, uint32_t, tx_pol, 1, 0,
                         uint32_t*, uint32_t, rx_pol, 1, 0);

CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0,
                         bcm_pm_if_power_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t, uint32_t, power_rx, 0, 0,
                         uint32_t, uint32_t, power_tx, 0, 0);

CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0,
                         bcm_pm_if_power_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t*, uint32_t, power_rx, 1, 0,
                         uint32_t*, uint32_t, power_tx, 1, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_rx_pmd_locked_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t*, uint32_t, rx_pmd_locked, 1, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         bcm_pm_if_rev_id,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t*, uint32_t, rev_id, 1, 0);

CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0,
                         bcm_pm_if_loopback_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t, uint32_t, lb_mode, 0, 0,
                         uint32_t, uint32_t, enable, 0, 0);

CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0,
                         bcm_pm_if_loopback_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t, uint32_t, lb_mode, 0, 0,
                         uint32_t*, uint32_t, enable, 1, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_tx_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         plp_bcm_tx_t*, plp_bcm_tx_t, tx, 1, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_tx_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         plp_bcm_tx_t*, plp_bcm_tx_t, tx, 1, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_rx_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         plp_bcm_rx_t*, plp_bcm_rx_t, rx, 1, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_rx_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         plp_bcm_rx_t*, plp_bcm_rx_t, rx, 1, 0);

CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0,
                         bcm_pm_if_reset_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, reset_mode, 0, 0,
                         uint32_t, uint32_t, reset_val, 0, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_phy_lane_reset_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         bcm_pm_phy_reset_t*, bcm_pm_phy_reset_t, reset, 1, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_phy_lane_reset_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         bcm_pm_phy_reset_t*, bcm_pm_phy_reset_t, reset, 1, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_tx_lane_control_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         bcm_pm_phy_tx_lane_control_t, bcm_pm_phy_tx_lane_control_t, tx_controlrx_control, 0, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_rx_lane_control_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         bcm_pm_phy_rx_lane_control_t, bcm_pm_phy_rx_lane_control_t, rx_controlrx_control, 0, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_tx_lane_control_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         bcm_pm_phy_tx_lane_control_t*, bcm_pm_phy_tx_lane_control_t, tx_controlrx_control, 1, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_rx_lane_control_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         bcm_pm_phy_rx_lane_control_t*, bcm_pm_phy_rx_lane_control_t, rx_controlrx_control, 1, 0);

CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0,
                         bcm_pm_if_lane_cross_switch_map_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t*, uint32_t, tx_source_array, 1, 0);

CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0,
                         bcm_pm_if_lane_cross_switch_map_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t*, uint32_t, mapped_to, 1, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_force_tx_training_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t, uint32_t, enable, 0, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_force_tx_training_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t*, uint32_t, enable, 1, 0);

CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0,
                         bcm_pm_if_force_tx_training_status_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t*, uint32_t, enable, 1, 0,
                         uint32_t*, uint32_t, training_failure, 1, 0,
                         uint32_t*, uint32_t, trained, 1, 0);

CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0,
                         bcm_pm_if_cl73_ability_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint16_t, uint16_t, tech_ability, 0, 0,
                         uint16_t, uint16_t, fec_ability, 0, 0,
                         uint16_t, uint16_t, pause_ability, 0, 0);

CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0,
                         bcm_pm_if_cl73_ability_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint16_t*, uint16_t, tech_ability, 1, 0,
                         uint16_t*, uint16_t, fec_ability, 1, 0,
                         uint16_t*, uint16_t, pause_ability, 1, 0);

CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0,
                         bcm_pm_if_cl73_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint16_t, uint16_t, ena_dis, 0, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_cl73_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t*, uint32_t, an, 1, 0,
                         uint32_t*, uint32_t, an_done, 1, 0);

CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0,
                         bcm_pm_if_display_eye_scan,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0);

CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0,
                         bcm_pm_if_firmware_info_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t*, uint32_t, fw_version, 1, 0,
                         uint32_t*, uint32_t, fw_crc, 1, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_pll_sequencer_restart,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         unsigned char, unsigned char, flags, 0, 0,
                         bcm_pm_sequencer_operation_t, bcm_pm_sequencer_operation_t, operation, 0, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         bcm_pm_if_fec_enable_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, enable, 0, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         bcm_pm_if_fec_enable_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t*, uint32_t, enable, 1, 0);

CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0,
                         bcm_pm_if_phy_status_dump,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_phy_diagnostics_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         bcm_pm_phy_diagnostics_t*, bcm_pm_phy_diagnostics_t, diag, 1, 0);

CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0,
                         bcm_pm_if_intr_status_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, intr_type, 0, 0,
                         uint32_t*, uint32_t, intr_status, 1, 0);

CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0,
                         bcm_pm_if_intr_enable_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, intr_type, 0, 0,
                         uint32_t, uint32_t, enable, 0, 0);

CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0,
                         bcm_pm_if_intr_enable_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, intr_type, 0, 0,
                         uint32_t*, uint32_t, enable, 1, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         bcm_pm_if_intr_status_clear,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, intr_type, 0, 0);

CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0,
                         bcm_pm_fc_pcs_chkr_enable_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t, uint32_t, fcpcs_chkr_mode, 0, 0,
                         uint32_t, uint32_t, enable, 0, 0);

CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0,
                         bcm_pm_fc_pcs_chkr_enable_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t, uint32_t, fcpcs_chkr_mode, 0, 0,
                         uint32_t*, uint32_t, enable, 1, 0);

CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0,
                         bcm_pm_fc_pcs_chkr_status_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t*, uint32_t, lock_status, 1, 0,
                         uint32_t*, uint32_t, lock_lost_lh, 1, 0,
                         uint32_t*, uint32_t, error_count, 1, 0);

CINT_FWRAPPER_CREATE_RP8(int, int, 0, 0,
                         bcm_pm_if_eye_margin_proj,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         double, double, rate, 0, 0,
                         unsigned char, unsigned char, ber_scan_mode, 0, 0,
                         unsigned char, unsigned char, timer_control, 0, 0,
                         unsigned char, unsigned char, max_error_control, 0, 0);

CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0,
                         bcm_pm_repeater_mode_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t*, uint32_t, ena_dis, 1, 0);

CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0,
                         bcm_pm_repeater_mode_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t, uint32_t, ena_dis, 0, 0);

CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0,
                         bcm_pm_if_module_read,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, lane_map, 0, 0,
                         uint32_t, uint32_t, slv_addr, 0, 0,
                         uint32_t, uint32_t, start_addr, 0, 0,
                         uint32_t, uint32_t, no_of_bytes, 0, 0,
                         unsigned char*, unsigned char, read_data, 1, 0);

CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0,
                         bcm_pm_if_module_write,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, lane_map, 0, 0,
                         uint32_t, uint32_t, slv_addr, 0, 0,
                         uint32_t, uint32_t, start_addr, 0, 0,
                         uint32_t, uint32_t, no_of_bytes, 0, 0,
                         unsigned char*, unsigned char, write_data, 1, 0);

CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0,
                         bcm_pm_if_modctrl_cfg_cfp_linecard_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, lane_map, 0, 0,
                         bcm_modctrl_cfp_io_pins_t*, bcm_modctrl_cfp_io_pins_t, mdcrtl_pins, 1, 0);

CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0,
                         bcm_pm_if_modctrl_cfg_qsfp_linecard_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, lane_map, 0, 0,
                         bcm_modctrl_qsfp_io_pins_t*, bcm_modctrl_qsfp_io_pins_t, bcm_modctrl_qsfp_io_pins_t, 1, 0);

CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0,
                         bcm_pm_if_modctrl_cfg_qsfp_linecard_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, lane_map, 0, 0,
                         bcm_modctrl_qsfp_io_pins_t*, bcm_modctrl_qsfp_io_pins_t, bcm_modctrl_qsfp_io_pins_t, 1, 0);

CINT_FWRAPPER_CREATE_RP4(int, int, 0, 0,
                         bcm_pm_if_modctrl_cfg_cfp_linecard_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, lane_map, 0, 0,
                         bcm_modctrl_cfp_io_pins_t*, bcm_modctrl_cfp_io_pins_t, mdcrtl_pins, 1, 0);

CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0,
                         bcm_pm_if_cfg_gpio_pin_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, gpio_pin_number, 0, 0,
                         uint32_t, uint32_t, cfg_direction, 0, 0,
                         uint32_t, uint32_t, cfg_pull, 0, 0,
                         uint32_t, uint32_t, pin_value, 0, 0);

CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0,
                         bcm_pm_if_cfg_gpio_pin_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, gpio_pin_number, 0, 0,
                         uint32_t*, uint32_t, cfg_direction, 1, 0,
                         uint32_t*, uint32_t, cfg_pull, 1, 0,
                         uint32_t*, uint32_t, pin_value, 1, 0);

CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0,
                         bcm_pm_if_lane_reg_value_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, devaddr, 0, 0,
                         uint32_t, uint32_t, regaddr, 0, 0,
                         uint32_t, uint32_t, data, 0, 0);

CINT_FWRAPPER_CREATE_RP7(int, int, 0, 0,
                         bcm_pm_if_lane_reg_value_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, lane, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, devaddr, 0, 0,
                         uint32_t, uint32_t, regaddr, 0, 0,
                         uint32_t*, uint32_t, data, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         bcm_pm_if_lane_config_set,
                         void*, void, platform_ctxt, 1, 0,
                         bcm_pm_lane_config_t*, bcm_pm_lane_config_t, lane_config, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         bcm_pm_if_lane_config_get,
                         void*, void, platform_ctxt, 1, 0,
                         bcm_pm_lane_config_t*, bcm_pm_lane_config_t, lane_config, 1, 0);

CINT_FWRAPPER_CREATE_RP5(int, int, 0, 0,
                         bcm_pm_if_short_channel_mode_set,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane_map, 0, 0,
                         uint32_t, uint32_t, ena_dis, 0, 0);

CINT_FWRAPPER_CREATE_RP6(int, int, 0, 0,
                         bcm_pm_if_short_channel_mode_get,
                         void*, void, platform_ctxt, 1, 0,
                         uint32_t, uint32_t, phy_id, 0, 0,
                         uint32_t, uint32_t, if_side, 0, 0,
                         uint32_t, uint32_t, lane_map, 0, 0,
                         uint32_t*, uint32_t, ena_dis, 1, 0,
                         uint32_t*, uint32_t, status, 1, 0);


/* Functions and Macros mapping */
static cint_function_t __cint_functions[] =
{
    CINT_FWRAPPER_ENTRY(bcm_pm_if_static_config_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_static_config_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_cleanup),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_link_status_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_mode_config_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_mode_config_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_version_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_prbs_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_prbs_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_prbs_rx_stat),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_prbs_clear),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_prbs_config_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_prbs_status_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_reg_value_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_reg_value_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_polarity_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_polarity_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_power_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_power_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_rx_pmd_locked_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_rev_id),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_loopback_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_loopback_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_tx_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_tx_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_rx_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_rx_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_reset_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_phy_lane_reset_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_phy_lane_reset_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_tx_lane_control_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_rx_lane_control_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_tx_lane_control_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_rx_lane_control_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_lane_cross_switch_map_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_lane_cross_switch_map_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_force_tx_training_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_force_tx_training_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_force_tx_training_status_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_cl73_ability_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_cl73_ability_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_cl73_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_cl73_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_display_eye_scan),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_firmware_info_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_pll_sequencer_restart),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_fec_enable_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_fec_enable_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_phy_status_dump),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_phy_diagnostics_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_intr_status_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_intr_enable_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_intr_enable_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_intr_status_clear),
    CINT_FWRAPPER_ENTRY(bcm_pm_fc_pcs_chkr_enable_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_fc_pcs_chkr_enable_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_fc_pcs_chkr_status_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_eye_margin_proj),
    CINT_FWRAPPER_ENTRY(bcm_pm_repeater_mode_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_repeater_mode_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_module_read),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_module_write),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_modctrl_cfg_cfp_linecard_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_modctrl_cfg_qsfp_linecard_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_modctrl_cfg_qsfp_linecard_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_modctrl_cfg_cfp_linecard_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_cfg_gpio_pin_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_cfg_gpio_pin_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_lane_reg_value_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_lane_reg_value_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_lane_config_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_lane_config_get),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_short_channel_mode_set),
    CINT_FWRAPPER_ENTRY(bcm_pm_if_short_channel_mode_get),
    { NULL }
};

/* Functions pointers section */
static cint_function_pointer_t __cint_function_pointers[1];



static cint_function_pointer_t __cint_function_pointers[] = 
{
    { NULL }
};

/* Structs section */
static void*
__cint_maddr__bcm_pm_lane_config_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    bcm_pm_lane_config_t* s = (bcm_pm_lane_config_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->phy_id);break;
        case 1: rv = &(s->if_side);break;
        case 2: rv = &(s->lane);break;
        case 3: rv = &(s->firmware_mode);break;
        case 4: rv = &(s->ena_dis);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__bcm_value_override_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    bcm_value_override_t* s = (bcm_value_override_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->enable);break;
        case 1: rv = &(s->value);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__plp_bcm_rx_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    plp_bcm_rx_t* s = (plp_bcm_rx_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->vga);break;
        case 1: rv = &(s->num_of_dfe_taps);break;
        case 2: rv = &(s->dfe);break;
        case 3: rv = &(s->peaking_filter);break;
        case 4: rv = &(s->low_freq_peaking_filter);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__plp_bcm_tx_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    plp_bcm_tx_t* s = (plp_bcm_tx_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->pre);break;
        case 1: rv = &(s->main);break;
        case 2: rv = &(s->post);break;
        case 3: rv = &(s->post2);break;
        case 4: rv = &(s->post3);break;
        case 5: rv = &(s->amp);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__bcm_pm_diag_slicer_offset_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    bcm_pm_diag_slicer_offset_t* s = (bcm_pm_diag_slicer_offset_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->offset_pe);break;
        case 1: rv = &(s->offset_ze);break;
        case 2: rv = &(s->offset_me);break;
        case 3: rv = &(s->offset_po);break;
        case 4: rv = &(s->offset_zo);break;
        case 5: rv = &(s->offset_mo);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__bcm_pm_diag_eyescan_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    bcm_pm_diag_eyescan_t* s = (bcm_pm_diag_eyescan_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->heye_left);break;
        case 1: rv = &(s->heye_right);break;
        case 2: rv = &(s->veye_upper);break;
        case 3: rv = &(s->veye_lower);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__bcm_pm_phy_diagnostics_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    bcm_pm_phy_diagnostics_t* s = (bcm_pm_phy_diagnostics_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->signal_detect);break;
        case 1: rv = &(s->vga_bias_reduced);break;
        case 2: rv = &(s->postc_metric);break;
        case 3: rv = &(s->osr_mode);break;
        case 4: rv = &(s->pmd_mode);break;
        case 5: rv = &(s->rx_lock);break;
        case 6: rv = &(s->rx_ppm);break;
        case 7: rv = &(s->tx_ppm);break;
        case 8: rv = &(s->clk90_offset);break;
        case 9: rv = &(s->clkp1_offset);break;
        case 10: rv = &(s->p1_lvl);break;
        case 11: rv = &(s->m1_lvl);break;
        case 12: rv = &(s->dfe1_dcd);break;
        case 13: rv = &(s->dfe2_dcd);break;
        case 14: rv = &(s->slicer_target);break;
        case 15: rv = &(s->slicer_offset);break;
        case 16: rv = &(s->eyescan);break;
        case 17: rv = &(s->state_machine_status);break;
        case 18: rv = &(s->link_time);break;
        case 19: rv = &(s->pf_main);break;
        case 20: rv = &(s->pf_hiz);break;
        case 21: rv = &(s->pf_bst);break;
        case 22: rv = &(s->pf_low);break;
        case 23: rv = &(s->pf2_ctrl);break;
        case 24: rv = &(s->vga);break;
        case 25: rv = &(s->dc_offset);break;
        case 26: rv = &(s->p1_lvl_ctrl);break;
        case 27: rv = &(s->dfe1);break;
        case 28: rv = &(s->dfe2);break;
        case 29: rv = &(s->dfe3);break;
        case 30: rv = &(s->dfe4);break;
        case 31: rv = &(s->dfe5);break;
        case 32: rv = &(s->dfe6);break;
        case 33: rv = &(s->txfir_pre);break;
        case 34: rv = &(s->txfir_main);break;
        case 35: rv = &(s->txfir_post1);break;
        case 36: rv = &(s->txfir_post2);break;
        case 37: rv = &(s->txfir_post3);break;
        case 38: rv = &(s->tx_amp_ctrl);break;
        case 39: rv = &(s->br_pd_en);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__bcm_pm_phy_reset_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    bcm_pm_phy_reset_t* s = (bcm_pm_phy_reset_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->rx);break;
        case 1: rv = &(s->tx);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__sesto_static_config_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    sesto_static_config_t* s = (sesto_static_config_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->an_mst_lane_p0);break;
        case 1: rv = &(s->an_mst_lane_p1);break;
        case 2: rv = &(s->far_side_intf_loss_lock);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__furia_static_config_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    furia_static_config_t* s = (furia_static_config_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->rptr_mode);break;
        case 1: rv = &(s->avdd_txdrv);break;
        case 2: rv = &(s->ull_dp);break;
        case 3: rv = &(s->an_master_lane);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__bcm_phy_static_config_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    bcm_phy_static_config_t* s = (bcm_phy_static_config_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->phy_id);break;
        case 1: rv = &(s->bcm_static_config);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__bcm_modctrl_pin_io_value_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    bcm_modctrl_pin_io_value_t* s = (bcm_modctrl_pin_io_value_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->enable);break;
        case 1: rv = &(s->value);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__bcm_modctrl_cfp_io_pins_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    bcm_modctrl_cfp_io_pins_t* s = (bcm_modctrl_cfp_io_pins_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->tx_dis);break;
        case 1: rv = &(s->rx_los);break;
        case 2: rv = &(s->mod_lopwr);break;
        case 3: rv = &(s->mod_abs);break;
        case 4: rv = &(s->glb_alrmn);break;
        case 5: rv = &(s->mod_rstn);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__bcm_modctrl_qsfp_io_pins_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    bcm_modctrl_qsfp_io_pins_t* s = (bcm_modctrl_qsfp_io_pins_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->lpmod);break;
        case 1: rv = &(s->resetl);break;
        case 2: rv = &(s->intl);break;
        case 3: rv = &(s->mod_sell);break;
        case 4: rv = &(s->mod_prsl);break;
        default: rv = NULL; break;
    }
    return rv;
}


static cint_parameter_desc_t __cint_struct_members__bcm_pm_lane_config_t[] = 
{
    {"int32_t", "phy_id", 0, 0},
    {"int32_t", "if_side", 0, 0},
    {"int32_t", "lane", 0, 0},
    {"bcm_pm_firmware_mode_t", "firmware_mode", 0, 0},
    {"int32_t", "ena_dis", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__bcm_value_override_t[] = 
{
    {"uint32_t", "enable", 0, 0},
    {"uint32_t", "value", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__plp_bcm_rx_t[] = 
{
    {"bcm_value_override_t", "vga", 0, 0},
    {"uint32_t", "num_of_dfe_taps", 0, 0},
    {"bcm_value_override_t", "dfe", 0, 0},
    {"bcm_value_override_t", "peaking_filter", 0, 0},
    {"bcm_value_override_t", "low_freq_peaking_filter", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__plp_bcm_tx_t[] = 
{
    {"char", "pre", 0, 0},
    {"char", "main", 0, 0},
    {"char", "post", 0, 0},
    {"char", "post2", 0, 0},
    {"char", "post3", 0, 0},
    {"char", "amp", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__bcm_pm_diag_slicer_offset_t[] = 
{
    {"uint32_t", "offset_pe", 0, 0},
    {"uint32_t", "offset_ze", 0, 0},
    {"uint32_t", "offset_me", 0, 0},
    {"uint32_t", "offset_po", 0, 0},
    {"uint32_t", "offset_zo", 0, 0},
    {"uint32_t", "offset_mo", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__bcm_pm_diag_eyescan_t[] = 
{
    {"uint32_t", "heye_left", 0, 0},
    {"uint32_t", "heye_right", 0, 0},
    {"uint32_t", "veye_upper", 0, 0},
    {"uint32_t", "veye_lower", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__bcm_pm_phy_diagnostics_t[] = 
{
    {"uint32_t", "signal_detect", 0, 0},
    {"uint32_t", "vga_bias_reduced", 0, 0},
    {"uint32_t", "postc_metric", 0, 0},
    {"bcm_pm_osr_mode_t", "osr_mode", 0, 0},
    {"bcm_pm_pmd_mode_t", "pmd_mode", 0, 0},
    {"uint32_t", "rx_lock", 0, 0},
    {"uint32_t", "rx_ppm", 0, 0},
    {"uint32_t", "tx_ppm", 0, 0},
    {"uint32_t", "clk90_offset", 0, 0},
    {"uint32_t", "clkp1_offset", 0, 0},
    {"uint32_t", "p1_lvl", 0, 0},
    {"uint32_t", "m1_lvl", 0, 0},
    {"uint32_t", "dfe1_dcd", 0, 0},
    {"uint32_t", "dfe2_dcd", 0, 0},
    {"uint32_t", "slicer_target", 0, 0},
    {"bcm_pm_diag_slicer_offset_t", "slicer_offset", 0, 0},
    {"bcm_pm_diag_eyescan_t", "eyescan", 0, 0},
    {"uint32_t", "state_machine_status", 0, 0},
    {"uint32_t", "link_time", 0, 0},
    {"char", "pf_main", 0, 0},
    {"char", "pf_hiz", 0, 0},
    {"char", "pf_bst", 0, 0},
    {"char", "pf_low", 0, 0},
    {"char", "pf2_ctrl", 0, 0},
    {"char", "vga", 0, 0},
    {"char", "dc_offset", 0, 0},
    {"char", "p1_lvl_ctrl", 0, 0},
    {"char", "dfe1", 0, 0},
    {"char", "dfe2", 0, 0},
    {"char", "dfe3", 0, 0},
    {"char", "dfe4", 0, 0},
    {"char", "dfe5", 0, 0},
    {"char", "dfe6", 0, 0},
    {"char", "txfir_pre", 0, 0},
    {"char", "txfir_main", 0, 0},
    {"char", "txfir_post1", 0, 0},
    {"char", "txfir_post2", 0, 0},
    {"char", "txfir_post3", 0, 0},
    {"char", "tx_amp_ctrl", 0, 0},
    {"unsigned char", "br_pd_en", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__bcm_pm_phy_reset_t[] = 
{
    {"bcm_pm_reset_direction_t", "rx", 0, 0},
    {"bcm_pm_reset_direction_t", "tx", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__sesto_static_config_t[] = 
{
    {"uint32_t", "an_mst_lane_p0", 0, 0},
    {"uint32_t", "an_mst_lane_p1", 0, 0},
    {"uint32_t", "far_side_intf_loss_lock", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__furia_static_config_t[] = 
{
    {"uint32_t", "rptr_mode", 0, 0},
    {"uint32_t", "avdd_txdrv", 0, 0},
    {"uint32_t", "ull_dp", 0, 0},
    {"uint32_t", "an_master_lane", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__bcm_phy_static_config_t[] = 
{
    {"uint32_t", "phy_id", 0, 0},
    {"void", "bcm_static_config", 1, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__bcm_modctrl_pin_io_value_t[] = 
{
    {"uint32_t", "enable", 0, 0},
    {"uint32_t", "value", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__bcm_modctrl_cfp_io_pins_t[] = 
{
    {"bcm_modctrl_pin_io_value_t", "tx_dis", 0, 0},
    {"bcm_modctrl_pin_io_value_t", "rx_los", 0, 0},
    {"bcm_modctrl_pin_io_value_t", "mod_lopwr", 0, 0},
    {"bcm_modctrl_pin_io_value_t", "mod_abs", 0, 0},
    {"bcm_modctrl_pin_io_value_t", "glb_alrmn", 0, 0},
    {"bcm_modctrl_pin_io_value_t", "mod_rstn", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__bcm_modctrl_qsfp_io_pins_t[] = 
{
    {"bcm_modctrl_pin_io_value_t", "lpmod", 0, 0},
    {"bcm_modctrl_pin_io_value_t", "resetl", 0, 0},
    {"bcm_modctrl_pin_io_value_t", "intl", 0, 0},
    {"bcm_modctrl_pin_io_value_t", "mod_sell", 0, 0},
    {"bcm_modctrl_pin_io_value_t", "mod_prsl", 0, 0},
    { NULL }
};


static cint_struct_type_t __cint_structures[] =
{
    {
    "bcm_pm_lane_config_t",
    sizeof(bcm_pm_lane_config_t),
    __cint_struct_members__bcm_pm_lane_config_t,
    __cint_maddr__bcm_pm_lane_config_t
    },
    {
    "bcm_value_override_t",
    sizeof(bcm_value_override_t),
    __cint_struct_members__bcm_value_override_t,
    __cint_maddr__bcm_value_override_t
    },
    {
    "plp_bcm_rx_t",
    sizeof(plp_bcm_rx_t),
    __cint_struct_members__plp_bcm_rx_t,
    __cint_maddr__plp_bcm_rx_t
    },
    {
    "plp_bcm_tx_t",
    sizeof(plp_bcm_tx_t),
    __cint_struct_members__plp_bcm_tx_t,
    __cint_maddr__plp_bcm_tx_t
    },
    {
    "bcm_pm_diag_slicer_offset_t",
    sizeof(bcm_pm_diag_slicer_offset_t),
    __cint_struct_members__bcm_pm_diag_slicer_offset_t,
    __cint_maddr__bcm_pm_diag_slicer_offset_t
    },
    {
    "bcm_pm_diag_eyescan_t",
    sizeof(bcm_pm_diag_eyescan_t),
    __cint_struct_members__bcm_pm_diag_eyescan_t,
    __cint_maddr__bcm_pm_diag_eyescan_t
    },
    {
    "bcm_pm_phy_diagnostics_t",
    sizeof(bcm_pm_phy_diagnostics_t),
    __cint_struct_members__bcm_pm_phy_diagnostics_t,
    __cint_maddr__bcm_pm_phy_diagnostics_t
    },
    {
    "bcm_pm_phy_reset_t",
    sizeof(bcm_pm_phy_reset_t),
    __cint_struct_members__bcm_pm_phy_reset_t,
    __cint_maddr__bcm_pm_phy_reset_t
    },
    {
    "sesto_static_config_t",
    sizeof(sesto_static_config_t),
    __cint_struct_members__sesto_static_config_t,
    __cint_maddr__sesto_static_config_t
    },
    {
    "furia_static_config_t",
    sizeof(furia_static_config_t),
    __cint_struct_members__furia_static_config_t,
    __cint_maddr__furia_static_config_t
    },
    {
    "bcm_phy_static_config_t",
    sizeof(bcm_phy_static_config_t),
    __cint_struct_members__bcm_phy_static_config_t,
    __cint_maddr__bcm_phy_static_config_t
    },
    {
    "bcm_modctrl_pin_io_value_t",
    sizeof(bcm_modctrl_pin_io_value_t),
    __cint_struct_members__bcm_modctrl_pin_io_value_t,
    __cint_maddr__bcm_modctrl_pin_io_value_t
    },
    {
    "bcm_modctrl_cfp_io_pins_t",
    sizeof(bcm_modctrl_cfp_io_pins_t),
    __cint_struct_members__bcm_modctrl_cfp_io_pins_t,
    __cint_maddr__bcm_modctrl_cfp_io_pins_t
    },
    {
    "bcm_modctrl_qsfp_io_pins_t",
    sizeof(bcm_modctrl_qsfp_io_pins_t),
    __cint_struct_members__bcm_modctrl_qsfp_io_pins_t,
    __cint_maddr__bcm_modctrl_qsfp_io_pins_t
    },
    { NULL }
};


/* Enums section */
static cint_enum_map_t __cint_enum_map__bcm_pm_interface_t[] =
{
    { "bcm_pm_InterfaceBypass", bcm_pm_InterfaceBypass },
    { "bcm_pm_InterfaceSR", bcm_pm_InterfaceSR },
    { "bcm_pm_InterfaceSR4", bcm_pm_InterfaceSR4 },
    { "bcm_pm_InterfaceKX", bcm_pm_InterfaceKX },
    { "bcm_pm_InterfaceKX4", bcm_pm_InterfaceKX4 },
    { "bcm_pm_InterfaceKR", bcm_pm_InterfaceKR },
    { "bcm_pm_InterfaceKR2", bcm_pm_InterfaceKR2 },
    { "bcm_pm_InterfaceKR4", bcm_pm_InterfaceKR4 },
    { "bcm_pm_InterfaceCX", bcm_pm_InterfaceCX },
    { "bcm_pm_InterfaceCX2", bcm_pm_InterfaceCX2 },
    { "bcm_pm_InterfaceCX4", bcm_pm_InterfaceCX4 },
    { "bcm_pm_InterfaceCR", bcm_pm_InterfaceCR },
    { "bcm_pm_InterfaceCR2", bcm_pm_InterfaceCR2 },
    { "bcm_pm_InterfaceCR4", bcm_pm_InterfaceCR4 },
    { "bcm_pm_InterfaceCR10", bcm_pm_InterfaceCR10 },
    { "bcm_pm_InterfaceXFI", bcm_pm_InterfaceXFI },
    { "bcm_pm_InterfaceSFI", bcm_pm_InterfaceSFI },
    { "bcm_pm_InterfaceSFPDAC", bcm_pm_InterfaceSFPDAC },
    { "bcm_pm_InterfaceXGMII", bcm_pm_InterfaceXGMII },
    { "bcm_pm_Interface1000X", bcm_pm_Interface1000X },
    { "bcm_pm_InterfaceSGMII", bcm_pm_InterfaceSGMII },
    { "bcm_pm_InterfaceRXAUI", bcm_pm_InterfaceRXAUI },
    { "bcm_pm_InterfaceX2", bcm_pm_InterfaceX2 },
    { "bcm_pm_InterfaceXLAUI", bcm_pm_InterfaceXLAUI },
    { "bcm_pm_InterfaceXLAUI2", bcm_pm_InterfaceXLAUI2 },
    { "bcm_pm_InterfaceCAUI", bcm_pm_InterfaceCAUI },
    { "bcm_pm_InterfaceLR4", bcm_pm_InterfaceLR4 },
    { "bcm_pm_InterfaceLR", bcm_pm_InterfaceLR },
    { "bcm_pm_InterfaceER", bcm_pm_InterfaceER },
    { "bcm_pm_InterfaceER4", bcm_pm_InterfaceER4 },
    { "bcm_pm_InterfaceSR10", bcm_pm_InterfaceSR10 },
    { "bcm_pm_InterfaceCAUI4", bcm_pm_InterfaceCAUI4 },
    { "bcm_pm_InterfaceVSR", bcm_pm_InterfaceVSR },
    { "bcm_pm_InterfaceXLAUI4", bcm_pm_InterfaceXLAUI4 },
    { "bcm_pm_InterfaceLR10", bcm_pm_InterfaceLR10 },
    { "bcm_pm_InterfaceKR10", bcm_pm_InterfaceKR10 },
    { "bcm_pm_InterfaceXAUI", bcm_pm_InterfaceXAUI },
    { "bcm_pm_InterfaceQSGMII", bcm_pm_InterfaceQSGMII },
    { "bcm_pm_InterfaceLR2", bcm_pm_InterfaceLR2 },
    { "bcm_pm_InterfaceER2", bcm_pm_InterfaceER2 },
    { "bcm_pm_InterfaceSR2", bcm_pm_InterfaceSR2 },
    { "bcm_pm_InterfaceCAUI4_C2C", bcm_pm_InterfaceCAUI4_C2C },
    { "bcm_pm_InterfaceCAUI4_C2M", bcm_pm_InterfaceCAUI4_C2M },
    { "bcm_pm_InterfaceZR", bcm_pm_InterfaceZR },
    { "bcm_pm_InterfaceLRM", bcm_pm_InterfaceLRM },
    { "bcm_pm_InterfaceOTN", bcm_pm_InterfaceOTN },
    { "bcm_pm_InterfaceXLPPI", bcm_pm_InterfaceXLPPI },
    { "bcm_pm_InterfaceCount", bcm_pm_InterfaceCount },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__bcm_pm_ref_clk_t[] =
{
    { "bcm_pm_RefClk156Mhz", bcm_pm_RefClk156Mhz },
    { "bcm_pm_RefClk125Mhz", bcm_pm_RefClk125Mhz },
    { "bcm_pm_RefClk106Mhz", bcm_pm_RefClk106Mhz },
    { "bcm_pm_RefClk161Mhz", bcm_pm_RefClk161Mhz },
    { "bcm_pm_RefClk174Mhz", bcm_pm_RefClk174Mhz },
    { "bcm_pm_RefClk312Mhz", bcm_pm_RefClk312Mhz },
    { "bcm_pm_RefClk322Mhz", bcm_pm_RefClk322Mhz },
    { "bcm_pm_RefClk644Mhz", bcm_pm_RefClk644Mhz },
    { "bcm_pm_RefClk349Mhz", bcm_pm_RefClk349Mhz },
    { "bcm_pm_RefClk698Mhz", bcm_pm_RefClk698Mhz },
    { "bcm_pm_RefClkCount", bcm_pm_RefClkCount },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__bcm_pm_interface_mode_t[] =
{
    { "bcm_pm_Interface_mode_IEEE", bcm_pm_Interface_mode_IEEE },
    { "bcm_pm_Interface_mode_HIGIG", bcm_pm_Interface_mode_HIGIG },
    { "bcm_pm_Interface_mode_OTN", bcm_pm_Interface_mode_OTN },
    { "bcm_pm_Interface_mode_FIBER", bcm_pm_Interface_mode_FIBER },
    { "bcm_pm_Interface_mode_Count", bcm_pm_Interface_mode_Count },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__bcm_pm_if_side_t[] =
{
    { "bcm_pm_if_line_side", bcm_pm_if_line_side },
    { "bcm_pm_if_system_side", bcm_pm_if_system_side },
    { "bcm_pm_if_Count", bcm_pm_if_Count },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__bcm_pm_prbs_tx_rx_t[] =
{
    { "bcm_pm_Prbs_tx_rx", bcm_pm_Prbs_tx_rx },
    { "bcm_pm_Prbs_rx", bcm_pm_Prbs_rx },
    { "bcm_pm_Prbs_tx", bcm_pm_Prbs_tx },
    { "bcm_pm_Prbs_tx_rx_count", bcm_pm_Prbs_tx_rx_count },
    { "bcm_pm_Prbs_Count", bcm_pm_Prbs_Count },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__bcm_pm_prbs_poly_t[] =
{
    { "bcm_pm_PrbsPoly7", bcm_pm_PrbsPoly7 },
    { "bcm_pm_PrbsPoly9", bcm_pm_PrbsPoly9 },
    { "bcm_pm_PrbsPoly11", bcm_pm_PrbsPoly11 },
    { "bcm_pm_PrbsPoly15", bcm_pm_PrbsPoly15 },
    { "bcm_pm_PrbsPoly23", bcm_pm_PrbsPoly23 },
    { "bcm_pm_PrbsPoly31", bcm_pm_PrbsPoly31 },
    { "bcm_pm_PrbsPoly58", bcm_pm_PrbsPoly58 },
    { "bcm_pm_PrbsPolyCount", bcm_pm_PrbsPolyCount },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__bcm_pm_osr_mode_t[] =
{
    { "bcmpmOversampleMode1", bcmpmOversampleMode1 },
    { "bcmpmOversampleMode2", bcmpmOversampleMode2 },
    { "bcmpmOversampleMode3", bcmpmOversampleMode3 },
    { "bcmpmOversampleMode3P3", bcmpmOversampleMode3P3 },
    { "bcmpmOversampleMode4", bcmpmOversampleMode4 },
    { "bcmpmOversampleMode5", bcmpmOversampleMode5 },
    { "bcmpmOversampleMode8", bcmpmOversampleMode8 },
    { "bcmpmOversampleMode8P25", bcmpmOversampleMode8P25 },
    { "bcmpmOversampleMode10", bcmpmOversampleMode10 },
    { "bcmpmOversampleModeCount", bcmpmOversampleModeCount },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__bcm_pm_pmd_mode_t[] =
{
    { "bcmpmPmdModeOs", bcmpmPmdModeOs },
    { "bcmpmPmdModeOsDfe", bcmpmPmdModeOsDfe },
    { "bcmpmPmdModeBrDfe", bcmpmPmdModeBrDfe },
    { "bcmpmPmdModeCount", bcmpmPmdModeCount },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__bcm_pm_sequencer_operation_t[] =
{
    { "bcmpmSeqOpStop", bcmpmSeqOpStop },
    { "bcmpmSeqOpStart", bcmpmSeqOpStart },
    { "bcmpmSeqOpRestart", bcmpmSeqOpRestart },
    { "bcmpmSeqOpCount", bcmpmSeqOpCount },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__bcm_pm_phy_tx_lane_control_t[] =
{
    { "bcmpmTxTrafficDisable", bcmpmTxTrafficDisable },
    { "bcmpmTxTrafficEnable", bcmpmTxTrafficEnable },
    { "bcmpmTxReset", bcmpmTxReset },
    { "bcmpmTxSquelchOn", bcmpmTxSquelchOn },
    { "bcmpmTxSquelchOff", bcmpmTxSquelchOff },
    { "bcmpmTxCount", bcmpmTxCount },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__bcm_pm_phy_rx_lane_control_t[] =
{
    { "bcmpmRxReset", bcmpmRxReset },
    { "bcmpmRxSquelchOn", bcmpmRxSquelchOn },
    { "bcmpmRxSquelchOff", bcmpmRxSquelchOff },
    { "bcmpmRxCount", bcmpmRxCount },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__bcm_pm_firmware_load_method_t[] =
{
    { "bcmpmFirmwareLoadMethodNone", bcmpmFirmwareLoadMethodNone },
    { "bcmpmFirmwareLoadMethodInternal", bcmpmFirmwareLoadMethodInternal },
    { "bcmpmFirmwareLoadMethodExternal", bcmpmFirmwareLoadMethodExternal },
    { "bcmpmFirmwareLoadMethodProgEEPROM", bcmpmFirmwareLoadMethodProgEEPROM },
    { "bcmpmFirmwareLoadMethodCount", bcmpmFirmwareLoadMethodCount },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__bcm_pm_reset_direction_t[] =
{
    { "bcmpmResetDirectionIn", bcmpmResetDirectionIn },
    { "bcmpmResetDirectionOut", bcmpmResetDirectionOut },
    { "bcmpmResetDirectionInOut", bcmpmResetDirectionInOut },
    { "bcmpmResetDirectionCount", bcmpmResetDirectionCount },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__bcm_firmware_mode_t[] =
{
    { "bcm_pm_fw_default", bcm_pm_fw_default },
    { "bcm_pm_fw_dfe", bcm_pm_fw_dfe },
    { "bcm_pm_fw_osdfe", bcm_pm_fw_osdfe },
    { "bcm_pm_fw_br_dfe", bcm_pm_fw_br_dfe },
    { "bcm_pm_fw_lp_dfe", bcm_pm_fw_lp_dfe },
    { "bcm_pm_fw_sfp_dac", bcm_pm_fw_sfp_dac },
    { "bcm_pm_fw_xlaui", bcm_pm_fw_xlaui },
    { "bcm_pm_fw_sfp_opt_sr4", bcm_pm_fw_sfp_opt_sr4 },
    { "bcm_pm_fw_Count", bcm_pm_fw_Count },
    { NULL }
};


static cint_enum_type_t __cint_enums[] =
{
    {"bcm_pm_interface_t", __cint_enum_map__bcm_pm_interface_t },
    {"bcm_pm_ref_clk_t", __cint_enum_map__bcm_pm_ref_clk_t },
    {"bcm_pm_interface_mode_t", __cint_enum_map__bcm_pm_interface_mode_t },
    {"bcm_pm_if_side_t", __cint_enum_map__bcm_pm_if_side_t },
    {"bcm_pm_prbs_tx_rx_t", __cint_enum_map__bcm_pm_prbs_tx_rx_t },
    {"bcm_pm_prbs_poly_t", __cint_enum_map__bcm_pm_prbs_poly_t },
    {"bcm_pm_osr_mode_t", __cint_enum_map__bcm_pm_osr_mode_t },
    {"bcm_pm_pmd_mode_t", __cint_enum_map__bcm_pm_pmd_mode_t },
    {"bcm_pm_sequencer_operation_t", __cint_enum_map__bcm_pm_sequencer_operation_t },
    {"bcm_pm_phy_tx_lane_control_t", __cint_enum_map__bcm_pm_phy_tx_lane_control_t },
    {"bcm_pm_phy_rx_lane_control_t", __cint_enum_map__bcm_pm_phy_rx_lane_control_t },
    {"bcm_pm_firmware_load_method_t", __cint_enum_map__bcm_pm_firmware_load_method_t },
    {"bcm_pm_reset_direction_t", __cint_enum_map__bcm_pm_reset_direction_t },
    {"bcm_firmware_mode_t", __cint_enum_map__bcm_firmware_mode_t },
    { NULL }
};

/* Defines section */
static cint_constants_t __cint_constants[] =
{
    { NULL }
};


/* Typedefs section */
static cint_parameter_desc_t __cint_typedefs[] =
{
    { NULL }
};


cint_data_t phymod_epil_apis_cint_data =
{    
    NULL,
    __cint_functions,
    __cint_structures,
    __cint_enums,
    __cint_typedefs,
    __cint_constants,
    __cint_function_pointers,
};


#endif /* defined(PHYMOD_EPIL_APIS_SUPPORT) */

#endif /* defined(INCLUDE_LIB_CINT) */
