
/**
 *
 * $Id: ocm_cint.stg,v 1.3 Broadcom SDK $ 	 
 * $Copyright: (c) 2016 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from $SDK/caladan_ucode/t3p1/src/t3p1_ocm_cfg.lrp
 * Edits to this file will be lost when it is regenerated.
 */
 
int t3p1_ocm_cint_data_not_empty;
#include <sdk_config.h>
#if defined(INCLUDE_LIB_CINT)
#if defined(BCM_CALADAN3_SUPPORT) && defined(BCM_CALADAN3_T3P1_SUPPORT)

#include <cint_config.h>
#include <cint_types.h>
#include <cint_porting.h>
#include <sal/core/libc.h>

#include <soc/sbx/t3p1/t3p1_int.h>
#define UTG_MALLOC(x) sal_alloc((x), "utg");

  /*
   * Constant HTYPE_NULL access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_null_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_NULL access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_null_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_ETYPE access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_etype_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_ETYPE access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_etype_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_ETH access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_eth_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_ETH access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_eth_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_IETH access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_ieth_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_LLC access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_llc_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_LLC access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_llc_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_SNAP access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_snap_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_SNAP access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_snap_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_VTAG access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_vtag_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_VTAG access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_vtag_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_DVTAG access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_dvtag_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_MPLS access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_mpls_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_MPLS access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_mpls_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_IPV4 access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_ipv4_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_IPV4 access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_ipv4_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_IPV6 access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_ipv6_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_IPV6 access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_ipv6_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_UDP access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_udp_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_UDP access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_udp_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_TCP access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_tcp_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_TCP access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_tcp_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_ACH access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_ach_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_ACH access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_ach_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_PTP access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_ptp_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_PTP access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_ptp_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_MIM access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_mim_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_MIM access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_mim_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_ELEN access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_elen_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_ELEN access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_elen_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_ERH access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_erh_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_ERH access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_erh_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_TMH access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_tmh_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_TMH access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_tmh_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_KSOP access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_ksop_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_KSOP access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_ksop_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_CUSTOM access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_custom_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HLEN_CUSTOM access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_hlen_custom_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
  /*
   * Constant HTYPE_UNKN access method
   */
  CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_htype_unkn_get,
                           int, int, unit, 0, 0,
                           uint32*, uint32, vp, 1, 0);  
/*
 * Global CONTEXTS access methods
 */
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_contexts_set,
                         int, int, unit, 0, 0,
                         uint32, uint32, v, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_contexts_get,
                         int, int, unit, 0, 0,
                         uint32*, uint32, vp, 1, 0);  
/*
 * Global DEBUG_STREAM_ELEN access methods
 */
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_debug_stream_elen_set,
                         int, int, unit, 0, 0,
                         uint32, uint32, v, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_debug_stream_elen_get,
                         int, int, unit, 0, 0,
                         uint32*, uint32, vp, 1, 0);  
/*
 * Global C3_SWS_STATIC_PAGE access methods
 */
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_c3_sws_static_page_set,
                         int, int, unit, 0, 0,
                         uint32, uint32, v, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_c3_sws_static_page_get,
                         int, int, unit, 0, 0,
                         uint32*, uint32, vp, 1, 0);  
/*
 * Global C3_SWS_INGRESS_BUBBLE_SQUEUE access methods
 */
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_c3_sws_ingress_bubble_squeue_set,
                         int, int, unit, 0, 0,
                         uint32, uint32, v, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_c3_sws_ingress_bubble_squeue_get,
                         int, int, unit, 0, 0,
                         uint32*, uint32, vp, 1, 0);  
/*
 * Global C3_SWS_FAB_TO_LINE_REDIRECT_QID0 access methods
 */
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_c3_sws_fab_to_line_redirect_qid0_set,
                         int, int, unit, 0, 0,
                         uint32, uint32, v, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_c3_sws_fab_to_line_redirect_qid0_get,
                         int, int, unit, 0, 0,
                         uint32*, uint32, vp, 1, 0);  
/*
 * Global C3_SWS_FAB_TO_LINE_REDIRECT_QID1 access methods
 */
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_c3_sws_fab_to_line_redirect_qid1_set,
                         int, int, unit, 0, 0,
                         uint32, uint32, v, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_c3_sws_fab_to_line_redirect_qid1_get,
                         int, int, unit, 0, 0,
                         uint32*, uint32, vp, 1, 0);  
/*
 * Global C3_SWS_EGRESS_BUBBLE_SQUEUE access methods
 */
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_c3_sws_egress_bubble_squeue_set,
                         int, int, unit, 0, 0,
                         uint32, uint32, v, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_c3_sws_egress_bubble_squeue_get,
                         int, int, unit, 0, 0,
                         uint32*, uint32, vp, 1, 0);  
/*
 * Global C3_SWS_LINE_TO_FAB_REDIRECT_QID0 access methods
 */
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_c3_sws_line_to_fab_redirect_qid0_set,
                         int, int, unit, 0, 0,
                         uint32, uint32, v, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_c3_sws_line_to_fab_redirect_qid0_get,
                         int, int, unit, 0, 0,
                         uint32*, uint32, vp, 1, 0);  
/*
 * Global C3_SWS_LINE_TO_FAB_REDIRECT_QID1 access methods
 */
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_c3_sws_line_to_fab_redirect_qid1_set,
                         int, int, unit, 0, 0,
                         uint32, uint32, v, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_c3_sws_line_to_fab_redirect_qid1_get,
                         int, int, unit, 0, 0,
                         uint32*, uint32, vp, 1, 0);  
/*
 * Global INGRESS_REPLICATION_COUNT access methods
 */
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_ingress_replication_count_set,
                         int, int, unit, 0, 0,
                         uint32, uint32, v, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_ingress_replication_count_get,
                         int, int, unit, 0, 0,
                         uint32*, uint32, vp, 1, 0);  
/*
 * Global EGRESS_REPLICATION_COUNT access methods
 */
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_egress_replication_count_set,
                         int, int, unit, 0, 0,
                         uint32, uint32, v, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_egress_replication_count_get,
                         int, int, unit, 0, 0,
                         uint32*, uint32, vp, 1, 0);  
/*
 * Global FLUSH_PORT access methods
 */
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_flush_port_set,
                         int, int, unit, 0, 0,
                         uint32, uint32, v, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_flush_port_get,
                         int, int, unit, 0, 0,
                         uint32*, uint32, vp, 1, 0);  
/*
 * Global MAC_LIMIT access methods
 */
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_mac_limit_set,
                         int, int, unit, 0, 0,
                         uint32, uint32, v, 0, 0);
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0, soc_sbx_t3p1_mac_limit_get,
                         int, int, unit, 0, 0,
                         uint32*, uint32, vp, 1, 0);  
 

/*
 * Table entry accessors
 */
/*
 * Entry accessor implementations for lag
 */
CINT_FWRAPPER_CREATE_VP1(soc_sbx_t3p1_lag_t_init, soc_sbx_t3p1_lag_t*,  soc_sbx_t3p1_lag_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_lag_entry_table_size_get,
                                    int, int, unit, 0, 0, 
                                    int*, int, size, 1, 0,
                                      int, int, ilagi, 0, 0  ); 
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_lag_set,
                                    int, int, unit, 0, 0, 
                                      int, int, ilagi, 0, 0  ,
                                    soc_sbx_t3p1_lag_t*, soc_sbx_t3p1_lag_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_lag_get,
                                    int, int, unit, 0, 0, 
                                      int, int, ilagi, 0, 0  ,
                                    soc_sbx_t3p1_lag_t*, soc_sbx_t3p1_lag_t, e, 1, 0);                                    

                                                
/*
 * Struct soc_sbx_t3p1_lag_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_t3p1_lag_t[] = 
{
      {
         "uint32",
         "qid",
         0,
         0
      },
      {
         "uint32",
         "oi",
         0,
         0
      },
  { NULL }
};         

/*
 * Struct soc_sbx_t3p1_lag_t
 */
 static void*
__cint_maddr__soc_sbx_t3p1_lag_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_t3p1_lag_t* s = (soc_sbx_t3p1_lag_t*) p;

    switch (mnum) {
      case 0: rv = &(s->qid); break;
      case 1: rv = &(s->oi); break;
      default: rv = NULL; break;
    }

    return rv;
}
 

          
/*
 * Entry accessor implementations for vlan
 */
CINT_FWRAPPER_CREATE_VP1(soc_sbx_t3p1_vlan_t_init, soc_sbx_t3p1_vlan_t*,  soc_sbx_t3p1_vlan_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_vlan_entry_table_size_get,
                                    int, int, unit, 0, 0, 
                                    int*, int, size, 1, 0,
                                      int, int, ivlan, 0, 0  ); 
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_vlan_set,
                                    int, int, unit, 0, 0, 
                                      int, int, ivlan, 0, 0  ,
                                    soc_sbx_t3p1_vlan_t*, soc_sbx_t3p1_vlan_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_vlan_get,
                                    int, int, unit, 0, 0, 
                                      int, int, ivlan, 0, 0  ,
                                    soc_sbx_t3p1_vlan_t*, soc_sbx_t3p1_vlan_t, e, 1, 0);                                    

                                                
/*
 * Struct soc_sbx_t3p1_vlan_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_t3p1_vlan_t[] = 
{
      {
         "uint32",
         "qid",
         0,
         0
      },
      {
         "uint32",
         "oi",
         0,
         0
      },
  { NULL }
};         

/*
 * Struct soc_sbx_t3p1_vlan_t
 */
 static void*
__cint_maddr__soc_sbx_t3p1_vlan_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_t3p1_vlan_t* s = (soc_sbx_t3p1_vlan_t*) p;

    switch (mnum) {
      case 0: rv = &(s->qid); break;
      case 1: rv = &(s->oi); break;
      default: rv = NULL; break;
    }

    return rv;
}
 

          
/*
 * Entry accessor implementations for irt
 */
CINT_FWRAPPER_CREATE_VP1(soc_sbx_t3p1_irt_t_init, soc_sbx_t3p1_irt_t*,  soc_sbx_t3p1_irt_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_irt_entry_table_size_get,
                                    int, int, unit, 0, 0, 
                                    int*, int, size, 1, 0,
                                      int, int, iirule, 0, 0  ); 
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_irt_set,
                                    int, int, unit, 0, 0, 
                                      int, int, iirule, 0, 0  ,
                                    soc_sbx_t3p1_irt_t*, soc_sbx_t3p1_irt_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_irt_get,
                                    int, int, unit, 0, 0, 
                                      int, int, iirule, 0, 0  ,
                                    soc_sbx_t3p1_irt_t*, soc_sbx_t3p1_irt_t, e, 1, 0);                                    

                                                
/*
 * Struct soc_sbx_t3p1_irt_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_t3p1_irt_t[] = 
{
      {
         "uint32",
         "vlan",
         0,
         0
      },
      {
         "uint32",
         "ftidx",
         0,
         0
      },
      {
         "uint32",
         "mirror",
         0,
         0
      },
      {
         "uint32",
         "usevlan",
         0,
         0
      },
      {
         "uint32",
         "useftidx",
         0,
         0
      },
      {
         "uint32",
         "copy",
         0,
         0
      },
      {
         "uint32",
         "dp",
         0,
         0
      },
      {
         "uint32",
         "cos",
         0,
         0
      },
      {
         "uint32",
         "fcos",
         0,
         0
      },
      {
         "uint32",
         "usedp",
         0,
         0
      },
      {
         "uint32",
         "usecos",
         0,
         0
      },
      {
         "uint32",
         "policer",
         0,
         0
      },
      {
         "uint32",
         "typedpolice",
         0,
         0
      },
      {
         "uint32",
         "mefcos",
         0,
         0
      },
      {
         "uint32",
         "mef",
         0,
         0
      },
  { NULL }
};         

/*
 * Struct soc_sbx_t3p1_irt_t
 */
 static void*
__cint_maddr__soc_sbx_t3p1_irt_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_t3p1_irt_t* s = (soc_sbx_t3p1_irt_t*) p;

    switch (mnum) {
      case 0: rv = &(s->vlan); break;
      case 1: rv = &(s->ftidx); break;
      case 2: rv = &(s->mirror); break;
      case 3: rv = &(s->usevlan); break;
      case 4: rv = &(s->useftidx); break;
      case 5: rv = &(s->copy); break;
      case 6: rv = &(s->dp); break;
      case 7: rv = &(s->cos); break;
      case 8: rv = &(s->fcos); break;
      case 9: rv = &(s->usedp); break;
      case 10: rv = &(s->usecos); break;
      case 11: rv = &(s->policer); break;
      case 12: rv = &(s->typedpolice); break;
      case 13: rv = &(s->mefcos); break;
      case 14: rv = &(s->mef); break;
      default: rv = NULL; break;
    }

    return rv;
}
 

          
/*
 * Entry accessor implementations for oam_bubble
 */
CINT_FWRAPPER_CREATE_VP1(soc_sbx_t3p1_oam_bubble_t_init, soc_sbx_t3p1_oam_bubble_t*,  soc_sbx_t3p1_oam_bubble_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_oam_bubble_entry_table_size_get,
                                    int, int, unit, 0, 0, 
                                    int*, int, size, 1, 0,
                                      int, int, ioamepi, 0, 0  ); 
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_oam_bubble_set,
                                    int, int, unit, 0, 0, 
                                      int, int, ioamepi, 0, 0  ,
                                    soc_sbx_t3p1_oam_bubble_t*, soc_sbx_t3p1_oam_bubble_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_oam_bubble_get,
                                    int, int, unit, 0, 0, 
                                      int, int, ioamepi, 0, 0  ,
                                    soc_sbx_t3p1_oam_bubble_t*, soc_sbx_t3p1_oam_bubble_t, e, 1, 0);                                    

                                                
/*
 * Struct soc_sbx_t3p1_oam_bubble_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_t3p1_oam_bubble_t[] = 
{
      {
         "uint32",
         "bubble_mode",
         0,
         0
      },
      {
         "uint32",
         "je",
         0,
         0
      },
      {
         "uint32",
         "i",
         0,
         0
      },
      {
         "uint32",
         "bubble_stream",
         0,
         0
      },
      {
         "uint32",
         "t",
         0,
         0
      },
      {
         "uint32",
         "interval_index",
         0,
         0
      },
      {
         "uint32",
         "reserved",
         0,
         0
      },
      {
         "uint32",
         "count",
         0,
         0
      },
      {
         "uint32",
         "timeout",
         0,
         0
      },
  { NULL }
};         

/*
 * Struct soc_sbx_t3p1_oam_bubble_t
 */
 static void*
__cint_maddr__soc_sbx_t3p1_oam_bubble_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_t3p1_oam_bubble_t* s = (soc_sbx_t3p1_oam_bubble_t*) p;

    switch (mnum) {
      case 0: rv = &(s->bubble_mode); break;
      case 1: rv = &(s->je); break;
      case 2: rv = &(s->i); break;
      case 3: rv = &(s->bubble_stream); break;
      case 4: rv = &(s->t); break;
      case 5: rv = &(s->interval_index); break;
      case 6: rv = &(s->reserved); break;
      case 7: rv = &(s->count); break;
      case 8: rv = &(s->timeout); break;
      default: rv = NULL; break;
    }

    return rv;
}
 

          
/*
 * Entry accessor implementations for demoage
 */
CINT_FWRAPPER_CREATE_VP1(soc_sbx_t3p1_demoage_t_init, soc_sbx_t3p1_demoage_t*,  soc_sbx_t3p1_demoage_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_demoage_entry_table_size_get,
                                    int, int, unit, 0, 0, 
                                    int*, int, size, 1, 0,
                                      int, int, imacindex, 0, 0  ); 
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_demoage_set,
                                    int, int, unit, 0, 0, 
                                      int, int, imacindex, 0, 0  ,
                                    soc_sbx_t3p1_demoage_t*, soc_sbx_t3p1_demoage_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_demoage_get,
                                    int, int, unit, 0, 0, 
                                      int, int, imacindex, 0, 0  ,
                                    soc_sbx_t3p1_demoage_t*, soc_sbx_t3p1_demoage_t, e, 1, 0);                                    

                                                
/*
 * Struct soc_sbx_t3p1_demoage_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_t3p1_demoage_t[] = 
{
      {
         "uint32",
         "age",
         0,
         0
      },
      {
         "uint32",
         "age_valid",
         0,
         0
      },
  { NULL }
};         

/*
 * Struct soc_sbx_t3p1_demoage_t
 */
 static void*
__cint_maddr__soc_sbx_t3p1_demoage_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_t3p1_demoage_t* s = (soc_sbx_t3p1_demoage_t*) p;

    switch (mnum) {
      case 0: rv = &(s->age); break;
      case 1: rv = &(s->age_valid); break;
      default: rv = NULL; break;
    }

    return rv;
}
 

          
/*
 * Entry accessor implementations for demoageid
 */
CINT_FWRAPPER_CREATE_VP1(soc_sbx_t3p1_demoageid_t_init, soc_sbx_t3p1_demoageid_t*,  soc_sbx_t3p1_demoageid_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_demoageid_entry_table_size_get,
                                    int, int, unit, 0, 0, 
                                    int*, int, size, 1, 0,
                                      int, int, imacindex, 0, 0  ); 
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_demoageid_set,
                                    int, int, unit, 0, 0, 
                                      int, int, imacindex, 0, 0  ,
                                    soc_sbx_t3p1_demoageid_t*, soc_sbx_t3p1_demoageid_t, e, 1, 0);
CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0, soc_sbx_t3p1_demoageid_get,
                                    int, int, unit, 0, 0, 
                                      int, int, imacindex, 0, 0  ,
                                    soc_sbx_t3p1_demoageid_t*, soc_sbx_t3p1_demoageid_t, e, 1, 0);                                    

                                                
/*
 * Struct soc_sbx_t3p1_demoageid_t parameter description
 */
static cint_parameter_desc_t __cint_struct_members__soc_sbx_t3p1_demoageid_t[] = 
{
      {
         "uint32",
         "age_id",
         0,
         0
      },
  { NULL }
};         

/*
 * Struct soc_sbx_t3p1_demoageid_t
 */
 static void*
__cint_maddr__soc_sbx_t3p1_demoageid_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    soc_sbx_t3p1_demoageid_t* s = (soc_sbx_t3p1_demoageid_t*) p;

    switch (mnum) {
      case 0: rv = &(s->age_id); break;
      default: rv = NULL; break;
    }

    return rv;
}
 

          










/*
 * struct type table
 */ 
static cint_struct_type_t __cint_t3p1_structures [] = 
{
    {
          "soc_sbx_t3p1_lag_t",
          sizeof(soc_sbx_t3p1_lag_t),
          __cint_struct_members__soc_sbx_t3p1_lag_t,
          __cint_maddr__soc_sbx_t3p1_lag_t
    },
    {
          "soc_sbx_t3p1_vlan_t",
          sizeof(soc_sbx_t3p1_vlan_t),
          __cint_struct_members__soc_sbx_t3p1_vlan_t,
          __cint_maddr__soc_sbx_t3p1_vlan_t
    },
    {
          "soc_sbx_t3p1_irt_t",
          sizeof(soc_sbx_t3p1_irt_t),
          __cint_struct_members__soc_sbx_t3p1_irt_t,
          __cint_maddr__soc_sbx_t3p1_irt_t
    },
    {
          "soc_sbx_t3p1_oam_bubble_t",
          sizeof(soc_sbx_t3p1_oam_bubble_t),
          __cint_struct_members__soc_sbx_t3p1_oam_bubble_t,
          __cint_maddr__soc_sbx_t3p1_oam_bubble_t
    },
    {
          "soc_sbx_t3p1_demoage_t",
          sizeof(soc_sbx_t3p1_demoage_t),
          __cint_struct_members__soc_sbx_t3p1_demoage_t,
          __cint_maddr__soc_sbx_t3p1_demoage_t
    },
    {
          "soc_sbx_t3p1_demoageid_t",
          sizeof(soc_sbx_t3p1_demoageid_t),
          __cint_struct_members__soc_sbx_t3p1_demoageid_t,
          __cint_maddr__soc_sbx_t3p1_demoageid_t
    },
  { NULL }
};
 

/*
 * Function table
 */
static cint_function_t __cint_t3p1_functions [] =
{           
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_null_get), /* Const htype_null */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_null_get), /* Const hlen_null */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_etype_get), /* Const htype_etype */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_etype_get), /* Const hlen_etype */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_eth_get), /* Const htype_eth */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_eth_get), /* Const hlen_eth */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_ieth_get), /* Const htype_ieth */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_llc_get), /* Const htype_llc */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_llc_get), /* Const hlen_llc */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_snap_get), /* Const htype_snap */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_snap_get), /* Const hlen_snap */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_vtag_get), /* Const htype_vtag */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_vtag_get), /* Const hlen_vtag */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_dvtag_get), /* Const htype_dvtag */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_mpls_get), /* Const htype_mpls */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_mpls_get), /* Const hlen_mpls */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_ipv4_get), /* Const htype_ipv4 */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_ipv4_get), /* Const hlen_ipv4 */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_ipv6_get), /* Const htype_ipv6 */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_ipv6_get), /* Const hlen_ipv6 */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_udp_get), /* Const htype_udp */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_udp_get), /* Const hlen_udp */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_tcp_get), /* Const htype_tcp */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_tcp_get), /* Const hlen_tcp */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_ach_get), /* Const htype_ach */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_ach_get), /* Const hlen_ach */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_ptp_get), /* Const htype_ptp */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_ptp_get), /* Const hlen_ptp */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_mim_get), /* Const htype_mim */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_mim_get), /* Const hlen_mim */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_elen_get), /* Const htype_elen */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_elen_get), /* Const hlen_elen */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_erh_get), /* Const htype_erh */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_erh_get), /* Const hlen_erh */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_tmh_get), /* Const htype_tmh */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_tmh_get), /* Const hlen_tmh */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_ksop_get), /* Const htype_ksop */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_ksop_get), /* Const hlen_ksop */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_custom_get), /* Const htype_custom */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_hlen_custom_get), /* Const hlen_custom */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_htype_unkn_get), /* Const htype_unkn */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_contexts_set), /* Global contexts */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_contexts_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_debug_stream_elen_set), /* Global debug_stream_elen */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_debug_stream_elen_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_c3_sws_static_page_set), /* Global c3_sws_static_page */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_c3_sws_static_page_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_c3_sws_ingress_bubble_squeue_set), /* Global c3_sws_ingress_bubble_squeue */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_c3_sws_ingress_bubble_squeue_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_c3_sws_fab_to_line_redirect_qid0_set), /* Global c3_sws_fab_to_line_redirect_qid0 */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_c3_sws_fab_to_line_redirect_qid0_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_c3_sws_fab_to_line_redirect_qid1_set), /* Global c3_sws_fab_to_line_redirect_qid1 */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_c3_sws_fab_to_line_redirect_qid1_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_c3_sws_egress_bubble_squeue_set), /* Global c3_sws_egress_bubble_squeue */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_c3_sws_egress_bubble_squeue_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_c3_sws_line_to_fab_redirect_qid0_set), /* Global c3_sws_line_to_fab_redirect_qid0 */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_c3_sws_line_to_fab_redirect_qid0_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_c3_sws_line_to_fab_redirect_qid1_set), /* Global c3_sws_line_to_fab_redirect_qid1 */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_c3_sws_line_to_fab_redirect_qid1_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_ingress_replication_count_set), /* Global ingress_replication_count */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_ingress_replication_count_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_egress_replication_count_set), /* Global egress_replication_count */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_egress_replication_count_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_flush_port_set), /* Global flush_port */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_flush_port_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_mac_limit_set), /* Global mac_limit */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_mac_limit_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_lag_t_init), /* Table lag */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_lag_entry_table_size_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_lag_set),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_lag_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_vlan_t_init), /* Table vlan */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_vlan_entry_table_size_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_vlan_set),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_vlan_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_irt_t_init), /* Table irt */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_irt_entry_table_size_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_irt_set),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_irt_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_oam_bubble_t_init), /* Table oam_bubble */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_oam_bubble_entry_table_size_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_oam_bubble_set),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_oam_bubble_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_demoage_t_init), /* Table demoage */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_demoage_entry_table_size_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_demoage_set),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_demoage_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_demoageid_t_init), /* Table demoageid */
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_demoageid_entry_table_size_get),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_demoageid_set),
    CINT_FWRAPPER_ENTRY(soc_sbx_t3p1_demoageid_get),
  { NULL }
};    


/* 
 * CINT exported datastructure
 */ 
cint_data_t t3p1_ocm_cint_data =
{
    NULL,
    __cint_t3p1_functions,
    __cint_t3p1_structures,
    NULL,   /* __cint_t3p1_enums */
    NULL,   /* __cint_t3p1_typedefs */
    NULL,   /* __cint_t3p1_constants */
    NULL,   /* __cint_t3p1_function_pointers */
};

#endif
#endif
