/*
 * $Id:dnxf_config_defs.csv,v 1.1.2.5 Broadcom SDK $
 * 
 * $Copyright: (c) 2016 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 * This file is auto-generated by autoCoder
 * DO NOT EDIT THIS FILE!
 *
 */

#include <shared/bsl.h>
#include <soc/defs.h>
#ifdef BCM_88790_A0

#include <soc/dnxf/cmn/dnxf_config_defs.h>
#include <soc/dcmn/dcmn_defs.h>
#include <soc/dnxf/fe1600/fe1600_interrupts.h>
#include <soc/dnxf/fe1600/fe1600_config_defs.h>

#ifdef _ERR_MSG_MODULE_NAME
    #error "_ERR_MSG_MODULE_NAME redefined"
#endif /* _ERR_MSG_MODULE_NAME */

#define _ERR_MSG_MODULE_NAME BSL_SOC_INIT

CONST soc_dnxf_defines_t soc_ramon_fe1600_defines= {
    SOC_RAMON_FE1600_NOF_LINKS,
    SOC_RAMON_FE1600_NOF_INSTANCES_MAC,
    SOC_RAMON_FE1600_NOF_LINKS_IN_MAC,
    SOC_RAMON_FE1600_NOF_INSTANCES_MAC_FSRD,
    SOC_RAMON_FE1600_NOF_INSTANCES_BRDC_FSRD,
    SOC_RAMON_FE1600_NOF_LINKS_IN_FSRD,
    SOC_RAMON_FE1600_NOF_QUADS_IN_FSRD,
    SOC_RAMON_FE1600_NOF_LINKS_IN_QUAD,
    SOC_RAMON_FE1600_NOF_INSTANCES_DCH,
    SOC_RAMON_FE1600_NOF_INSTANCES_CCS,
    SOC_RAMON_FE1600_NOF_LINKS_IN_CCS,
    SOC_RAMON_FE1600_NOF_INSTANCES_DCL,
    SOC_RAMON_FE1600_NOF_LINKS_IN_DCQ,
    SOC_RAMON_FE1600_NOF_INSTANCES_RTP,
    SOC_RAMON_FE1600_NOF_INSTANCES_OCCG,
    SOC_RAMON_FE1600_NOF_INSTANCES_ECI,
    SOC_RAMON_FE1600_NOF_INSTANCES_DCMA,
    SOC_RAMON_FE1600_NOF_INSTANCES_DCMB,
    SOC_RAMON_FE1600_NOF_INSTANCES_DCMC,
    SOC_RAMON_FE1600_NOF_INSTANCES_DCM,
    SOC_RAMON_FE1600_NOF_INSTANCES_CMIC,
    SOC_RAMON_FE1600_NOF_INSTANCES_MESH_TOPOLOGY,
    SOC_RAMON_FE1600_NOF_INSTANCES_OTPC,
    SOC_RAMON_FE1600_NOF_INSTANCES_BRDC_FMACH,
    SOC_RAMON_FE1600_NOF_INSTANCES_BRDC_FMACL,
    SOC_RAMON_FE1600_NOF_INSTANCES_BRDC_FMAC_AC,
    SOC_RAMON_FE1600_NOF_INSTANCES_BRDC_FMAC_BD,
    SOC_RAMON_FE1600_NOF_INSTANCES_BRDC_DCH,
    SOC_RAMON_FE1600_NOF_INSTANCES_BRDC_DCM,
    SOC_RAMON_FE1600_NOF_INSTANCES_BRDC_DCL,
    SOC_RAMON_FE1600_NOF_INSTANCES_BRDC_CCS,
    SOC_RAMON_FE1600_MAX_LINK_SCORE,
    SOC_RAMON_FE1600_MULTICAST_ROW_SIZE_IN_UINT32,
    SOC_RAMON_FE1600_MAX_BUCKET_FILL_RATE,
    SOC_RAMON_FE1600_RTP_RMHMT_GROUP_SIZE,
    SOC_RAMON_FE1600_NOF_LCPLL,
    SOC_RAMON_FE1600_NOF_PORT_IN_LCPLL,
    SOC_RAMON_FE1600_RTP_RMGR_UNITS,
    SOC_RAMON_FE1600_RTP_RMGR_NOF_LINKS,
    SOC_RAMON_FE1600_NOF_INTERRUPTS,
    SOC_RAMON_FE1600_NOF_RTP_MCLBTP_INSTANCES,
    SOC_RAMON_FE1600_NOF_RTP_MCLBTS_INSTANCES,
    SOC_RAMON_FE1600_NOF_LINKS_IN_DCL,
    SOC_RAMON_FE1600_FIFO_DMA_FABRIC_CELL_FIRST_CHANNEL,
    SOC_RAMON_FE1600_FIFO_DMA_NOF_FABRIC_CELL_CHANNELS,
    SOC_RAMON_FE1600_FIFO_DMA_FABRIC_CELL_NOF_ENTRIES_PER_CELL,
    SOC_RAMON_FE1600_REPEATER_NONE_EMPTY_CELL_SIZE,
    SOC_RAMON_FE1600_REPEATER_DEFAULT_EMPTY_CELL_SIZE,
    SOC_RAMON_FE1600_NOF_LOCAL_MODID,
    SOC_RAMON_FE1600_NOF_LOCAL_MODID_FE13,
    SOC_RAMON_FE1600_FABRIC_MAC_BUS_SIZE,
    SOC_RAMON_FE1600_LINK_MASK,
    SOC_RAMON_FE1600_RX_CPU_CELL_MAX_PAYLOAD_SIZE,
    SOC_RAMON_FE1600_SOURCE_ROUTED_CELLS_HEADER_OFFSET,
    SOC_RAMON_FE1600_ALDWP_MAX_VAL,
};

/* defines struct init func for ramon_fe1600 */
int soc_ramon_fe1600_defines_init(int unit)
{
    SOCDNX_INIT_FUNC_DEFS;

    if ( soc_dnxf_defines[unit] == NULL ) {
        soc_dnxf_defines[unit] = (soc_dnxf_defines_t *) sal_alloc(sizeof(soc_dnxf_defines_t),"Defines struct");
        if ( soc_dnxf_defines[unit] == NULL ) {
            SOCDNX_EXIT_WITH_ERR(SOC_E_MEMORY, (_BSL_SOCDNX_MSG("Failed to allocate memory for configuration defines struct")));
        }
    }
        sal_memcpy(soc_dnxf_defines[unit], &soc_ramon_fe1600_defines, sizeof(soc_dnxf_defines_t));

exit:
    SOCDNX_FUNC_RETURN;
}

/* defines struct deinit func for ramon_fe1600 */
int soc_ramon_fe1600_defines_deinit(int unit)
{
    if ( soc_dnxf_defines[unit] != NULL ) {
        sal_free(soc_dnxf_defines[unit]);
        soc_dnxf_defines[unit] = NULL;
    }

    return SOC_E_NONE;
}

/**************************************/
/*  Operation mode specific logic    */
/**************************************/

#endif /* BCM_88790_A0 */
