# -*- Makefile -*-
# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM PCRE library
#

LOCALDIR = src/bcm/esw/regex

include ${SDK}/make/Make.config

lib = libbcm_regex
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
