#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# $Id: Makefile,v 1.4 Broadcom SDK $
LOCALDIR = src/appl/diag/portmod

include ${SDK}/make/Make.config

lib = libdiag_portmod

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
