# $Id$
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for Apache SOC driver Library
#

LOCALDIR = src/soc/esw/tdm/apache/

include ${SDK}/make/Make.config

lib = libsoc_tdm_apache

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

