#
# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for phy/phy8806x/src subdirectory
#
LOCALDIR = src/soc/phy/phy8806x/src

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/src/soc/phy/phy8806x/include

lib = libsoc_phy8806x
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
