# $Id$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$

PLATFORM=m32

include ${SDK}/make/Make.config


lib = libsoc_kbp_nlm2_rngmgr_refapp3

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

