# $Id: Makefile,v 1.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Build LED processor tools
# Build example code
#
.KEEP_STATE:

all:
	$(MAKE) -C tools all
	$(MAKE) -C example all

clean:
	$(MAKE) -C tools clean
	$(MAKE) -C example clean

clobber:
	$(MAKE) -C tools clobber
	$(MAKE) -C example clobber
