/*
 * $Copyright: (c) 2016 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *
 * THIS SOFTWARE IS OFFERED "AS IS", AND BROADCOM GRANTS NO WARRANTIES OF ANY
 * KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE.
 * BROADCOM SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A SPECIFIC PURPOSE OR NONINFRINGEMENT CONCERNING THIS SOFTWARE.
 *
 * $Id: tmu_config.h,v $
 *
 * TMU configuration defines
 *
 *-----------------------------------------------------------------------------*/
#ifndef _SBX_CALADN3_TMU_CONFIG_H_
#define _SBX_CALADN3_TMU_CONFIG_H_

#include <sal/appl/sal.h>

#define SOC_SBX_CALADAN3_TMU_TABLE_1X_REPLICATION (1)
#define SOC_SBX_CALADAN3_TMU_TABLE_2X_REPLICATION (2)
#define SOC_SBX_CALADAN3_TMU_TABLE_4X_REPLICATION (4)
#define SOC_SBX_CALADAN3_TMU_TABLE_DEF_REPLICATION (SOC_SBX_CALADAN3_TMU_TABLE_4X_REPLICATION)

#define SOC_SBX_CALADAN3_TMU_MAX_TABLE (64)
#define SOC_SBX_CALADAN3_TMU_MAX_CHAIN_TABLE (32) /* 0 - 31 */
#define SOC_SBX_CALADAN3_TMU_MIN_TABLE_NUM_ENTRIES (4096) /* 4K entries */
#define SOC_SBX_CALADAN3_TMU_TABLE_ENTRY_SIZE_UNITS (64) /* entires has to be multiple of 64bits */
#define SOC_SBX_CALADAN3_TMU_TABLE_ENTRY_SIZE_MIN (64) /* min entry size 64 bits */
#define SOC_SBX_CALADAN3_TMU_TABLE_ENTRY_SIZE_MAX (8*1024) /* max entry size 8K bits */

#define SOC_SBX_TMU_TABLE_FLAG_NONE         (0)
#define SOC_SBX_TMU_TABLE_FLAG_WITH_ID      (1)
#define SOC_SBX_TMU_TABLE_FLAG_CHAIN        (2)

#define SOC_SBX_CALADAN3_TMU_MAX_BMP        (512)
#define SOC_SBX_CALADAN3_TMU_MAX_BMP_WORDS  (SOC_SBX_CALADAN3_TMU_MAX_BMP/32)


typedef enum _soc_sbx_caladan3_tmu_lookup_e {
    SOC_SBX_TMU_LKUP_EML_64 = 0,
    SOC_SBX_TMU_LKUP_EML_144 = 1, /* EML144 share same lookup value as EML176 */
    SOC_SBX_TMU_LKUP_EML_176 = 1,
    SOC_SBX_TMU_LKUP_EML_304 = 2,
    SOC_SBX_TMU_LKUP_EML_424 = 3,
    SOC_SBX_TMU_LKUP_EML2ND_64 = 4,
    SOC_SBX_TMU_LKUP_EML2ND_144 = 5, /* EML144 share same lookup value as EML176 */
    SOC_SBX_TMU_LKUP_EML2ND_176 = 5,
    SOC_SBX_TMU_LKUP_EML2ND_304 = 6,
    SOC_SBX_TMU_LKUP_EML2ND_424 = 7,
    SOC_SBX_TMU_LKUP_EMC_64 = 8,
    SOC_SBX_TMU_LKUP_EMC2ND_64 = 9,
    SOC_SBX_TMU_LKUP_TAPS_IPV4_SUB_KEY = 12,
    SOC_SBX_TMU_LKUP_TAPS_IPV6_SUB_KEY = 13,
    SOC_SBX_TMU_LKUP_TAPS_IPV4_UNIFIED_KEY = 14,
    SOC_SBX_TMU_LKUP_TAPS_IPV6_UNIFIED_KEY = 15,
    SOC_SBX_TMU_LKUP_TAPS_IPV4_BUCKET = 16,
    SOC_SBX_TMU_LKUP_TAPS_IPV6_BUCKET = 17,
    SOC_SBX_TMU_LKUP_TAPS_IPV4_DATA = 18,
    SOC_SBX_TMU_LKUP_TAPS_IPV6_DATA = 19,
    SOC_SBX_TMU_LKUP_EML_INSERT_DELETE = 28,
    SOC_SBX_TMU_LKUP_DM_119 = 32,
    SOC_SBX_TMU_LKUP_DM_247 = 33,
    SOC_SBX_TMU_LKUP_DM_366 = 34,
    SOC_SBX_TMU_LKUP_DM_494 = 35,
    SOC_SBX_TMU_LKUP_NONE = 63 /* nothing */
} soc_sbx_caladan3_tmu_lookup_t; 


#endif /* _SBX_CALADN3_TMU_CONFIG_H_ */
