#
#   $Id: Makefile,v 1.2 Broadcom SDK $
# 
# 
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for ces/sal subdirectory
#
LOCALDIR = src/soc/ces/sal

CFLAGS = 
include ${SDK}/make/Make.config


lib = libsoc_sal
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
