# $Id: $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM Trident2 driver Library
#

LOCALDIR = src/bcm/esw/trident2

include ${SDK}/make/Make.config

lib = libtrident2

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
