#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/rx

include ${SDK}/make/Make.config

#subdirs = rx

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxrx

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

