# -*- Makefile -*-
# $Id: Makefile,v 1.11 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for StrataXGS SDK and diagnostics
#

include $(SDK)/make/Make.config

ifeq ($(HOSTTYPE),i386-linux)
subdirs= bmw jag nsx nsx64 raptor nsx-2_6 bmw-2_6 jag-2_6 raptor-2_6 nsx_wrl-2_6 gto-2_6
endif

include $(SDK)/make/Make.subdirs

include $(SDK)/make/Make.depend
