# $Id:  Exp $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for METROLITE SOC driver Library
#

LOCALDIR = src/soc/esw/metrolite

include ${SDK}/make/Make.config

lib = libsoc_metrolite

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

