# $Id: Makefile,v 1.5 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC SAL support (Linux Kernel)
#
LOCALDIR = src/sal/core/linux

include ${SDK}/make/Make.config

lib = libsal_core_plat
include ${SDK}/make/Make.kernlib

include ${SDK}/make/Make.depend
