# $Id:$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SDK board driver Library
#

LOCALDIR = src/board/driver

include ${SDK}/make/Make.config

lib = libboard_dvr
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
