# -*- Makefile -*-
# $Id: Makefile,v 1.2 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
LOCALDIR = systems/linux/kernel/modules/shared

include ${SDK}/make/Make.config

lib = libkern

include ${SDK}/make/Make.kernlib

include ${SDK}/make/Make.depend
