# $Id:  Exp $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for APACHE SOC driver Library
#

LOCALDIR = src/soc/esw/apache

include ${SDK}/make/Make.config

lib = libsoc_apache

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

