#
# $Id:$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# 
# Makefile for SOC shared subdirectory
#
LOCALDIR = src/soc/shared

include ${SDK}/make/Make.config

lib = libsoc_shared

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
