#
# $Id$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for dpp subdirectory
#

LOCALDIR = src/soc/dnxc/legacy

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libsoc_dnxclegacy

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

