# -*- Makefile -*-
# $Id: Makefile,v 1.2 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
LOCALDIR = systems/linux/kernel/user/shared

include ${SDK}/make/Make.config

CFLAGS += -I../../modules/include

lib = libuser

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
