
# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for common sbx driver Library
#

LOCALDIR = src/bcm/sbx/common

include ${SDK}/make/Make.config

lib = libsbxcommon

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
