#
# $Id: Makefile Exp $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/dpp/QAX/

include ${SDK}/make/Make.config

subdirs := QAX_PP


include ${SDK}/make/Make.subdirs

lib = libsoc_dpp_qax

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
