# -*- Makefile -*-
# $Id: $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM compat driver Library
#

LOCALDIR = src/bcm/compat

include ${SDK}/make/Make.config

lib = libbcm_compat
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
