#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# $Id: Makefile,v 1.11 Broadcom SDK $
LOCALDIR = src/appl/diag/dnx

include ${SDK}/make/Make.config

subdirs+= dbal
subdirs+= mdb
subdirs+= tx
subdirs+= init

lib = libdiag_dnx
include ${SDK}/make/Make.subdirs
include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
