# $Id: Makefile,v 1.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/esw/katana2

include ${SDK}/make/Make.config

lib = libkatana2

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
