# $Id: Makefile,v 1.23 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC driver Library
#
LOCALDIR = src/soc/dnxf/ramon

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libsoc_dnxframon

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
