#
#   $Id: Makefile,v 1.2 Broadcom SDK $
# 
# 
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for ces/clsbuilder subdirectory
#
LOCALDIR = src/soc/ces/clsbuilder
CFLAGS = 
include ${SDK}/make/Make.config
#CFLAGS += -fno-strict-aliasing

lib = libsoc_clsbuilder
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
 