# $Id: Makefile,v 1.3 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for PTP Common Library
#

LOCALDIR = src/bcm/common/ptp

include ${SDK}/make/Make.config

lib = libptp_common

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
