# $Id: Makefile,v 1.2 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for Access Control List (ACL) library.
#
LOCALDIR = src/appl/acl

include ${SDK}/make/Make.config

lib = libacl
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
