# $Id: Makefile,v 1.5 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
LOCALDIR = src/appl/diag/bcmx

include ${SDK}/make/Make.config

lib = libdiag_bcmx

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
