#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for dnx/dnx_data/jer2_a0 subdirectory
#

LOCALDIR = src/soc/dnx/dnx_data/jer2_a0

include ${SDK}/make/Make.config


include ${SDK}/make/Make.subdirs

lib = libsoc_dnxdnxdatajer2a0

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
