#
# $Id: Makefile,v 1.1.2.2 Broadcom SDK $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

include ${SDK}/make/Make.config

LOCALDIR = src/soc/kbp/common

INCDIR += -I$(SDK)/include/soc/kbp/common \
	-I$(SDK)/include \
	-I$(SDK)/include/sal/core \
	-I$(SDK)/include/sal/core/unix



lib = libsoc_kbp_cmn

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
