/*
 *         
 * $Id: phymod.xml,v 1.1.2.5 Broadcom SDK $
 * 
 * $Copyright: (c) 2016 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *         
 *     
 * DO NOT EDIT THIS FILE!
 *
 */

#include <phymod/phymod.h>
#include <phymod/phymod_diagnostics.h>
#include <phymod/phymod_diagnostics_dispatch.h>

#ifdef PHYMOD_QSGMIIE_SUPPORT

#include <phymod/chip/qsgmiie_diagnostics.h>


__phymod_diagnostics__dispatch__t__ phymod_diagnostics_qsgmiie_diagnostics_driver = {

    qsgmiie_phy_rx_slicer_position_set,
    qsgmiie_phy_rx_slicer_position_get,
    qsgmiie_phy_rx_slicer_position_max_get,
    qsgmiie_phy_prbs_config_set,
    qsgmiie_phy_prbs_config_get,
    qsgmiie_phy_prbs_enable_set,
    qsgmiie_phy_prbs_enable_get,
    qsgmiie_phy_prbs_status_get,
    qsgmiie_phy_pattern_config_set,
    qsgmiie_phy_pattern_config_get,
    qsgmiie_phy_pattern_enable_set,
    qsgmiie_phy_pattern_enable_get,
    qsgmiie_core_diagnostics_get,
    qsgmiie_phy_diagnostics_get,
    qsgmiie_phy_pmd_info_dump,
    NULL, /* phymod_phy_pcs_info_dump */
    NULL, /* phymod_phy_eyescan_run */
    NULL, /* phymod_phy_link_mon_enable_set */
    NULL, /* phymod_phy_link_mon_enable_get */
    NULL, /* phymod_phy_link_mon_status_get */
    NULL, /* phymod_phy_fec_correctable_counter_get */
    NULL, /* phymod_phy_fec_uncorrectable_counter_get */
};

#endif /* PHYMOD_QSGMIIE_SUPPORT */
