#
# $Id: Makefile Exp $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/dnx/legacy/JER2/

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libsoc_dnxlegacyjer2

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
