# $Id:$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/esw/xgs5

include ${SDK}/make/Make.config

lib = libxgs5

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
