# $Id: Makefile,v 1.97 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/shadow

export BCM_HIDE_DISPATCHABLE=1

include ${SDK}/make/Make.config
include ${SDK}/make/Make.subdirs

lib = libbcm_shadow
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
