#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/l3

include ${SDK}/make/Make.config

#subdirs = l3

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxl3

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

