
# $Id$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for sirius mbcm driver Library
#

LOCALDIR = src/bcm/sbx/sirius

include ${SDK}/make/Make.config

lib = libsirius

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
