# $Id: $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for SOC flexport common library

LOCALDIR = src/soc/esw/flexport

include ${SDK}/make/Make.config

lib = libsoc_flexport

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend


