# -*- Makefile -*-
# $Id: Makefile,v 1.10 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC SAL support
#
LOCALDIR = systems/linux/kernel/modules

include ${SDK}/make/Make.config

subdirs=shared uk-proxy bcm-diag-full bcm-core bcm-net bcm-diag

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.depend
