#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# $Id$
LOCALDIR = src/appl/diag/sbx

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/soc/sbx

CFLAGS += -O0

lib = libdiag_sbx

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
