# $Id: Makefile,v 1.1.8.2 Broadcom SDK $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for Greyhound SOC driver Library
#

LOCALDIR = src/soc/esw/greyhound

include ${SDK}/make/Make.config

lib = libsoc_greyhound

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

