# $Id: Makefile,v 1.3 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC SAL support (Unix)
#
LOCALDIR = src/sal/appl/linux

include ${SDK}/make/Make.config

lib = libsal_appl_plat
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
