# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for Tomahawk2 SOC driver Library
#

LOCALDIR = src/soc/esw/tomahawk2

include ${SDK}/make/Make.config

SUBDIR_TOMAHAWK2_FLEXPORT = flexport

subdirs := $(SUBDIR_TOMAHAWK2_FLEXPORT)

lib = libsoc_tomahawk2

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

