
# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for qe2000 mbcm driver Library
#

LOCALDIR = src/bcm/sbx/qe2000

include ${SDK}/make/Make.config

lib = libqe2000

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
