# $Id$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
LOCALDIR = src/soc/dpp/PPD

include ${SDK}/make/Make.config

lib = libbcm_dpp_ppd

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
