#
# $Id: Makefile,v 1.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for phy/wcmod/src subdirectory
#
LOCALDIR = src/soc/phy/wcmod/src

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/src/soc/phy/wcmod/include
INCDIR += -I${SDK}/src/soc/phy

lib = libsoc_wcmod
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
