#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/appl/diag/dnx/tx

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/soc/dnx/tx

include ${SDK}/make/Make.subdirs

lib = libdiag_dnxtx

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

