#
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/dnx/pemladrv

include ${SDK}/make/Make.config
include ${SDK}/make/Make.subdirs

lib = libsoc_dnxpemladrv

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
