#
# $Id: Makefile,v 1.3 Broadcom SDK $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/dpp/PORT/

include ${SDK}/make/Make.config

lib = libsoc_dpp_port

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
