#
# $Id:$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# 
# Makefile for SOC swstate subdirectory
#
LOCALDIR = src/soc/hwstate

include ${SDK}/make/Make.config

lib = libsoc_hwstate

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend