#
# $Id: Makefile Exp $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/dpp/QUX/

include ${SDK}/make/Make.config

lib = libsoc_dpp_qux

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
