/*
 * Normally, this file is autogenerated, but for EA we are doing it by hand
 *
 * $Id: allenum.h,v 1.1 Broadcom SDK $
 * $Copyright: (c) 2016 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 */

#ifndef _SOC_EA_ALLENUM_H
#define _SOC_EA_ALLENUM_H


#ifndef EXTERN
# ifdef __cplusplus
#  define EXTERN extern "C"
# else
#  define EXTERN extern
# endif
#endif

/****************************************************************
 *
 * BCM Chip Support options.
 *
 * If NO_BCM_<chip> is defined, do not define BCM_<chip>.  This
 * avoids adding support for the chip.  NO_BCM_<chip> can be added
 * to Make.local.
 ****************************************************************/

#define SOC_EA_MAX_NUM_PORTS    11
#define SOC_EA_MAX_NUM_BLKS		4

#endif	/* !_SOC_EA_ALLENUM_H */

