# $Id: Makefile,v 1.2 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
LOCALDIR = src/customer

include ${SDK}/make/Make.config

lib = libcustomer

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
