#
# $Id: Makefile Exp $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/dpp/JERP/

include ${SDK}/make/Make.config

subdirs := JERP_PP
include ${SDK}/make/Make.subdirs

lib = libsoc_dpp_jerp

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
