# $Id: Makefile Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
LOCALDIR = src/appl/diag/esw/techsupport/l3mc

include ${SDK}/make/Make.config

lib = libtsl3mc

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
