#
# $Id$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for dpp subdirectory
#

LOCALDIR = src/soc/dfe/fe1600

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libsoc_dfe_fe1600

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

