
# $Id: Makefile,v 1.1.2.2 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for ixf1110 mbcm driver Library
#

LOCALDIR = src/bcm/sbx/bme3200

include ${SDK}/make/Make.config

lib = libbme3200

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
