#
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/shared/libxml

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/shared

lib = libxml

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
