# $Id: Makefile,v 1.2 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
LOCALDIR = src/soc/dpp/SAND/Management

include ${SDK}/make/Make.config

lib = libbcm_dpp_sand_mgmt

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
