# $Id: $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM Apache driver Library
#

LOCALDIR = src/bcm/esw/apache

include ${SDK}/make/Make.config

lib = libapache

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
