# $Id$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
LOCALDIR = src/soc/dpp/SAND/SAND_FM

include ${SDK}/make/Make.config

lib = libbcm_dpp_sand_fm

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
