# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for Tomahawk SOC driver Library
#

LOCALDIR = src/soc/esw/tomahawk

include ${SDK}/make/Make.config

lib = libsoc_tomahawk

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

