# $Id: Makefile,v 1.5 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC SAL support
#

LOCALDIR = src/sal/appl

include ${SDK}/make/Make.config

subdirs=${targetbase} editline

include ${SDK}/make/Make.subdirs


lib = libsal_appl

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend



