# Makefile,v 1.2 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# $Id: Makefile,v 1.5 2011/10/05 21:47:19 vinodhkc Exp $
# Makefile for Caladan3 SOC driver Library
#

LOCALDIR = src/soc/sbx/caladan3

include ${SDK}/make/Make.config

lib = libsoc_sbx_caladan3_etu

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
