# Makefile,v 1.2 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# $Id: Makefile,v 1.6 2012/11/06 02:37:31 vinodhkc Exp $
# Makefile for Caladan3 SOC driver Library
#

LOCALDIR = src/soc/sbx/caladan3

include ${SDK}/make/Make.config

subdirs += tmu
subdirs += sbxsim
subdirs += asm3
subdirs += etu
subdirs += sws

include ${SDK}/make/Make.subdirs

lib = libsoc_sbx_caladan3

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
