#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for portlib subdirectory
#

LOCALDIR = src/soc/portmod

include ${SDK}/make/Make.config

subdirs := pms
include ${SDK}/make/Make.subdirs

lib = libsoc_portmod

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
