
/*
 * $Id: tmu_h_ext_sim.stg,v 1.10 Broadcom SDK $
 * $Copyright: (c) 2016 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *
 * g3p1_tmu.h: Guadalupe2k V1.3 TMU table manager & wrappers
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from sdk/caladan_ucode/g3p1/src/g3p1_tmu_cfg.lrp.
 * Edits to this file will be lost when it is regenerated.
 *
 */
 
#ifndef _SOC_SBX_G3P1_TMU_SIM_H
#define _SOC_SBX_G3P1_TMU_SIM_H

#include <soc/types.h>
#include <soc/drv.h>

#if defined(BCM_CALADAN3_SUPPORT) && defined(BCM_CALADAN3_G3P1_SUPPORT) 

#define MAX_BUFFER_SIZE 8*1024
#define MAX_NUM_FIELD 128


extern int soc_sbx_g3p1_mac_add_ext_sim(int unit,  soc_sbx_g3p1_6_byte_t imac ,  int vsi , soc_sbx_g3p1_mac_t *entry);

extern int soc_sbx_g3p1_mac_delete_ext_sim(int unit,  soc_sbx_g3p1_6_byte_t imac ,  int vsi );

extern int soc_sbx_g3p1_mac_get_ext_sim(int unit,  soc_sbx_g3p1_6_byte_t imac ,  int vsi , soc_sbx_g3p1_mac_t *entry);


extern int soc_sbx_g3p1_pvv2e_add_ext_sim(int unit,  int ivid ,  int ovid ,  int port , soc_sbx_g3p1_pvv2e_t *entry);

extern int soc_sbx_g3p1_pvv2e_delete_ext_sim(int unit,  int ivid ,  int ovid ,  int port );

extern int soc_sbx_g3p1_pvv2e_get_ext_sim(int unit,  int ivid ,  int ovid ,  int port , soc_sbx_g3p1_pvv2e_t *entry);


extern int soc_sbx_g3p1_labels_add_ext_sim(int unit,  int label2 ,  int resv ,  int port ,  int label1 , soc_sbx_g3p1_labels_t *entry);

extern int soc_sbx_g3p1_labels_delete_ext_sim(int unit,  int label2 ,  int resv ,  int port ,  int label1 );

extern int soc_sbx_g3p1_labels_get_ext_sim(int unit,  int label2 ,  int resv ,  int port ,  int label1 , soc_sbx_g3p1_labels_t *entry);


extern int soc_sbx_g3p1_v4da_add_ext_sim(int unit,  int vrf ,  int da , soc_sbx_g3p1_v4da_t *entry);

extern int soc_sbx_g3p1_v4da_delete_ext_sim(int unit,  int vrf ,  int da );

extern int soc_sbx_g3p1_v4da_get_ext_sim(int unit,  int vrf ,  int da , soc_sbx_g3p1_v4da_t *entry);


extern int soc_sbx_g3p1_v4sa_add_ext_sim(int unit,  int vrf ,  int sa , soc_sbx_g3p1_v4sa_t *entry);

extern int soc_sbx_g3p1_v4sa_delete_ext_sim(int unit,  int vrf ,  int sa );

extern int soc_sbx_g3p1_v4sa_get_ext_sim(int unit,  int vrf ,  int sa , soc_sbx_g3p1_v4sa_t *entry);


extern int soc_sbx_g3p1_v4mc_sgv_add_ext_sim(int unit,  int vsi ,  int sa ,  int ga , soc_sbx_g3p1_v4mc_sgv_t *entry);

extern int soc_sbx_g3p1_v4mc_sgv_delete_ext_sim(int unit,  int vsi ,  int sa ,  int ga );

extern int soc_sbx_g3p1_v4mc_sgv_get_ext_sim(int unit,  int vsi ,  int sa ,  int ga , soc_sbx_g3p1_v4mc_sgv_t *entry);


extern int soc_sbx_g3p1_v4mc_gv_add_ext_sim(int unit,  int vsi ,  int ga , soc_sbx_g3p1_v4mc_gv_t *entry);

extern int soc_sbx_g3p1_v4mc_gv_delete_ext_sim(int unit,  int vsi ,  int ga );

extern int soc_sbx_g3p1_v4mc_gv_get_ext_sim(int unit,  int vsi ,  int ga , soc_sbx_g3p1_v4mc_gv_t *entry);


extern int soc_sbx_g3p1_v6da_add_ext_sim(int unit,  int vrf ,  int da0 ,  int da1 ,  int da2 ,  int da3 , soc_sbx_g3p1_v6da_t *entry);

extern int soc_sbx_g3p1_v6da_delete_ext_sim(int unit,  int vrf ,  int da0 ,  int da1 ,  int da2 ,  int da3 );

extern int soc_sbx_g3p1_v6da_get_ext_sim(int unit,  int vrf ,  int da0 ,  int da1 ,  int da2 ,  int da3 , soc_sbx_g3p1_v6da_t *entry);


extern int soc_sbx_g3p1_v6sa_add_ext_sim(int unit,  int vrf ,  int sa0 ,  int sa1 ,  int sa2 ,  int sa3 , soc_sbx_g3p1_v6sa_t *entry);

extern int soc_sbx_g3p1_v6sa_delete_ext_sim(int unit,  int vrf ,  int sa0 ,  int sa1 ,  int sa2 ,  int sa3 );

extern int soc_sbx_g3p1_v6sa_get_ext_sim(int unit,  int vrf ,  int sa0 ,  int sa1 ,  int sa2 ,  int sa3 , soc_sbx_g3p1_v6sa_t *entry);


extern int soc_sbx_g3p1_v6mc_gv_add_ext_sim(int unit,  int vsi ,  int ga0 ,  int ga1 ,  int ga2 ,  int ga3 , soc_sbx_g3p1_v6mc_gv_t *entry);

extern int soc_sbx_g3p1_v6mc_gv_delete_ext_sim(int unit,  int vsi ,  int ga0 ,  int ga1 ,  int ga2 ,  int ga3 );

extern int soc_sbx_g3p1_v6mc_gv_get_ext_sim(int unit,  int vsi ,  int ga0 ,  int ga1 ,  int ga2 ,  int ga3 , soc_sbx_g3p1_v6mc_gv_t *entry);


extern int soc_sbx_g3p1_v6mc_sgv_add_ext_sim(int unit,  int vsi ,  int sa0 ,  int sa1 ,  int sa2 ,  int sa3 ,  int ga0 ,  int ga1 ,  int ga2 ,  int ga3 , soc_sbx_g3p1_v6mc_sgv_t *entry);

extern int soc_sbx_g3p1_v6mc_sgv_delete_ext_sim(int unit,  int vsi ,  int sa0 ,  int sa1 ,  int sa2 ,  int sa3 ,  int ga0 ,  int ga1 ,  int ga2 ,  int ga3 );

extern int soc_sbx_g3p1_v6mc_sgv_get_ext_sim(int unit,  int vsi ,  int sa0 ,  int sa1 ,  int sa2 ,  int sa3 ,  int ga0 ,  int ga1 ,  int ga2 ,  int ga3 , soc_sbx_g3p1_v6mc_sgv_t *entry);


extern int soc_sbx_g3p1_oamrx_add_ext_sim(int unit,  int ivid ,  int ovid ,  int dir ,  int port ,  int vid_mode , soc_sbx_g3p1_oamrx_t *entry);

extern int soc_sbx_g3p1_oamrx_delete_ext_sim(int unit,  int ivid ,  int ovid ,  int dir ,  int port ,  int vid_mode );

extern int soc_sbx_g3p1_oamrx_get_ext_sim(int unit,  int ivid ,  int ovid ,  int dir ,  int port ,  int vid_mode , soc_sbx_g3p1_oamrx_t *entry);


extern int soc_sbx_g3p1_maidmep_add_ext_sim(int unit,  int svc_hdl ,  int mepid ,  int msg_type ,  int mdlvl , soc_sbx_g3p1_maidmep_t *entry);

extern int soc_sbx_g3p1_maidmep_delete_ext_sim(int unit,  int svc_hdl ,  int mepid ,  int msg_type ,  int mdlvl );

extern int soc_sbx_g3p1_maidmep_get_ext_sim(int unit,  int svc_hdl ,  int mepid ,  int msg_type ,  int mdlvl , soc_sbx_g3p1_maidmep_t *entry);


extern int soc_sbx_g3p1_emlfilter_add_ext_sim(int unit,  int emlindex , soc_sbx_g3p1_emlfilter_t *entry);

extern int soc_sbx_g3p1_emlfilter_delete_ext_sim(int unit,  int emlindex );

extern int soc_sbx_g3p1_emlfilter_get_ext_sim(int unit,  int emlindex , soc_sbx_g3p1_emlfilter_t *entry);


extern int soc_sbx_g3p1_ete_add_ext_sim(int unit,  int etei , soc_sbx_g3p1_ete_t *entry);

extern int soc_sbx_g3p1_ete_delete_ext_sim(int unit,  int etei );

extern int soc_sbx_g3p1_ete_get_ext_sim(int unit,  int etei , soc_sbx_g3p1_ete_t *entry);


extern int soc_sbx_g3p1_oam_ep_add_ext_sim(int unit,  int oam_epi , soc_sbx_g3p1_oam_ep_t *entry);

extern int soc_sbx_g3p1_oam_ep_delete_ext_sim(int unit,  int oam_epi );

extern int soc_sbx_g3p1_oam_ep_get_ext_sim(int unit,  int oam_epi , soc_sbx_g3p1_oam_ep_t *entry);


extern int soc_sbx_g3p1_oam_local_add_ext_sim(int unit,  int oam_locali , soc_sbx_g3p1_oam_local_t *entry);

extern int soc_sbx_g3p1_oam_local_delete_ext_sim(int unit,  int oam_locali );

extern int soc_sbx_g3p1_oam_local_get_ext_sim(int unit,  int oam_locali , soc_sbx_g3p1_oam_local_t *entry);


extern int soc_sbx_g3p1_oam_peer_add_ext_sim(int unit,  int oam_peer_idx , soc_sbx_g3p1_oam_peer_t *entry);

extern int soc_sbx_g3p1_oam_peer_delete_ext_sim(int unit,  int oam_peer_idx );

extern int soc_sbx_g3p1_oam_peer_get_ext_sim(int unit,  int oam_peer_idx , soc_sbx_g3p1_oam_peer_t *entry);


extern int soc_sbx_g3p1_labels3_add_ext_sim(int unit,  int label3 ,  int label2 ,  int label1 ,  int resv1 ,  int port , soc_sbx_g3p1_labels3_t *entry);

extern int soc_sbx_g3p1_labels3_delete_ext_sim(int unit,  int label3 ,  int label2 ,  int label1 ,  int resv1 ,  int port );

extern int soc_sbx_g3p1_labels3_get_ext_sim(int unit,  int label3 ,  int label2 ,  int label1 ,  int resv1 ,  int port , soc_sbx_g3p1_labels3_t *entry);


extern int soc_sbx_g3p1_bfd_ld2e_add_ext_sim(int unit,  int localDiscri , soc_sbx_g3p1_bfd_ld2e_t *entry);

extern int soc_sbx_g3p1_bfd_ld2e_delete_ext_sim(int unit,  int localDiscri );

extern int soc_sbx_g3p1_bfd_ld2e_get_ext_sim(int unit,  int localDiscri , soc_sbx_g3p1_bfd_ld2e_t *entry);


extern int soc_sbx_g3p1_sample_dm1_add_ext_sim(int unit,  int index_1 ,  int index_2 , soc_sbx_g3p1_sample_dm1_t *entry);

extern int soc_sbx_g3p1_sample_dm1_delete_ext_sim(int unit,  int index_1 ,  int index_2 );

extern int soc_sbx_g3p1_sample_dm1_get_ext_sim(int unit,  int index_1 ,  int index_2 , soc_sbx_g3p1_sample_dm1_t *entry);


#endif

#endif
