# $Id$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# 

export TARGET
export BLDDIR
export LIBDIR

LOCALDIR = systems/sim/dpp/ChipSim

include ${SDK}/make/Make.config

lib = libchipsim_sim

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
