# $Id: Makefile,v 1.1.6.2 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$

LOCALDIR = src/soc/kbp/nlm3/nlmdevmgr

include ${SDK}/make/Make.config

lib = libsoc_kbp_nlm3_dm

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
