/** \file dnx_data_internal_fabric.h
 * 
 * MODULE DEVICE DATA - DNX_DATA
 * 
 * Device Data
 * SW component that maintains per device data
 * The data is static and won't be changed after device initialization.
 *     
 * Supported data types:
 *     - Define             - a 'uint32' number (a max value for all devices is maintained)
 *     - feature            - 1 bit per each feature (supported/not supported) - support soc properties 
 *     - table              - the data is accessed with keys and/or can maintain multiple values and/or set by soc property
 *     - numeric            - a 'uint32' number that support soc properties
 * 
 * User interface for DNX DATA component can be found in "dnx_data_if.h" and "dnx_data_if_#module#.h"
 * 
 * Adding the data is done via XMLs placed in "tools/autocoder/DeviceData/dnx/.." 
 * "How to" User Guide can be found in confluence. 
 *        
 *     
 * 
 * AUTO-GENERATED BY AUTOCODER!
 * DO NOT EDIT THIS FILE!
 */
/* *INDENT-OFF* */
/*
 * $Copyright: (c) 2016 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 */
#ifndef _DNX_DATA_INTERNAL_FABRIC_H_
/*{*/
#define _DNX_DATA_INTERNAL_FABRIC_H_
/*
 * INCLUDE FILES:
 * {
 */
#include <soc/dnx/dnx_data/dnx_data_internal.h>
#include <soc/dnx/dnx_data/dnx_data_fabric.h>
/*
 * }
 */

/*!
* \brief This file is only used by DNX (JR2 family). Including it by
* software that is not specific to DNX is an error.
*/
#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif

/*
 * TYPEDEFS:
 * {
 */
/**
 * \brief 
 * Submodule enum
 */
typedef enum
{
    dnx_data_fabric_submodule_links,
    dnx_data_fabric_submodule_thresholds,
    dnx_data_fabric_submodule_cell,
    dnx_data_fabric_submodule_pipes,

    /**
     * Must be last one!
     */
    dnx_data_fabric_submodule_nof
} dnx_data_fabric_submodule_e;

/*
 * }
 */

/*
 * SUBMODULE LINKS:
 * {
 */
/*
 * Features
 */
/* Feature enum - placed in if header (should be exposed to component user */
/* Get Data */
/**
 * \brief get submodule feauture - disabled/enabled
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - Unit #
 *   \param [in] feature - feature to get (see enum defintion for more details
 * \par INDIRECT INPUT:
 *   device data - module global data
 * \par DIRECT OUTPUT:
 *     is_supported - returns 1 iff supported and 0 otherwise
 * \par INDIRECT OUTPUT:
 * \remark
 *   * None
 * \see
 *   * None
 */
int dnx_data_fabric_links_feature_get(
    int unit,
    dnx_data_fabric_links_feature_e feature);

/*
 * Defines
 */
/**
 * \brief 
 * Define enum
 */
typedef enum
{
    dnx_data_fabric_links_define_nof_links,

    /**
     * Must be last one!
     */
    dnx_data_fabric_links_define_nof
} dnx_data_fabric_links_define_e;

/* Get Data */
/**
 * \brief returns define data of nof_links
 * Module - 'fabric', Submodule - 'links', data - 'nof_links'
 * nof of fabric links
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - unit #
 * \par INDIRECT INPUT:
 *   _dnx_data[unit] - module global data
 * \par DIRECT OUTPUT:
 *     nof_links - the required data value
 * \par INDIRECT OUTPUT:
 * \remark
 *   * None
 * \see
 *   * None
 */
uint32 dnx_data_fabric_links_nof_links_get(
    int unit);

/*
 * Tables
 */
/**
 * \brief 
 * Table enum
 */
typedef enum
{

    /**
     * Must be last one!
     */
    dnx_data_fabric_links_table_nof
} dnx_data_fabric_links_table_e;

/* Get Data */
/* Get Value Str */
/*
 * SUBMODULE THRESHOLDS:
 * {
 */
/*
 * Features
 */
/* Feature enum - placed in if header (should be exposed to component user */
/* Get Data */
/**
 * \brief get submodule feauture - disabled/enabled
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - Unit #
 *   \param [in] feature - feature to get (see enum defintion for more details
 * \par INDIRECT INPUT:
 *   device data - module global data
 * \par DIRECT OUTPUT:
 *     is_supported - returns 1 iff supported and 0 otherwise
 * \par INDIRECT OUTPUT:
 * \remark
 *   * None
 * \see
 *   * None
 */
int dnx_data_fabric_thresholds_feature_get(
    int unit,
    dnx_data_fabric_thresholds_feature_e feature);

/*
 * Defines
 */
/**
 * \brief 
 * Define enum
 */
typedef enum
{
    dnx_data_fabric_thresholds_define_default_severity,
    dnx_data_fabric_thresholds_define_default_mode,

    /**
     * Must be last one!
     */
    dnx_data_fabric_thresholds_define_nof
} dnx_data_fabric_thresholds_define_e;

/* Get Data */
/**
 * \brief returns define data of default_severity
 * Module - 'fabric', Submodule - 'thresholds', data - 'default_severity'
 * default severity for thresholds
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - unit #
 * \par INDIRECT INPUT:
 *   _dnx_data[unit] - module global data
 * \par DIRECT OUTPUT:
 *     default_severity - the required data value
 * \par INDIRECT OUTPUT:
 * \remark
 *   * None
 * \see
 *   * None
 */
uint32 dnx_data_fabric_thresholds_default_severity_get(
    int unit);

/**
 * \brief returns define data of default_mode
 * Module - 'fabric', Submodule - 'thresholds', data - 'default_mode'
 * default mode for thresholds
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - unit #
 * \par INDIRECT INPUT:
 *   _dnx_data[unit] - module global data
 * \par DIRECT OUTPUT:
 *     default_mode - the required data value
 * \par INDIRECT OUTPUT:
 * \remark
 *   * None
 * \see
 *   * None
 */
uint32 dnx_data_fabric_thresholds_default_mode_get(
    int unit);

/*
 * Tables
 */
/**
 * \brief 
 * Table enum
 */
typedef enum
{
    dnx_data_fabric_thresholds_table_dch_default,

    /**
     * Must be last one!
     */
    dnx_data_fabric_thresholds_table_nof
} dnx_data_fabric_thresholds_table_e;

/* Get Data */
/**
 * \brief get table dch_default info
 * set of threholds
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - unit #
 *   \param [in] severity - severity thresholds
 *   \param [in] mode - mode of threholds according to fabric pipes
 * \par INDIRECT INPUT:
 *   _dnx_data[unit] - module global data
 * \par DIRECT OUTPUT:
 *     dch_default - returns the relevant entry values grouped in struct - see dnx_data_fabric_thresholds_dch_default_t
 * \par INDIRECT OUTPUT:
 * \remark
 *   * None
 * \see
 *   * None
 */
const dnx_data_fabric_thresholds_dch_default_t * dnx_data_fabric_thresholds_dch_default_get(
    int unit,
    int severity,
    int mode);

/* Get Value Str */
/**
 * \brief Get table value as string
 * Module - 'fabric', Submodule - 'thresholds', table - 'dch_default'
 * set of threholds
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - Unit #
 *   \param [in] key0 - key #0 index - 0 if not used
 *   \param [in] key1 - key #1 index - 0 if not used
 *   \param [in] value_index - value index to get - the index is alligned with values array in table structure
 * \par INDIRECT INPUT:
 *   _dnx_data[unit] - module global data
 * \par DIRECT OUTPUT:
 *     err - See shr_error_e
 * \par INDIRECT OUTPUT:
 *   \param [out] buffer - buffer for the value
 * \remark
 *   * None
 * \see
 *   * None
 */
shr_error_e dnx_data_fabric_thresholds_dch_default_entry_str_get(
    int unit,
    char *buffer,
    int key0,
    int key1,
    int value_index);

/*
 * SUBMODULE CELL:
 * {
 */
/*
 * Features
 */
/* Feature enum - placed in if header (should be exposed to component user */
/* Get Data */
/**
 * \brief get submodule feauture - disabled/enabled
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - Unit #
 *   \param [in] feature - feature to get (see enum defintion for more details
 * \par INDIRECT INPUT:
 *   device data - module global data
 * \par DIRECT OUTPUT:
 *     is_supported - returns 1 iff supported and 0 otherwise
 * \par INDIRECT OUTPUT:
 * \remark
 *   * None
 * \see
 *   * None
 */
int dnx_data_fabric_cell_feature_get(
    int unit,
    dnx_data_fabric_cell_feature_e feature);

/*
 * Defines
 */
/**
 * \brief 
 * Define enum
 */
typedef enum
{
    dnx_data_fabric_cell_define_nof_priorities,

    /**
     * Must be last one!
     */
    dnx_data_fabric_cell_define_nof
} dnx_data_fabric_cell_define_e;

/* Get Data */
/**
 * \brief returns define data of nof_priorities
 * Module - 'fabric', Submodule - 'cell', data - 'nof_priorities'
 * nof of supported fabric priorities
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - unit #
 * \par INDIRECT INPUT:
 *   _dnx_data[unit] - module global data
 * \par DIRECT OUTPUT:
 *     nof_priorities - the required data value
 * \par INDIRECT OUTPUT:
 * \remark
 *   * None
 * \see
 *   * None
 */
uint32 dnx_data_fabric_cell_nof_priorities_get(
    int unit);

/*
 * Tables
 */
/**
 * \brief 
 * Table enum
 */
typedef enum
{
    dnx_data_fabric_cell_table_pcp,

    /**
     * Must be last one!
     */
    dnx_data_fabric_cell_table_nof
} dnx_data_fabric_cell_table_e;

/* Get Data */
/**
 * \brief get table pcp info
 * packet cell packing
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - unit #
 * \par INDIRECT INPUT:
 *   _dnx_data[unit] - module global data
 * \par DIRECT OUTPUT:
 *     pcp - returns the relevant entry values grouped in struct - see dnx_data_fabric_cell_pcp_t
 * \par INDIRECT OUTPUT:
 * \remark
 *   * None
 * \see
 *   * None
 */
const dnx_data_fabric_cell_pcp_t * dnx_data_fabric_cell_pcp_get(
    int unit);

/* Get Value Str */
/**
 * \brief Get table value as string
 * Module - 'fabric', Submodule - 'cell', table - 'pcp'
 * packet cell packing
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - Unit #
 *   \param [in] key0 - key #0 index - 0 if not used
 *   \param [in] key1 - key #1 index - 0 if not used
 *   \param [in] value_index - value index to get - the index is alligned with values array in table structure
 * \par INDIRECT INPUT:
 *   _dnx_data[unit] - module global data
 * \par DIRECT OUTPUT:
 *     err - See shr_error_e
 * \par INDIRECT OUTPUT:
 *   \param [out] buffer - buffer for the value
 * \remark
 *   * None
 * \see
 *   * None
 */
shr_error_e dnx_data_fabric_cell_pcp_entry_str_get(
    int unit,
    char *buffer,
    int key0,
    int key1,
    int value_index);

/*
 * SUBMODULE PIPES:
 * {
 */
/*
 * Features
 */
/* Feature enum - placed in if header (should be exposed to component user */
/* Get Data */
/**
 * \brief get submodule feauture - disabled/enabled
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - Unit #
 *   \param [in] feature - feature to get (see enum defintion for more details
 * \par INDIRECT INPUT:
 *   device data - module global data
 * \par DIRECT OUTPUT:
 *     is_supported - returns 1 iff supported and 0 otherwise
 * \par INDIRECT OUTPUT:
 * \remark
 *   * None
 * \see
 *   * None
 */
int dnx_data_fabric_pipes_feature_get(
    int unit,
    dnx_data_fabric_pipes_feature_e feature);

/*
 * Defines
 */
/**
 * \brief 
 * Define enum
 */
typedef enum
{
    dnx_data_fabric_pipes_define_max_nof_pipes,

    /**
     * Must be last one!
     */
    dnx_data_fabric_pipes_define_nof
} dnx_data_fabric_pipes_define_e;

/* Get Data */
/**
 * \brief returns define data of max_nof_pipes
 * Module - 'fabric', Submodule - 'pipes', data - 'max_nof_pipes'
 * max supported fabric pipes
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - unit #
 * \par INDIRECT INPUT:
 *   _dnx_data[unit] - module global data
 * \par DIRECT OUTPUT:
 *     max_nof_pipes - the required data value
 * \par INDIRECT OUTPUT:
 * \remark
 *   * None
 * \see
 *   * None
 */
uint32 dnx_data_fabric_pipes_max_nof_pipes_get(
    int unit);

/*
 * Tables
 */
/**
 * \brief 
 * Table enum
 */
typedef enum
{
    dnx_data_fabric_pipes_table_nof_pipes,
    dnx_data_fabric_pipes_table_map,
    dnx_data_fabric_pipes_table_system,

    /**
     * Must be last one!
     */
    dnx_data_fabric_pipes_table_nof
} dnx_data_fabric_pipes_table_e;

/* Get Data */
/**
 * \brief get table nof_pipes info
 * number of actual (configured) pipes
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - unit #
 * \par INDIRECT INPUT:
 *   _dnx_data[unit] - module global data
 * \par DIRECT OUTPUT:
 *     nof_pipes - returns the relevant entry values grouped in struct - see dnx_data_fabric_pipes_nof_pipes_t
 * \par INDIRECT OUTPUT:
 * \remark
 *   * None
 * \see
 *   * None
 */
const dnx_data_fabric_pipes_nof_pipes_t * dnx_data_fabric_pipes_nof_pipes_get(
    int unit);

/**
 * \brief get table map info
 * map traffic cast X priority to fabric pipe
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - unit #
 * \par INDIRECT INPUT:
 *   _dnx_data[unit] - module global data
 * \par DIRECT OUTPUT:
 *     map - returns the relevant entry values grouped in struct - see dnx_data_fabric_pipes_map_t
 * \par INDIRECT OUTPUT:
 * \remark
 *   * None
 * \see
 *   * None
 */
const dnx_data_fabric_pipes_map_t * dnx_data_fabric_pipes_map_get(
    int unit);

/**
 * \brief get table system info
 * system attributes
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - unit #
 * \par INDIRECT INPUT:
 *   _dnx_data[unit] - module global data
 * \par DIRECT OUTPUT:
 *     system - returns the relevant entry values grouped in struct - see dnx_data_fabric_pipes_system_t
 * \par INDIRECT OUTPUT:
 * \remark
 *   * None
 * \see
 *   * None
 */
const dnx_data_fabric_pipes_system_t * dnx_data_fabric_pipes_system_get(
    int unit);

/* Get Value Str */
/**
 * \brief Get table value as string
 * Module - 'fabric', Submodule - 'pipes', table - 'nof_pipes'
 * number of actual (configured) pipes
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - Unit #
 *   \param [in] key0 - key #0 index - 0 if not used
 *   \param [in] key1 - key #1 index - 0 if not used
 *   \param [in] value_index - value index to get - the index is alligned with values array in table structure
 * \par INDIRECT INPUT:
 *   _dnx_data[unit] - module global data
 * \par DIRECT OUTPUT:
 *     err - See shr_error_e
 * \par INDIRECT OUTPUT:
 *   \param [out] buffer - buffer for the value
 * \remark
 *   * None
 * \see
 *   * None
 */
shr_error_e dnx_data_fabric_pipes_nof_pipes_entry_str_get(
    int unit,
    char *buffer,
    int key0,
    int key1,
    int value_index);

/**
 * \brief Get table value as string
 * Module - 'fabric', Submodule - 'pipes', table - 'map'
 * map traffic cast X priority to fabric pipe
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - Unit #
 *   \param [in] key0 - key #0 index - 0 if not used
 *   \param [in] key1 - key #1 index - 0 if not used
 *   \param [in] value_index - value index to get - the index is alligned with values array in table structure
 * \par INDIRECT INPUT:
 *   _dnx_data[unit] - module global data
 * \par DIRECT OUTPUT:
 *     err - See shr_error_e
 * \par INDIRECT OUTPUT:
 *   \param [out] buffer - buffer for the value
 * \remark
 *   * None
 * \see
 *   * None
 */
shr_error_e dnx_data_fabric_pipes_map_entry_str_get(
    int unit,
    char *buffer,
    int key0,
    int key1,
    int value_index);

/**
 * \brief Get table value as string
 * Module - 'fabric', Submodule - 'pipes', table - 'system'
 * system attributes
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - Unit #
 *   \param [in] key0 - key #0 index - 0 if not used
 *   \param [in] key1 - key #1 index - 0 if not used
 *   \param [in] value_index - value index to get - the index is alligned with values array in table structure
 * \par INDIRECT INPUT:
 *   _dnx_data[unit] - module global data
 * \par DIRECT OUTPUT:
 *     err - See shr_error_e
 * \par INDIRECT OUTPUT:
 *   \param [out] buffer - buffer for the value
 * \remark
 *   * None
 * \see
 *   * None
 */
shr_error_e dnx_data_fabric_pipes_system_entry_str_get(
    int unit,
    char *buffer,
    int key0,
    int key1,
    int value_index);

/*
 * FUNCTIONS:
 * {
 */
/**
 * \brief Init module
 * 
 * \par DIRECT INPUT:
 *   \param [in] unit - Unit #
 * \par INDIRECT INPUT:
 *   * None
 * \par DIRECT OUTPUT:
 *     rv - see 'shr_error_e
 * \par INDIRECT OUTPUT:
 *   \param [out] module_data - pointer to module data
 * \remark
 *   * None
 * \see
 *   * None
 */
shr_error_e dnx_data_fabric_init(
    int unit,
    dnx_data_module_t *module_data);

/*
 * }
 */
/*}*/
#else     /*DNX_DATA_INTERNAL_FABRIC_H_*/
/*{*/
#ifndef DNX_DATA_INTERNAL
/*{*/
#error "dnx_data_internal_fabric file might include any header files, therfore header files must not include it.\nAny include to dnx_data_internal_fabric must be from 'c' file"
/*}*/
#endif /*DNX_DATA_INTERNAL*/
/*}*/
#endif /*_DNX_DATA_INTERNAL_FABRIC_H_*/
/* *INDENT-ON* */
