# $Id: Makefile,v 1.3 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/dpp/ptp

include ${SDK}/make/Make.config

#CFLAGS += -DPTP_RX_CALLBACK_DEBUG

lib = libptp_dpp

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
