#
#   $Id: Makefile,v 1.2.648.1 Broadcom SDK $
# 
# 
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for i2c subdirectory
#
CFLAGS += -g
LOCALDIR = src/soc/i2c

include ${SDK}/make/Make.config

lib = libsoc_i2c
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
