#
# $Id:$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# 
# Makefile for SOC swstate layout subdirectory
#
LOCALDIR = src/shared/swstate/layout

# enable optimization & disable debugging for this lib
DEBUG_OPTIMIZE = TRUE
DEBUG_CFLAGS += -g0

include ${SDK}/make/Make.config

lib = libshared_swstate_layout

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
