#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/bcm/dnx/algo/lif_mngr

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/bcm_int/dnx/algo/lif_mngr

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxalgolif

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
