# 
# $Id: Makefile,v 1.2.12.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for Caladan3 SOC driver Library
#

LOCALDIR = src/soc/sbx/caladan3/tmu

include ${SDK}/make/Make.config
CFG_FLAGS+=-g
subdirs += taps

include ${SDK}/make/Make.subdirs

lib = libsoc_sbx_caladan3_tmu

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
