# $Id: Makefile,v 1.3 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC EA driver Library
#
LOCALDIR = src/soc/ea/tk371x

include ${SDK}/make/Make.config

subdirs := utils

include ${SDK}/make/Make.subdirs

lib = libsoceatk371x

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
