# -*- Makefile -*-
# $Id: Makefile,v 1.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC driver Library
#
LOCALDIR = src/soc/robo/tbx/thunderbolt

include ${SDK}/make/Make.config

lib = libsocrobo_tb
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
