# -*- Makefile -*-
# $Id: Makefile,v 1.2 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

include ${SDK}/make/Make.config

subdirs= shared bcm-diag-proxy

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.depend
