# $Id: Makefile,v 1.1.12.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for Caladan3 SOC TAPs driver Library
#

LOCALDIR = src/soc/sbx/caladan3/tmu/taps

include ${SDK}/make/Make.config

lib = libsoc_sbx_caladan3_tmu_taps

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
