# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM Tomahawk driver Library
#

LOCALDIR = src/bcm/esw/tomahawk2

include ${SDK}/make/Make.config

lib = libtomahawk2

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
