# $Id$
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# $Id$
# Makefile for Triumph3 SOC driver Library
#

LOCALDIR = src/soc/esw/triumph3

include ${SDK}/make/Make.config

lib = libsoc_triumph3

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
