#
# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/dpp/DRC/

include ${SDK}/make/Make.config

lib = libsoc_dpp_drc

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

