# $Id$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$

LOCALDIR = src/soc/kbp/nlm3

include ${SDK}/make/Make.config

KBP_SRCS += ../common nlmdevmgr nlmgenerictblmgr nlmrangemgr blackholexpt xpt

subdirs := $(KBP_SRCS)

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.depend
