# $Id: Makefile,v 1.5.40.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$

LOCALDIR = src/soc/kbp/alg_kbp

include ${SDK}/make/Make.config

subdirs += portability

include ${SDK}/make/Make.subdirs
include ${SDK}/make/Make.depend
