#
# $Id$
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/appl/dpp/UserInterface/ppd

include ${SDK}/make/Make.config

lib = libappl_dpp_ui_ppd

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
