#
# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for phy/tscmod/src subdirectory
#
LOCALDIR = src/soc/phy/tscmod/src

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/src/soc/phy/tscmod/include
INCDIR += -I${SDK}/src/soc/phy

lib = libsoc_tscmod
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
