# $Id: Makefile,v 1.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# 

LOCALDIR = src/appl/portmod

include ${SDK}/make/Make.config

lib = lib_portmod_appl

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
