# $Id:$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SDK board driver Library
#

LOCALDIR = src/board

include ${SDK}/make/Make.config

subdirs=manager support stack driver
include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.depend
