
# $Id: Makefile,v 1.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for fe2k/g2p3 ucode Library
#

LOCALDIR = src/bcm/sbx/caldan3/g3p1

include ${SDK}/make/Make.config

lib = libcaladan3g3p1

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
