#
# $Id: Makefile,v 1.3 Broadcom SDK $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/dpp/JER/JER_PP

include ${SDK}/make/Make.config

lib = libsoc_dpp_jer_pp

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
