/*
 * $Id: sbFabStatus.h,v 1.8 Broadcom SDK $
 * $Copyright: (c) 2016 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *
 * sbFlibStatus.h: Sandburst fabric ilib 2.x driver status codes
 */

#ifndef _SOC_SBX_SB_FAB_STATUS_H_
#define _SOC_SBX_SB_FAB_STATUS_H_

#include "sbTypesGlue.h"

typedef enum sbFabStatus_e {
    SB_FAB_STATUS_OK = 0,	/* Must have number 0 */
    SB_FAB_STATUS_NO_MEMORY = SB_BUILD_ERR_CODE(SB_VENDOR_ID_SANDBURST, SB_MODULE_ID_FAB_ILIB, 0x1),
    SB_FAB_STATUS_BAD_ARGS,
    SB_FAB_STATUS_NODE_IN_USE,
    SB_FAB_STATUS_PORT_NOT_PRESENT,
    SB_FAB_STATUS_INIT_FAILED,
    SB_FAB_STATUS_TOPO_BAD_SLOT,
    SB_FAB_STATUS_TOPO_SLOT_IN_USE,
    SB_FAB_STATUS_TOPO_LINK_IN_USE,
    SB_FAB_STATUS_TOPO_BAD_CARD_STATE,
    SB_FAB_STATUS_BAD_PHYSICAL_CROSSBAR_ID,
    SB_FAB_STATUS_BAD_ESET,
    SB_FAB_STATUS_BAD_DEVICE_TYPE,
    SB_FAB_STATUS_BAD_PHYSICAL_DEVICE,
    SB_FAB_STATUS_BAD_DATA_PLANE,
    SB_FAB_STATUS_BAD_CONTROL_PLANE,
    SB_FAB_STATUS_BAD_NODE,
    SB_FAB_STATUS_BAD_INIT_PARAMS,
    SB_FAB_STATUS_LOGICAL_CROSSBAR_IN_USE,
    SB_FAB_STATUS_LOGICAL_CROSSBAR_NOT_IN_USE,
    SB_FAB_STATUS_LINK_TO_INVALID_LOGICAL_CROSSBAR,
    SB_FAB_STATUS_NODE_MISSING_LINK_TO_LOGICAL_CROSSBAR,
    SB_FAB_STATUS_NODE_MISSING_LINK_TO_SWITCH_CONTROLLER,
    SB_FAB_STATUS_CARD_NOT_FINALIZED,
    SB_FAB_STATUS_CARD_NOT_INSTALLED,
    SB_FAB_STATUS_CARD_NOT_REMOVED,
    SB_FAB_STATUS_TRANSPORT_PING_FAILED,
    SB_FAB_STATUS_BAD_LINK_ID,
    SB_FAB_STATUS_BAD_LINK_STATE,
    SB_FAB_STATUS_BAD_PHYSICAL_LCM_ID,
    SB_FAB_STATUS_BAD_FABRIC_PORT_MAPPING,
    SB_FAB_STATUS_BAD_PORT_INTERFACE_ID,
    SB_FAB_STATUS_BAD_PORT_OWNER,
    SB_FAB_STATUS_BAD_TME,
    SB_FAB_STATUS_TME_IN_USE,
    SB_FAB_STATUS_BAD_LOGICAL_PORT_HANDLE,
    SB_FAB_STATUS_BAD_LOGICAL_PORT_OWNER_ID,
    SB_FAB_STATUS_NO_FREE_LOGICAL_PORT,
    SB_FAB_STATUS_FLOW_IN_USE,
    SB_FAB_STATUS_FLOW_NOT_ENABLED,
    SB_FAB_STATUS_FLOW_PARTIALLY_ENABLED,
    SB_FAB_STATUS_FLOW_NOT_DISABLED,
    SB_FAB_STATUS_FLOW_PARTIALLY_DISABLED,
    SB_FAB_STATUS_FLOW_BAD_PATH,
    SB_FAB_STATUS_FLOW_BAD_TYPE,
    SB_FAB_STATUS_FLOW_BAD_WRED_TEMPLATE,
    SB_FAB_STATUS_BAD_QUEUE_NUMBER,
    SB_FAB_STATUS_QUEUE_IS_RESERVED,
    SB_FAB_STATUS_QUEUE_IN_USE,
    SB_FAB_STATUS_BAD_QE_MODE,
    SB_FAB_STATUS_LOGICAL_PORTS_NOT_ENABLED,
    SB_FAB_STATUS_LOGICAL_PORTS_PARTIALLY_ENABLED,
    SB_FAB_STATUS_LOGICAL_PORTS_PARAMS_PARTIALLY_SET,
    SB_FAB_STATUS_FABRIC_PORTS_NOT_ENABLED,
    SB_FAB_STATUS_FABRIC_PORTS_PARTIALLY_ENABLED,
    SB_FAB_STATUS_FLOWS_NOT_ENABLED,
    SB_FAB_STATUS_FLOWS_PARTIALLY_ENABLED,
    SB_FAB_STATUS_BM1600_INIT_FAILED,
    SB_FAB_STATUS_BM3200_INIT_FAILED,
    SB_FAB_STATUS_QE1000_INIT_FAILED,
    SB_FAB_STATUS_QE2000_INIT_FAILED,
    SB_FAB_STATUS_USER_MALLOC_FAILED,
    SB_FAB_STATUS_MASTER_TRANSPORT_FAILED,
    SB_FAB_STATUS_BAD_FLIB_INSTANCE,
    SB_FAB_STATUS_BAD_DEVICE,
    SB_FAB_STATUS_DEVICE_ACCESS_FAILED,
    SB_FAB_STATUS_TARGET_MAX_DEVICE_EXCEEDED,
    SB_FAB_STATUS_TARGET_TRANSPORT_FAILED,
    SB_FAB_STATUS_BAD_FLIB_MODE,
    SB_FAB_STATUS_INVALID_ACTIVE_SWITCH_CONTROLLER,
    SB_FAB_STATUS_MCGROUP_NOT_PRESENT,
    SB_FAB_STATUS_MCGROUPS_NOT_ENABLED,
    SB_FAB_STATUS_MCGROUPS_PARTIALLY_ENABLED,
    SB_FAB_STATUS_BAD_COS,
    SB_FAB_STATUS_BAD_FABRIC_MODE,
    SB_FAB_STATUS_NO_AVAILABLE_BW,
    SB_FAB_STATUS_NOT_ENOUGH_AVAILABLE_BW,
    SB_FAB_STATUS_BAD_PHYSICAL_PORT,
    SB_FAB_STATUS_PHYSICAL_PORT_DISABLED,
    SB_FAB_STATUS_PHYSICAL_PORT_IN_USE,
    SB_FAB_STATUS_ESET_MEMORY_RD_WR_FAILED,
    SB_FAB_STATUS_ADD_QUEUE_FAILED,
    SB_FAB_STATUS_DELETE_QUEUE_FAILED,
    SB_FAB_STATUS_TARGET_INDIRECT_MEMORY_TIMEOUT,
    SB_FAB_STATUS_TARGET_ADD_QUEUE_FAILED,
    SB_FAB_STATUS_TARGET_DELETE_QUEUE_FAILED,
    SB_FAB_STATUS_TARGET_QE2000_E2Q_TABLE_WRITE_FAILED,
    SB_FAB_STATUS_TARGET_QE2000_Q2EC_TABLE_WRITE_FAILED,
    SB_FAB_STATUS_TARGET_QE2000_Q2EC_TABLE_READ_FAILED,
    SB_FAB_STATUS_TARGET_QE2000_QDEPTH_TABLE_WRITE_FAILED,
    SB_FAB_STATUS_TARGET_QE2000_QAGE_THRESHKEY_TABLE_WRITE_FAILED,
    SB_FAB_STATUS_TARGET_QE2000_QSHAPE_MAXBURST_TABLE_WRITE_FAILED,
    SB_FAB_STATUS_TARGET_QE2000_QSHAPE_RATE_TABLE_WRITE_FAILED,
    SB_FAB_STATUS_TARGET_QE2000_QRATE_TABLE_WRITE_FAILED,
    SB_FAB_STATUS_TARGET_QE2000_QPARAM_TABLE_WRITE_FAILED,
    SB_FAB_STATUS_TARGET_QE2000_BAA_CONFIG_TABLE_UPDATE_FAILED,
    SB_FAB_STATUS_TARGET_QE2000_QUEUE_AGE_TABLE_READ_FAILED,
    SB_FAB_STATUS_TARGET_QE2000_QUEUE_AGE_TABLE_WRITE_FAILED,
    SB_FAB_STATUS_TARGET_QE2000_BW_PORT_CONFIG_TABLE_UPDATE_FAILED,
    SB_FAB_STATUS_QOS_SET_PARAMS_FAILED,
    SB_FAB_STATUS_LOGICAL_PORT_SHAPING_MISMATCH,
    SB_FAB_STATUS_TARGET_UPDATE_MVT_PORTS_FAILED,
    SB_FAB_STATUS_TARGET_SET_LOG_LEVEL_FAILED,
    SB_FAB_STATUS_LOGICAL_CROSSBAR_NOT_PRESENT,
    SB_FAB_STATUS_LOGICAL_CROSSBAR_NUMBER_OUT_OF_RANGE,
    SB_FAB_STATUS_LOGICAL_CROSSBAR_LINK_STATUS_BAD,
    SB_FAB_STATUS_CONTROL_LINK_STATUS_BAD,
    SB_FAB_STATUS_LOGICAL_CROSSBAR_LINKS_BELOW_MINIMUM,
    SB_FAB_STATUS_DEVICE_NOT_PRESENT,
    SB_FAB_STATUS_UNKNOWN_LINK_TYPE,
    SB_FAB_STATUS_TRANSPORT_CLEAR_ERRORS_FAILED,
    SB_FAB_STATUS_TRANSPORT_SAMPLE_LINK_STATUS_FAILED,
    SB_FAB_STATUS_FLOW_PARAMS_NOT_SET,
    SB_FAB_STATUS_FLOW_PARAMS_PARTIALLY_SET,
    SB_FAB_STATUS_SWITCH_CONTROLLER_NOT_PRESENT,
    SB_FAB_STATUS_TARGET_QE_UPDATE_XCFG_FAILED,
    SB_FAB_STATUS_BM3200_BW_TABLE_BANK0_ACCESS_FAILED,
    SB_FAB_STATUS_BM3200_BW_TABLE_BANK1_ACCESS_FAILED,
    SB_FAB_STATUS_LOGICAL_PORT_UPDATE_ERROR,
    SB_FAB_STATUS_EGRESS_SHAPER_NO_RESOURCE,
    SB_FAB_STATUS_EGRESS_SHAPER_ALREADY_ADDED,
    SB_FAB_STATUS_EGRESS_SHAPER_BAG_CONFLICT,
    SB_FAB_STATUS_EGRESS_SHAPER_BAD_PARAMS,
    SB_FAB_STATUS_EGRESS_SHAPER_CONFIGURE_FAILED,
    SB_FAB_STATUS_BW_ENABLE_FAILED,
    SB_FAB_STATUS_TARGET_LOGICAL_PORT_UPDATE_FAILED,
    SB_FAB_STATUS_WRED_BAD_PARAMS,
    SB_FAB_STATUS_WRED_ENTRY_NOT_PRESENT,
    SB_FAB_STATUS_WRED_CONFIGURATION_FAILED,
    SB_FAB_STATUS_ADD_DEVICE_EXCEEDS_MAX_ALLOWBLE_DEVICES,
    SB_FAB_STATUS_SERIALIZER_FAILED,
    SB_FAB_STATUS_DEVICE_NOT_FOUND,
    SB_FAB_STATUS_TARGET_HW_ERROR,
    SB_FAB_STATUS_NO_HANDLE_RESOURCE,
    SB_FAB_STATUS_HANDLE_LIST_INCONSISTENCY,
    SB_FAB_STATUS_HANDLE_INVALID,
    SB_FAB_STATUS_HANDLE_ERROR,
    SB_FAB_STATUS_HANDLE_IN_USE,
    SB_FAB_STATUS_SERIALIZER_LINE_LOOPBACK_UNAVAILABLE,
    SB_FAB_STATUS_SERIALIZER_LOOPBACK_ACTION_TRANSPORT_FAILED,
    SB_FAB_STATUS_SET_INGRESS_PARAMS_FAILED,
    SB_FAB_STATUS_SET_PATH_PARAMS_FAILED,
    SB_FAB_STATUS_LOGICAL_PORT_FLOW_QOS_INCOMPATIBLE,
    SB_FAB_STATUS_TARGET_SET_LOOPBACK_FAILED,
    SB_FAB_STATUS_SERIALIZER_PRBS_CONFIG_FAILED,
    SB_FAB_STATUS_ACTION_NOT_SUPPORTED_ON_DEVICE,

    /* XXX Temporary */
    SB_FAB_STATUS_UNIMPLEMENTED,

    SB_FAB_STATUS_LAST
} sbFabStatus_et;

char * sbGetFabStatusString(sbStatus_t status);

#define sbFabStatus_t sbFabStatus_et


typedef uint32 sbFabUserDeviceHandle_t;

#ifdef SB_FAB_DEBUG_TRACE
#define SB_FAB_ENTER() _SB_FAB_LOGF(0, "Enter.\n");
#define SB_FAB_LEAVE() _SB_FAB_LOGF(0, "Leave.\n");
#define SB_FAB_VERIFY(x...) do{_SB_FAB_LOGF(0,"%d: Assert if 0x0 == 0x%08x (%s)\n",__LINE__,(uint32)(x), #x);if((x)==0){assert(0);}}while(0)
#else
#define SB_FAB_ENTER()
#define SB_FAB_LEAVE()
#define SB_FAB_VERIFY(x) do{if((x)==0){assert(0);}}while(0)
#endif

#define SB_FAB_TARGET_DEVICE_LINK_IMPLEMENTATION_TYPE_UNKNOWN                  (0x438A0000)
#define SB_FAB_TARGET_DEVICE_LINK_IMPLEMENTATION_TYPE_RAMBUS_RS2314            (0x438A0001)
#define SB_FAB_TARGET_DEVICE_LINK_IMPLEMENTATION_TYPE_HYPERCORE                (0x438A0002)

#endif /* _SOC_SBX_SB_FAB_STATUS_H_ */
