
# $Id: Makefile,v 1.1.2.2 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for bm9600 mbcm driver Library
#

LOCALDIR = src/bcm/sbx/bm9600

include ${SDK}/make/Make.config

lib = libbm9600

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
