#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# $Id: $
LOCALDIR = src/appl/diag/phymod

include ${SDK}/make/Make.config

lib = libdiag_phymod

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
