# $Id$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
LOCALDIR = src/soc/dnx/legacy/SAND/SAND_FM

include ${SDK}/make/Make.config

lib = libsoc_dnxlegacysandsandfm

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
