#!/bin/bash

echo "========================================================================="
echo "ARCH             = $ARCH"
echo "KERNDIR          = $KERNDIR"
echo "SDK_VER          = $SDK_VER"
echo "SDK              = $SDK"
echo "TARGET           = $TARGET"
echo "TOOLCHAIN_DIR    = $TOOLCHAIN_DIR"
echo "PATH             = $PATH"
echo "CROSS_COMPILE    = $CROSS_COMPILE"
echo "LDFLAGS          = $LDFLAGS"
echo "OPT_CFLAGS       = $OPT_CFLAGS"
echo "MODULE_LDFLAGS   = $MODULE_LDFLAGS"
echo "LINUX_INCLUDE    = $LINUX_INCLUDE"
echo "LINUX_MAKE_FLAGS = $LINUX_MAKE_FLAGS"
echo "MRV_STANDALONE   = $MRV_STANDALONE"
echo "CFLAGS           = $CFLAGS"
echo "========================================================================="
