# $Id:  Exp $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# $Id: Makefile,v 1.3 Broadcom SDK $
# Makefile for Trident2plus SOC driver Library
#

LOCALDIR = src/soc/esw/trident2p

include ${SDK}/make/Make.config

lib = libsoc_trident2p

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

