#
# $Id: Makefile,v 1.3 Broadcom SDK $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/dpp/ARAD/

include ${SDK}/make/Make.config

lib = libbcm_dpp_arad_pp

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
