# $Id: Makefile,v 1.2 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/esw/titan

include ${SDK}/make/Make.config

lib = libtitan

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
