# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC SAL support
#
LOCALDIR = src/sal/core

include ${SDK}/make/Make.config

subdirs=${targetbase}
include ${SDK}/make/Make.subdirs

lib = libsal_core
include ${SDK}/make/Make.kernlib

include ${SDK}/make/Make.depend
