# $Id: Makefile.linux-x86-rh72,v 1.4 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$

# Default Linux include directory
ifeq (,$(LINUX_INCLUDE))
LINUX_INCLUDE = /projects/ntsw-tools/linux/headers/rh-7.2-x86/include
endif

include ${SDK}/make/Makefile.linux-x86-common
