KBUILD_VERBOSE = 1
export KBUILD_VERBOSE

AUTOCONF = $(LINUX_INCLUDE)/include/generated/autoconf.h

# gcc system include path
SYSINC = $(shell ${CC} -print-search-dirs | grep install | cut -c 10-)include
