# $Id: Makefile.linux-metrocore_xes-2_6,v 1.9 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$

SBX_CHIPS = 1

# Look for custom tools
ifneq (,$(MIPS_TOOLS_DIR))
override PATH := $(MIPS_TOOLS_DIR):$(PATH)
endif
ifneq (,$(MIPS_CROSS_COMPILE))
override CROSS_COMPILE := $(MIPS_CROSS_COMPILE)
endif

# Default tools
ifeq (,$(CROSS_COMPILE))
CROSS_COMPILE := mips_4KC-
override PATH := /tools/eldk/4.0/usr/bin:$(PATH)
endif

# Default Linux Kernel directory
ifeq (,$(KERNDIR))
KERNDIR := /projects/ntsw-tools/linux/linux-2.6.16-xes_r3-20070628
endif
# Default Linux include directory
ifeq (,$(LINUX_INCLUDE))
LINUX_INCLUDE := $(KERNDIR)/include
endif

CFGFLAGS += -DSYS_BE_PIO=1 -DSYS_BE_PACKET=0 -DSYS_BE_OTHER=1
CFGFLAGS += -DBCM_PLATFORM_STRING=\"Metrocore_AMCC440GX\"
ENDIAN = BE_HOST=1
CFGFLAGS += -D$(ENDIAN)

ARCH = ppc

# From linux/arch/mips/Makefile
ifeq (,$(KFLAGS))
KFLAGS := -D__KERNEL__ -Wno-trigraphs -O0 -msoft-float -pipe -Wno-uninitialized -mmultiple -mstring -Wa,-m405 -mcpu=405 -meabi
endif

CFLAGS +=      -DBCM_PLX9656_LOCAL_BUS

ifneq ($(targetplat),user)
include ${SDK}/make/Makefile.linux-kernel-2_6
endif
