# $Id$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$

#LOCALDIR = src/soc/ces

#include ${SDK}/make/Make.config

#subdirs = nemo_driver
#subdirs += clsbuilder
#subdirs += sal

#include ${SDK}/make/Make.subdirs
