# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# Makefile for ALPM SOC driver Library
#

LOCALDIR = src/soc/esw/alpm

include ${SDK}/make/Make.config

lib = libsoc_alpm

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

