# $Id: Makefile,v 1.3 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC COMMON driver Library
#
LOCALDIR = src/soc/common

include ${SDK}/make/Make.config

lib = libsoccommon

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
