/* $Id: $
 * 
 * $Copyright: (c) 2016 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
*/
#ifndef _SHR_sw_state_dpp_soc_jericho_H_
#define _SHR_sw_state_dpp_soc_jericho_H_


#include <shared/swstate/layout/sw_state_dpp_soc_jericho_pp_mpls_term_layout.h>
#include <shared/swstate/layout/sw_state_dpp_soc_jericho_tm_ingress_reserved_resource_layout.h>
#include <shared/swstate/layout/sw_state_dpp_soc_jericho_tm_is_tdm_queuing_on_layout.h>
#include <shared/swstate/layout/sw_state_dpp_soc_jericho_tm_nof_remote_faps_with_remote_credit_value_layout.h>
#include <shared/swstate/layout/sw_state_dpp_soc_jericho_tm_pfc_gen_bmp_layout.h>
#define SW_STATE_DPP_SOC_JERICHO_TM_LAYOUT_NOF_MAX_LAYOUT_NODES (1 + SW_STATE_DPP_SOC_JERICHO_TM_NOF_REMOTE_FAPS_WITH_REMOTE_CREDIT_VALUE_LAYOUT_NOF_MAX_LAYOUT_NODES + SW_STATE_DPP_SOC_JERICHO_TM_PFC_GEN_BMP_LAYOUT_NOF_MAX_LAYOUT_NODES + SW_STATE_DPP_SOC_JERICHO_TM_INGRESS_RESERVED_RESOURCE_LAYOUT_NOF_MAX_LAYOUT_NODES + SW_STATE_DPP_SOC_JERICHO_TM_IS_TDM_QUEUING_ON_LAYOUT_NOF_MAX_LAYOUT_NODES) 
#define SW_STATE_DPP_SOC_JERICHO_PP_LAYOUT_NOF_MAX_LAYOUT_NODES (1 + SW_STATE_DPP_SOC_JERICHO_PP_MPLS_TERM_LAYOUT_NOF_MAX_LAYOUT_NODES) 
#define SW_STATE_DPP_SOC_JERICHO_LAYOUT_NOF_MAX_LAYOUT_NODES (1 + SW_STATE_DPP_SOC_JERICHO_TM_LAYOUT_NOF_MAX_LAYOUT_NODES + SW_STATE_DPP_SOC_JERICHO_PP_LAYOUT_NOF_MAX_LAYOUT_NODES) 

#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
int sw_state_dpp_soc_jericho_layout_node_create(int unit, int* root_node_id, uint32* next_free_node_id);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 
#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
int sw_state_dpp_soc_jericho_tm_layout_node_create(int unit, int* root_node_id, uint32* next_free_node_id);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 
#if defined(BCM_PETRA_SUPPORT)
#ifdef BCM_PETRA_SUPPORT
int sw_state_dpp_soc_jericho_pp_layout_node_create(int unit, int* root_node_id, uint32* next_free_node_id);
#endif /* BCM_PETRA_SUPPORT*/ 
#endif /* defined(BCM_PETRA_SUPPORT)*/ 

#endif /* _SHR_sw_state_dpp_soc_jericho_H_ */
