# Makefile,v 1.2 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# $Id: Makefile,v 1.6 2012/11/06 02:37:31 vinodhkc Exp $
# Makefile for Caladan3 SOC driver Library
#

LOCALDIR = src/soc/sbx/caladan3/sws

include ${SDK}/make/Make.config

lib = libsoc_sbx_caladan3_sws

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
