#
# $Id: Makefile,v 1.2 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for dfe subdirectory
#

LOCALDIR = src/soc/dfe/fe3200

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libsoc_dfe_fe3200

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

