# $Id: $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
# $Id$
# Makefile for Greyhound2 SOC driver Library
#

LOCALDIR = src/soc/esw/greyhound2

include ${SDK}/make/Make.config

lib = libsoc_greyhound2

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
