# $Id$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC driver Library
#

LOCALDIR = src/bcm/esw/triumph

include ${SDK}/make/Make.config

lib = libtriumph

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
