# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
LOCALDIR = src/appl/diag/esw

include ${SDK}/make/Make.config

subdirs := techsupport

include ${SDK}/make/Make.subdirs

lib = libdiag_esw

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
