
# $Id: Makefile,v 1.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for caladan3/g3p1 ucode Library
#

LOCALDIR = src/bcm/sbx/caladan3/oam

include ${SDK}/make/Make.config

lib = libcaladan3oam

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
