#
# $Id$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for dpp subdirectory
#

LOCALDIR = src/soc/dnxc

include ${SDK}/make/Make.config

subdirs = legacy

include ${SDK}/make/Make.subdirs

lib = libsoc_dnxc

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

