#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/init

include ${SDK}/make/Make.config

#subdirs = vlan

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxinit

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

