# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/esw/flexctr

include ${SDK}/make/Make.config

lib = libflexctr

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
