# $Id$
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/dnxf

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxf

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
