#
# $Id: Makefile,v 1.2 Broadcom SDK $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
export TARGET
export BLDDIR
export LIBDIR

LOCALDIR = src/appl/dcmn/interrupts

include ${SDK}/make/Make.config

lib = libappl_dcmn_interrupts

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

