#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$

LOCALDIR = src/appl/diag/dnx/init

include ${SDK}/make/Make.config

lib = libdiag_dnxinit

include ${SDK}/make/Make.subdirs
include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
