# $Id: Makefile,v 1.1 Broadcom SDK $
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
LOCALDIR = src/soc/sbx/g3p1

include ${SDK}/make/Make.config

G2_INC  = ${SDK}/include/soc/sbx/g3p1

lib = libsoc_sbx_g3p1

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
