#
#
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

LOCALDIR = src/soc/dnx/drv

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/soc/dnx

include ${SDK}/make/Make.subdirs

lib = libsoc_dnxdrv

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
