# -*- Makefile -*-
# $Id: Makefile,v 1.2 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
LOCALDIR = src/appl/diag/aps

include ${SDK}/make/Make.config

lib = libdiag_aps

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
