#
# $Id: Makefile,v 1.4 Broadcom SDK $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#


LOCALDIR = src/bcm/dnx/algo

include ${SDK}/make/Make.config

#subdirs = algo
subdirs += res_mngr
subdirs += template_mngr
subdirs += l3
subdirs += lif_mngr
subdirs += mirror


include ${SDK}/make/Make.subdirs

lib = libbcm_dnxalgo

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

