# -*- Makefile -*-
# $Id:  $
# $Copyright: (c) 2016 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC driver Library
#
LOCALDIR = src/soc/robo/gex/northstar

include ${SDK}/make/Make.config

lib = libsocrobo_northstar
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

